%% View: Domain-Focus | Parent: 15-dq-check-workflow-full.mermaid
flowchart TB

    N1["B"]
    N2["B1"]
    N3["C"]
    N4["B2"]
    N5["B3"]
    N6["B4"]
    N7["A"]
    N8["O"]
    N9["P"]
    N10["Q"]
    N11["J"]
    N12["M"]
    N13["I"]
    N14["L"]
    N15["K"]
    N16["H"]
    N17["D"]
    N18["E"]
    N19["F"]
    N20["G"]

    N1 --> N2
    N1 --> N4
    N1 --> N5
    N1 --> N6
    N7 --> N1
    N2 --> N3
    N4 --> N3
    N5 --> N3
    N6 --> N3
    N17 --> N16
    N18 --> N13
    N19 --> N11
    N20 --> N15
    N16 --> N14
    N13 --> N14
    N13 --> N12
    N11 --> N14
    N11 --> N12
    N15 --> N12
    N1 --> N8
    N1 --> N9
    N1 --> N10
