%% View: Overview | Parent: 21-activity-entity-data-flow-full.mermaid
%% @uniform width=140 height=56 max_title_len=3 max_desc_lines=0
flowchart TB

    N1["E1&nbsp;"]
    N2["E2&nbsp;"]
    N3["E3&nbsp;"]
    N4["E4&nbsp;"]
    N5["T1&nbsp;"]
    N6["T2&nbsp;"]
    N7["T3&nbsp;"]
    N8["T4&nbsp;"]
    N9["V1&nbsp;"]
    N10["V2&nbsp;"]
    N11["V3&nbsp;"]
    N12["API"]
    N13["V4&nbsp;"]
    N14["L1&nbsp;"]
    N15["L2&nbsp;"]

    N12 --> N1
    N1 --> N2
    N2 --> N3
    N3 --> N4
    N4 --> N5
    N5 --> N6
    N6 --> N7
    N7 --> N8
    N8 --> N9
    N9 --> N10
    N10 --> N11
    N11 --> N13
    N14 --> N15

    linkStyle 0 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 1 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 2 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 3 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 4 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 5 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 6 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 7 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 8 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 9 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 10 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 11 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 12 stroke:#475569,stroke-width:2px,stroke-dasharray:5
