%% View: Data-Flow | Parent: 21-activity-entity-data-flow-full.mermaid
flowchart TB

    N1["E1"]
    N2["E2"]
    N3["E3"]
    N4["E4"]
    N5["T1"]
    N6["T2"]
    N7["T3"]
    N8["T4"]
    N9["V1"]
    N10["V2"]
    N11["V3"]
    N12["API"]

    N12 --> N1
    N1 --> N2
    N2 --> N3
    N3 --> N4
    N4 --> N5
    N5 --> N6
    N6 --> N7
    N7 --> N8
    N8 --> N9
    N9 --> N10
    N10 --> N11

    linkStyle 0 stroke:#1E293B,stroke-width:4px
    linkStyle 1 stroke:#1E293B,stroke-width:4px
    linkStyle 2 stroke:#1E293B,stroke-width:4px
    linkStyle 3 stroke:#1E293B,stroke-width:4px
    linkStyle 4 stroke:#1E293B,stroke-width:4px
    linkStyle 5 stroke:#1E293B,stroke-width:4px
    linkStyle 6 stroke:#1E293B,stroke-width:4px
    linkStyle 7 stroke:#1E293B,stroke-width:4px
    linkStyle 8 stroke:#1E293B,stroke-width:4px
    linkStyle 9 stroke:#1E293B,stroke-width:4px
    linkStyle 10 stroke:#1E293B,stroke-width:4px
