%% View: Data-Flow | Parent: 21-activity-entity-data-flow-full.mermaid
flowchart TB

    N1["E1"]
    N2["E2"]
    N3["E3"]
    N4["E4"]
    N5["T1"]
    N6["T2"]
    N7["T3"]
    N8["T4"]
    N9["V1"]
    N10["V2"]
    N11["V3"]
    N12["API"]

    N12 --> N1
    N1 --> N2
    N2 --> N3
    N3 --> N4
    N4 --> N5
    N5 --> N6
    N6 --> N7
    N7 --> N8
    N8 --> N9
    N9 --> N10
    N10 --> N11
