%% View: Infrastructure-Mapping | Parent: 21-activity-entity-data-flow-full.mermaid
flowchart TB

    N1["LocalFS"]
    N2["E1"]
    N3["E2"]
    N4["E3"]
    N5["E4"]
    N6["T1"]
    N7["T2"]
    N8["T3"]
    N9["T4"]
    N10["V1"]
    N11["V2"]
    N12["V3"]
    N13["API"]
    N14["V4"]
    N15["L1"]
    N16["L2"]
    N17["Assay"]
    N18["Molecule"]
    N19["Target"]
    N20["Q"]

    N13 --> N2
    N2 --> N3
    N3 --> N4
    N4 --> N5
    N5 --> N6
    N6 --> N7
    N7 --> N8
    N8 --> N9
    N9 --> N10
    N10 --> N11
    N11 --> N12
    N12 --> N14
    N15 --> N16

    linkStyle 0 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 1 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 2 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 3 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 4 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 5 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 6 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 7 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 8 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 9 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 10 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 11 stroke:#475569,stroke-width:2px,stroke-dasharray:5
    linkStyle 12 stroke:#475569,stroke-width:2px,stroke-dasharray:5
