%% View: Data-Flow | Parent: 32-single-record-journey-full.mermaid
%% @uniform width=140 height=56 max_title_len=5 max_desc_lines=0
flowchart TB

    N1["SW&nbsp;&nbsp;&nbsp;"]
    N2["ST&nbsp;&nbsp;&nbsp;"]
    N3["TFG&nbsp;&nbsp;"]
    N4["GV&nbsp;&nbsp;&nbsp;"]
    N5["GW&nbsp;&nbsp;&nbsp;"]
    N6["CLEAN"]
    N7["WARN&nbsp;"]
    N8["GT&nbsp;&nbsp;&nbsp;"]
    N9["BW&nbsp;&nbsp;&nbsp;"]
    N10["BF&nbsp;&nbsp;&nbsp;"]
    N11["BT&nbsp;&nbsp;&nbsp;"]
    N12["TI&nbsp;&nbsp;&nbsp;"]

    N9 --> N10
    N10 --> N11
    N11 --> N12
    N6 --> N1
    N7 --> N1
    N1 --> N2
    N2 --> N3
    N3 --> N4
    N4 --> N5
    N5 --> N8

    linkStyle 0 stroke:#1E293B,stroke-width:4px
    linkStyle 1 stroke:#1E293B,stroke-width:4px
    linkStyle 2 stroke:#1E293B,stroke-width:4px
    linkStyle 3 stroke:#1E293B,stroke-width:4px
    linkStyle 4 stroke:#1E293B,stroke-width:4px
    linkStyle 5 stroke:#1E293B,stroke-width:4px
    linkStyle 6 stroke:#1E293B,stroke-width:4px
    linkStyle 7 stroke:#1E293B,stroke-width:4px
    linkStyle 8 stroke:#1E293B,stroke-width:4px
    linkStyle 9 stroke:#1E293B,stroke-width:4px
