"""DEPRECATED: Import from bioetl.domain.configs instead.

This module is a backward compatibility shim and will be removed in v2.0.
All configuration models have been moved to the domain layer.

Migration guide: docs/migration/v2.0-import-changes.md
"""

import warnings

warnings.warn(
    "Importing from bioetl.infrastructure.config.models is deprecated. "
    "Use bioetl.domain.configs instead. This module will be removed in v2.0.",
    DeprecationWarning,
    stacklevel=2,
)

# Re-export all configuration models from domain.configs for backward compatibility
from bioetl.domain.configs import (  # noqa: E402, F401
    BaseProviderConfig,
    BusinessKeyConfig,
    CanonicalizationConfig,
    ChemblSourceConfig,
    ClientDefaultsConfig,
    CsvInputConfig,
    DataFlowConfig,
    DataSinkConfig,
    DataSourceConfig,
    DefaultsConfig,
    DeterminismConfig,
    DummyProviderConfig,
    ExecutionConfig,
    FeatureFlagsConfig,
    HashingConfig,
    HashingDefaultsConfig,
    HttpClientConfig,
    HttpDefaultsConfig,
    InterfaceFeaturesConfig,
    LoggingConfig,
    MetricsConfig,
    NetworkDefaultsConfig,
    NetworkHttpDefaultsConfig,
    NormalizationConfig,
    NormalizationDefaultsConfig,
    ObservabilityConfig,
    OutputOptionsConfig,
    PaginationConfig,
    PipelineConfig,
    PipelineIdentityConfig,
    PipelineManifest,
    PipelineStagesConfig,
    ProfileConfig,
    ProviderConfigUnion,
    ProviderHttpConfig,
    QualityConfig,
    QualityControlConfig,
    RuntimeConfig,
    SourceDefaultsConfig,
    SourcesDefaultsConfig,
    StorageConfig,
    TransformConfig,
)

__all__ = [
    "BaseProviderConfig",
    "BusinessKeyConfig",
    "CanonicalizationConfig",
    "ChemblSourceConfig",
    "ClientDefaultsConfig",
    "CsvInputConfig",
    "DataFlowConfig",
    "DataSinkConfig",
    "DataSourceConfig",
    "DefaultsConfig",
    "DeterminismConfig",
    "DummyProviderConfig",
    "ExecutionConfig",
    "FeatureFlagsConfig",
    "HashingConfig",
    "HashingDefaultsConfig",
    "HttpClientConfig",
    "HttpDefaultsConfig",
    "InterfaceFeaturesConfig",
    "LoggingConfig",
    "MetricsConfig",
    "NetworkDefaultsConfig",
    "NetworkHttpDefaultsConfig",
    "NormalizationConfig",
    "NormalizationDefaultsConfig",
    "ObservabilityConfig",
    "OutputOptionsConfig",
    "PaginationConfig",
    "PipelineConfig",
    "PipelineIdentityConfig",
    "PipelineManifest",
    "PipelineStagesConfig",
    "ProfileConfig",
    "ProviderConfigUnion",
    "ProviderHttpConfig",
    "QualityConfig",
    "QualityControlConfig",
    "RuntimeConfig",
    "SourceDefaultsConfig",
    "SourcesDefaultsConfig",
    "StorageConfig",
    "TransformConfig",
]
