version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    groups:
      pip-minor-patch:
        patterns: ["*"]
        update-types:
          ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "ci/cd"
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci/cd"
    groups:
      docker:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      npm-root:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/.github/actions/setup-mermaid"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci/cd"
    groups:
      npm-mermaid:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/.github/tooling/jscpd"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci/cd"
    groups:
      npm-jscpd:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/grafana/plugins/bioetl-scenes-app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      npm-grafana-scenes:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/grafana/plugins/bioetl-selectorshell-panel"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      npm-grafana-selectorshell:
        patterns: ["*"]
