# ruff: noqa: E501
"""Golden records snapshot for assay_chembl."""

import json

expected_assay_records = json.loads(
    """
[
    {
        "aidx": "cld0",
        "assay_category": null,
        "assay_cell_type": null,
        "assay_chembl_id": "CHEMBL1000139",
        "assay_classifications": null,
        "assay_group": null,
        "assay_organism": "cavia porcellus",
        "assay_parameters": null,
        "assay_strain": null,
        "assay_subcellular_fraction": "membrane",
        "assay_tax_id": 10141.0,
        "assay_test_type": null,
        "assay_tissue": "liver",
        "assay_type": "B",
        "assay_type_description": "binding",
        "bao_format": "BAO_0000249",
        "bao_label": "cell membrane format",
        "cell_chembl_id": null,
        "confidence_description": "direct single protein target assigned",
        "confidence_score": 9,
        "description": "displacement of [3h](-)-(s)-emopamil from ebp in guinea pig liver membrane",
        "document_chembl_id": "CHEMBL1140235",
        "relationship_description": "direct protein target assigned",
        "relationship_type": "d",
        "score": null,
        "src_assay_id": null,
        "src_id": 1.0,
        "target_chembl_id": "CHEMBL5525",
        "tissue_chembl_id": "CHEMBL3559723",
        "variant_sequence": null,
        "hash_row": "4a5704b09673040952fee2534fafe46306f8e4d0a94fa02a03711701c942e224",
        "hash_business_key": "f9cf8feb6fd7c5abce76c81acc7e34dc2b530940b72520696a772aea51b876b8",
        "index": 0,
        "database_version": "ChEMBL_36",
        "extracted_at": "2025-12-06T12:42:34.383793+00:00"
    },
    {
        "aidx": "cld0",
        "assay_category": null,
        "assay_cell_type": null,
        "assay_chembl_id": "CHEMBL1000140",
        "assay_classifications": null,
        "assay_group": null,
        "assay_organism": "cavia porcellus",
        "assay_parameters": null,
        "assay_strain": null,
        "assay_subcellular_fraction": "membrane",
        "assay_tax_id": 10141.0,
        "assay_test_type": null,
        "assay_tissue": "brain",
        "assay_type": "B",
        "assay_type_description": "binding",
        "bao_format": "BAO_0000249",
        "bao_label": "cell membrane format",
        "cell_chembl_id": null,
        "confidence_description": "direct single protein target assigned",
        "confidence_score": 9,
        "description": "displacement of [3h](+)-pentazocine from sigma 1 receptor in guinea pig brain membrane without cerebellum",
        "document_chembl_id": "CHEMBL1140235",
        "relationship_description": "direct protein target assigned",
        "relationship_type": "d",
        "score": null,
        "src_assay_id": null,
        "src_id": 1.0,
        "target_chembl_id": "CHEMBL4153",
        "tissue_chembl_id": "CHEMBL3638188",
        "variant_sequence": null,
        "hash_row": "dad2c0b30962a0604656d2c389b496a0f906daad6234becbc2b485d78966f1e3",
        "hash_business_key": "6fcaf3d536e9395e60727edc9ff9d8e78be030efa62816d4922a79ec45297198",
        "index": 1,
        "database_version": "ChEMBL_36",
        "extracted_at": "2025-12-06T12:42:34.383793+00:00"
    },
    {
        "aidx": "cld0",
        "assay_category": null,
        "assay_cell_type": null,
        "assay_chembl_id": "CHEMBL1000236",
        "assay_classifications": null,
        "assay_group": null,
        "assay_organism": "homo sapiens",
        "assay_parameters": null,
        "assay_strain": null,
        "assay_subcellular_fraction": null,
        "assay_tax_id": 9606.0,
        "assay_test_type": null,
        "assay_tissue": null,
        "assay_type": "B",
        "assay_type_description": "binding",
        "bao_format": "BAO_0000357",
        "bao_label": "single protein format",
        "cell_chembl_id": null,
        "confidence_description": "direct single protein target assigned",
        "confidence_score": 9,
        "description": "displacement of [3h]pdbu form human pkcalpha in presence of phosphatidylserine",
        "document_chembl_id": "CHEMBL1138492",
        "relationship_description": "direct protein target assigned",
        "relationship_type": "d",
        "score": null,
        "src_assay_id": null,
        "src_id": 1.0,
        "target_chembl_id": "CHEMBL299",
        "tissue_chembl_id": null,
        "variant_sequence": null,
        "hash_row": "c6332598cc48fd0c95f9387c2059c3d74ebd0031910b1d39d85a5d40a54960a6",
        "hash_business_key": "6a17c91605742476e186b310b2884895775102581964832738c230fecfeef89b",
        "index": 3,
        "database_version": "ChEMBL_36",
        "extracted_at": "2025-12-06T12:42:34.383793+00:00"
    },
    {
        "aidx": "cld0",
        "assay_category": null,
        "assay_cell_type": null,
        "assay_chembl_id": "CHEMBL1000237",
        "assay_classifications": null,
        "assay_group": null,
        "assay_organism": "homo sapiens",
        "assay_parameters": null,
        "assay_strain": null,
        "assay_subcellular_fraction": null,
        "assay_tax_id": 9606.0,
        "assay_test_type": null,
        "assay_tissue": null,
        "assay_type": "B",
        "assay_type_description": "binding",
        "bao_format": "BAO_0000357",
        "bao_label": "single protein format",
        "cell_chembl_id": null,
        "confidence_description": "direct single protein target assigned",
        "confidence_score": 9,
        "description": "displacement of [3h]pdbu form human pkcbeta in presence of phosphatidylserine",
        "document_chembl_id": "CHEMBL1138492",
        "relationship_description": "direct protein target assigned",
        "relationship_type": "d",
        "score": null,
        "src_assay_id": null,
        "src_id": 1.0,
        "target_chembl_id": "CHEMBL3045",
        "tissue_chembl_id": null,
        "variant_sequence": null,
        "hash_row": "d261206f6bc472e3c891dcb0bc6fd2e9bac96b7c3729d0df76f4d05d3bb0e68a",
        "hash_business_key": "bed37edca40e8899d96102d7a91ca7d6e408223f800c4e2be80339eacf9803bf",
        "index": 4,
        "database_version": "ChEMBL_36",
        "extracted_at": "2025-12-06T12:42:34.383793+00:00"
    },
    {
        "aidx": "cld0",
        "assay_category": null,
        "assay_cell_type": null,
        "assay_chembl_id": "CHEMBL1000238",
        "assay_classifications": null,
        "assay_group": null,
        "assay_organism": "homo sapiens",
        "assay_parameters": null,
        "assay_strain": null,
        "assay_subcellular_fraction": null,
        "assay_tax_id": 9606.0,
        "assay_test_type": null,
        "assay_tissue": null,
        "assay_type": "B",
        "assay_type_description": "binding",
        "bao_format": "BAO_0000357",
        "bao_label": "single protein format",
        "cell_chembl_id": null,
        "confidence_description": "direct single protein target assigned",
        "confidence_score": 9,
        "description": "displacement of [3h]pdbu form human pkcgamma in presence of phosphatidylserine",
        "document_chembl_id": "CHEMBL1138492",
        "relationship_description": "direct protein target assigned",
        "relationship_type": "d",
        "score": null,
        "src_assay_id": null,
        "src_id": 1.0,
        "target_chembl_id": "CHEMBL2938",
        "tissue_chembl_id": null,
        "variant_sequence": null,
        "hash_row": "9f71734c047f2eac8f4c6f747b802b3fba28a870c68c7a2e1ec3c112f75651a6",
        "hash_business_key": "bc30190ee48ac8b705109103ba4a54c4bb8878de98f3cc534b640f388c2abfb9",
        "index": 5,
        "database_version": "ChEMBL_36",
        "extracted_at": "2025-12-06T12:42:34.383793+00:00"
    },
    {
        "aidx": "cld0",
        "assay_category": null,
        "assay_cell_type": null,
        "assay_chembl_id": "CHEMBL1000239",
        "assay_classifications": null,
        "assay_group": null,
        "assay_organism": "homo sapiens",
        "assay_parameters": null,
        "assay_strain": null,
        "assay_subcellular_fraction": null,
        "assay_tax_id": 9606.0,
        "assay_test_type": null,
        "assay_tissue": null,
        "assay_type": "B",
        "assay_type_description": "binding",
        "bao_format": "BAO_0000357",
        "bao_label": "single protein format",
        "cell_chembl_id": null,
        "confidence_description": "direct single protein target assigned",
        "confidence_score": 9,
        "description": "displacement of [3h]pdbu form human pkcdelta in presence of phosphatidylserine",
        "document_chembl_id": "CHEMBL1138492",
        "relationship_description": "direct protein target assigned",
        "relationship_type": "d",
        "score": null,
        "src_assay_id": null,
        "src_id": 1.0,
        "target_chembl_id": "CHEMBL2996",
        "tissue_chembl_id": null,
        "variant_sequence": null,
        "hash_row": "f8ac640991b5f92e662f083553bf5f245054b036a1dd51f44b0e37ebc02addfe",
        "hash_business_key": "7531402aa9faece4c5435a5754ef055b243d02f9ec4704cd0cc45efc369c5c6f",
        "index": 6,
        "database_version": "ChEMBL_36",
        "extracted_at": "2025-12-06T12:42:34.383793+00:00"
    }
]
"""
)
