# ruff: noqa: E501
"""Golden records snapshot for document_chembl."""

import json

expected_document_records = json.loads("""
[
    {
        "abstract": "a new route to 5-(p-hydroxybenzyl)pyrimidines has been developed which utilizes phenolic mannich bases plus pyrimidines containing at least two activating groups. the products can be alkylated on the phenolic oxygen or on the pyrimidine n-1 atom, depending on conditions. this method has been used to prepare trimethoprim, a broad-spectrum antibacterial agent, starting from 2,4-diaminopyrimidine and 2,6-dimethoxyphenol.",
        "authors": "roth b, strelitz jz, rauckman bs.",
        "chembl_release": "chembl_release:CHEMBL_1|creation_date:2009-09-03",
        "contact": null,
        "doc_type": "PUBLICATION",
        "document_chembl_id": "CHEMBL1121421",
        "doi": "10.1021/jm00178a007",
        "doi_chembl": null,
        "first_page": 379,
        "issue": 4.0,
        "journal": "j med chem",
        "journal_full_title": "journal of medicinal chemistry.",
        "last_page": 384,
        "patent_id": null,
        "pubmed_id": 6991692,
        "score": null,
        "src_id": 1.0,
        "title": "2,4-diamino-5-benzylpyrimidines and analogues as antibacterial agents. 2. c-alkylation of pyrimidines with mannich bases and application to the synthesis of trimethoprim and analogues.",
        "volume": 23,
        "year": 1980.0,
        "hash_row": "ae0b902a3ebd8d36580dc14ce7c6626f4b2a530300a0deeed1639c3b3a2f3ded",
        "hash_business_key": "4d294e25d5727e881363ed0b558d47fa78247326f48e3943293ce26698ed4919",
        "index": 771,
        "database_version": "ChEMBL_36",
        "extracted_at": "2025-12-06T13:34:13.027556+00:00"
    },
    {
        "abstract": "a fluorinated derivative of the benzomorphan opiate agonist phenazocine, (+/-)-5,9 alpha-dimethyl-2-[2-(4-fluorophenyl)ethyl]-2'-hydroxy-6, 7-benzomorphan (fluorophen), was prepared by n-acylation of (+/-)-5,9 alpha-dimethyl-2'-hydroxybenzomorphan with (p-fluorophenyl)acetyl chloride, followed by diborane reduction of the resulting amide. fluorination produces only a twofold opiate receptor affinity loss when measured either by bioassay or receptor binding (selectivity mu congruent to delta greater than kappa). labeled with 18f, fluorophen should be sufficiently potent to be useful as an in vivo probe for visualizing opiate receptors by positron emission transaxial tomography (pett).",
        "authors": "rice kc, konicki pe, quirion r, burke tr, pert cb.",
        "chembl_release": "chembl_release:CHEMBL_1|creation_date:2009-09-03",
        "contact": null,
        "doc_type": "PUBLICATION",
        "document_chembl_id": "CHEMBL1122397",
        "doi": "10.1021/jm00365a017",
        "doi_chembl": null,
        "first_page": 1643,
        "issue": 11.0,
        "journal": "j med chem",
        "journal_full_title": "journal of medicinal chemistry.",
        "last_page": 1645,
        "patent_id": null,
        "pubmed_id": 6313921,
        "score": null,
        "src_id": 1.0,
        "title": "synthesis and pharmacological characterization of (+/-)-5,9 alpha-dimethyl-2-[2-(4-fluorophenyl)ethyl]-2'-hydroxy-6,7-benzomorphan (fluorophen), a ligand suitable for visualization of opiate receptors in vivo.",
        "volume": 26,
        "year": 1983.0,
        "hash_row": "4c2a3638c1102a15339c0fcb7441a9d00af6db7550062cd10deb140909af1bab",
        "hash_business_key": "27516297a0a19a55e92d62aa1e09ed68d0e4a89f7d71db7e9eac6441ffabbdd8",
        "index": 480,
        "database_version": "ChEMBL_36",
        "extracted_at": "2025-12-06T13:34:13.027556+00:00"
    },
    {
        "abstract": "a close analogue of the antileukemic agent 5,8-dideaza-n10 propargylfolic acid (2) was synthesized by replacing the propargyl moiety of 2 with a cyanomethyl group. this compound, n10-(cyanomethyl)-5,8-dideazafolic acid (3), was evaluated for its antifolate and antitumor activities in several biological test systems. alkylation of diethyl n-(4-aminobenzoyl)-l-glutamate with bromoacetonitrile gave diethyl n-[4-[(cyanomethyl)amino]benzoyl]-l-glutamate (7). reaction of 7 with 2 amino-6-(bromomethyl)-4-hydroxyquinazoline (9) in dimethylacetamide gave the corresponding diethyl ester 11, which was hydrolyzed to the target compound 3. the known antileukemic agent 2 was also synthesized for comparative studies by employing a modified procedure, which resulted in a better yield of this product. both compounds 2 and 3 were evaluated for their antifolate activities by using two folate-requiring microorganisms, streptococcus faecium and lactobacillus casei. they were further evaluated as inhibitors of thymidylate synthase and dihydrofolate reductase derived from the above organisms, as well as for their antitumor activity by using selected tumor cells in culture. compound 2 was found to be as equally potent as methotrexate (mtx) against s. faecium, and it was an excellent inhibitor of l. casei thymidylate synthase. the cyanomethyl analogue 3 was less active than 2 in all the test systems, except the inhibition of dihydrofolate reductase.",
        "authors": "nair mg, salter dc, kisliuk rl, gaumont y, north g, sirotnak fm.",
        "chembl_release": "chembl_release:CHEMBL_1|creation_date:2009-09-03",
        "contact": null,
        "doc_type": "PUBLICATION",
        "document_chembl_id": "CHEMBL1122470",
        "doi": "10.1021/jm00358a030",
        "doi_chembl": null,
        "first_page": 605,
        "issue": 4.0,
        "journal": "j med chem",
        "journal_full_title": "journal of medicinal chemistry.",
        "last_page": 607,
        "patent_id": null,
        "pubmed_id": 6403710,
        "score": null,
        "src_id": 1.0,
        "title": "folate analogues. 21. synthesis and antifolate and antitumor activities of n10-(cyanomethyl)-5,8-dideazafolic acid.",
        "volume": 26,
        "year": 1983.0,
        "hash_row": "04872ac6c6ed3b7a6a06524f243762f43fb126049a562ed8a04300445e431c67",
        "hash_business_key": "9184f7580181dd30def7e4eedbd148ebd373b56c346876648fa44873c87b493a",
        "index": 410,
        "database_version": "ChEMBL_36",
        "extracted_at": "2025-12-06T13:34:13.027556+00:00"
    },
    {
        "abstract": "a consideration of the detailed structural information available from x-ray crystallographic and nmr studies on complexes of dihydrofolate reductase with inhibitors has led to the design of trimethoprim analogues with improved binding properties. computer graphic techniques have been used to predict which substituent groups were required at the 3'-o position of brodimoprim (2,4-diamino-5-(3,5-dimethoxy-4-bromobenzyl)pyrimidine) to make additional interactions with the enzyme. nmr spectroscopy provided a convenient method of assessing if the analogues were binding in the predicted manner. on the basis of this approach, the c4,c6-dicarboxylic acid analogue ix was designed to interact with arg-57 and his-28 in the enzyme, and this analogue was found to bind 3 orders of magnitude more tightly than the parent brodimoprim.",
        "authors": "birdsall b, feeney j, pascual c, roberts gc, kompis i, then rl, müller k, kroehn a.",
        "chembl_release": "chembl_release:CHEMBL_1|creation_date:2009-09-03",
        "contact": null,
        "doc_type": "PUBLICATION",
        "document_chembl_id": "CHEMBL1122542",
        "doi": "10.1021/jm00378a025",
        "doi_chembl": null,
        "first_page": 1672,
        "issue": 12.0,
        "journal": "j med chem",
        "journal_full_title": "journal of medicinal chemistry.",
        "last_page": 1676,
        "patent_id": null,
        "pubmed_id": 6438320,
        "score": null,
        "src_id": 1.0,
        "title": "a 1h nmr study of the interactions and conformations of rationally designed brodimoprim analogues in complexes with lactobacillus casei dihydrofolate reductase.",
        "volume": 27,
        "year": 1984.0,
        "hash_row": "36b0b6bdea4feab356e5113d5b8b0418a18d7cf0595ce79b0fd43b94067ec243",
        "hash_business_key": "7986c61c93c75af20f81b9b0578a4904188b5ad014de51867c74b19ab5d27369",
        "index": 441,
        "database_version": "ChEMBL_36",
        "extracted_at": "2025-12-06T13:34:13.027556+00:00"
    },
    {
        "abstract": "3,4,5-triethylacetophenone was synthesized in 60% yield by a friedel-crafts reaction from 4-ethylacetophenone and converted to 2,4-diamino-5-(3,4,5-triethylbenzyl)pyrimidine (2), a trimethoprim (1) isostere, by standard techniques. this compound is more lipophilic than 1 by three log units (log p, octanol/water). compound 2 was approximately equipotent with 1 in inhibiting escherichia coli dihydrofolate reductase (dhfr), 2-fold more potent against p. berghei and n. gonorrhoeae dhfr, and 10 and 25 times better an inhibitor of rat and chicken liver dhfr, respectively. although the 3,4-dimethoxy analogue 19 was 10-fold less inhibitory to e. coli dhfr than 1, it was 3-4 times more potent on the vertebrate isozymes, whereas the diethyl congener 10 followed 19 in its e. coli dhfr binding but was less active on rat and chicken dhfr. therefore, a significant portion of the selectivity of 1 for bacterial, as opposed to vertebrate, dhfr, involves the methoxy functions. an analysis of the x-ray data on 1 and 2 complexed with chicken dhfr, coupled with kinetic data, led to the conclusion that the difference in binding energies of the methoxy and ethyl compounds probably involve desolvation factors, as well as direct energies of interaction with protein atoms. thus, one cannot invoke lipophilicity or shape alone in explaining the relationship in properties of 1 and 2.",
        "authors": "roth b, aig e.",
        "chembl_release": "chembl_release:CHEMBL_1|creation_date:2009-09-03",
        "contact": null,
        "doc_type": "PUBLICATION",
        "document_chembl_id": "CHEMBL1123638",
        "doi": "10.1021/jm00394a012",
        "doi_chembl": null,
        "first_page": 1998,
        "issue": 11.0,
        "journal": "j med chem",
        "journal_full_title": "journal of medicinal chemistry.",
        "last_page": 2004,
        "patent_id": null,
        "pubmed_id": 3312605,
        "score": null,
        "src_id": 1.0,
        "title": "2,4-diamino-5-benzylpyrimidines as antibacterial agents. 8. the 3,4,5-triethyl isostere of trimethoprim. a study of specificity.",
        "volume": 30,
        "year": 1987.0,
        "hash_row": "e26d8208d399601fdb75641f412900dd70b04476655c21643221d28da8f15943",
        "hash_business_key": "005b6049b5a30a85b113f5b5838aafa1a41aa1b136e011d86d057b2f94e884b8",
        "index": 171,
        "database_version": "ChEMBL_36",
        "extracted_at": "2025-12-06T13:34:13.027556+00:00"
    },
    {
        "abstract": "2-phenylpyrroles were synthesized as conformationally restricted analogues of the substituted benzamide sultopride and the butyrophenones haloperidol and fluanisone. dopamine antagonistic activity is maintained if the 2-phenylpyrrole side chain is linked to the pharmacophoric n-ethylpyrrolidine moiety of sultopride or to the 4-substituted piperazine moiety of fluanisone but is lost if the 2-phenylpyrrole is combined with the 4-substituted piperidine moiety of haloperidol. the 2-phenylpyrrole analogue 1 of sultopride is in vitro 0.25 and in vivo 3 times as potent as the parent compound. its binding to the dopamine d-2 receptors is, in analogy to the substituted benzamides, strongly sodium-dependent. the 2-(4-fluorophenyl)pyrrole analogue 5 of fluanisone is superior in vitro as well as in vivo to the corresponding benzamide 7 and the butyrophenone fluanisone. the increase in activity is not only due to a higher affinity for the d-2 receptors but also to an enhanced oral absorption (ratio po/ip = 4.5 vs 40 for the benzamide and 60 for fluanisone). compound 5 is further characterized by a high selectivity for the d-2 receptors, in contrast to the benzamide and butyrophenone analogues (ratio d-2/alpha 1 = 60, 2.0, and 0.3, respectively). the binding to the d-2 receptors has little dependence on sodium. the 2-phenylpyrrole 5 shares with the benzamide 7 a low potential to induce catalepsy, which is in contrast to haloperidol. so, 5-(4-fluorophenyl)-2-[[4-(2-methoxyphenyl)-1-piperazinyl]methyl]pyrrole (5) is the prototype of a new class of sodium-independent dopamine d-2 antagonists, which may be particularly useful as potential antipsychotics with a low propensity to induce acute extrapyramidal side effects.",
        "authors": "van wijngaarden i, kruse cg, van hes r, van der heyden ja, tulp mt.",
        "chembl_release": "chembl_release:CHEMBL_1|creation_date:2009-09-03",
        "contact": null,
        "doc_type": "PUBLICATION",
        "document_chembl_id": "CHEMBL1123646",
        "doi": "10.1021/jm00394a028",
        "doi_chembl": null,
        "first_page": 2099,
        "issue": 11.0,
        "journal": "j med chem",
        "journal_full_title": "journal of medicinal chemistry.",
        "last_page": 2104,
        "patent_id": null,
        "pubmed_id": 2889830,
        "score": null,
        "src_id": 1.0,
        "title": "2-phenylpyrroles as conformationally restricted benzamide analogues. a new class of potential antipsychotics. 1.",
        "volume": 30,
        "year": 1987.0,
        "hash_row": "f048574a6b9544a64854a4dc9297953c930a1cdc76b52a161378559a7764126a",
        "hash_business_key": "7f0b6b7553fa040c439c2ad81242c2f434041dea244aa80d3e87df109a548b42",
        "index": 150,
        "database_version": "ChEMBL_36",
        "extracted_at": "2025-12-06T13:34:13.027556+00:00"
    }
]
""")
