#!/bin/bash
# Manual DNS setup for WSL - step by step

echo "========================================"
echo "WSL DNS Setup for Codex Device Auth"
echo "========================================"
echo ""

echo "Step 1: Configure /etc/wsl.conf..."
echo "Please run the following command manually:"
echo ""
echo "sudo bash -c 'cat > /etc/wsl.conf << EOF"
echo "[boot]"
echo "systemd=true"
echo ""
echo "[user]"
echo "default=fedor"
echo ""
echo "[network]"
echo "generateResolvConf = false"
echo "EOF'"
echo ""
echo "Press Enter when done..."
read

echo ""
echo "Step 2: Configure /etc/resolv.conf..."
echo "Please run the following command manually:"
echo ""
echo "sudo bash -c 'cat > /etc/resolv.conf << EOF"
echo "nameserver 8.8.8.8"
echo "nameserver 8.8.4.4"
echo "EOF'"
echo ""
echo "Press Enter when done..."
read

echo ""
echo "Step 3: Protect /etc/resolv.conf..."
echo "Please run the following command manually:"
echo ""
echo "sudo chattr +i /etc/resolv.conf"
echo ""
echo "Press Enter when done..."
read

echo ""
echo "Step 4: Test DNS resolution..."
echo "Please run the following command manually:"
echo ""
echo "ping -c 1 auth.openai.com"
echo ""
echo "Press Enter when done..."
read

echo ""
echo "========================================"
echo "DNS Setup Complete"
echo "========================================"
echo ""
echo "Next steps:"
echo "1. Restart WSL from PowerShell: wsl --shutdown"
echo "2. Start WSL again: wsl"
echo "3. Test device-auth: codex login --device-auth"
echo ""
echo "To undo these changes:"
echo "  sudo chattr -i /etc/resolv.conf"
echo "  Remove [network] section from /etc/wsl.conf"
echo "  Restart WSL"