# pyright: reportArgumentType=false
# pyright: reportAttributeAccessIssue=false
# pyright: reportCallIssue=false
# pyright: reportIndexIssue=false
# pyright: reportMissingTypeArgument=false
# pyright: reportGeneralTypeIssues=false
# pyright: reportOptionalMemberAccess=false
# pyright: reportOperatorIssue=false
# pyright: reportAbstractUsage=false
# PD5 test mock/fixture surface — product NewTypes/Ports stay strict (#6997+#6998+#6999+#7000).
"""Guard generated Python data placement in the domain layer."""

from __future__ import annotations

from pathlib import Path

import pytest

pytestmark = pytest.mark.architecture

# Temporary legacy allowlist; no new generated domain modules should be added.
ALLOWED_GENERATED_DOMAIN_MODULES = {
    Path("mapping/generated/publication_type_classification_data.py"),
    Path("mapping/generated/publication_type_classification_payload.py"),
    Path("schemas/generated/registry.py"),
}

GENERATED_MARKERS = (
    "auto-generated",
    "do not edit manually",
    "generated by",
    "asset source:",
)


def test_generated_python_data_is_restricted_in_domain(src_dir: Path) -> None:
    """Generated Python data modules must stay in explicit legacy locations only."""
    domain_dir = src_dir / "bioetl" / "domain"
    if not domain_dir.exists():
        pytest.skip("domain directory not found")

    generated_dir_files: list[Path] = []
    marker_violations: list[Path] = []

    for py_file in sorted(domain_dir.rglob("*.py")):
        rel_path = py_file.relative_to(domain_dir)
        if "generated" in rel_path.parts and py_file.name != "__init__.py":
            generated_dir_files.append(rel_path)

        if rel_path in ALLOWED_GENERATED_DOMAIN_MODULES:
            continue
        content = py_file.read_text(encoding="utf-8").lower()
        if any(marker in content for marker in GENERATED_MARKERS):
            marker_violations.append(rel_path)

    unexpected_generated_modules = sorted(
        set(generated_dir_files) - ALLOWED_GENERATED_DOMAIN_MODULES
    )

    assert not unexpected_generated_modules, (
        "Unexpected generated modules detected under domain/. "
        "Do not add new generated Python data modules in domain layer.\n"
        + "\n".join(f"  - {item}" for item in unexpected_generated_modules)
    )
    assert not marker_violations, (
        "Generated-data markers found outside approved generated modules in domain/.\n"
        + "\n".join(f"  - {item}" for item in marker_violations)
    )
