"""Guard docs/04-reference/api landing pages against false autogen claims (#9690)."""

from __future__ import annotations

import importlib
import re
from pathlib import Path

import pytest

pytestmark = pytest.mark.architecture

ROOT = Path(__file__).resolve().parents[2]
API_ROOT = ROOT / "docs" / "04-reference" / "api"
LAYER_PAGES = (
    API_ROOT / "application.md",
    API_ROOT / "composition.md",
    API_ROOT / "infrastructure.md",
)
_IDENT = re.compile(r"`([A-Za-z_][A-Za-z0-9_]*)`")
_AUTOGEN = re.compile(r"Autogenerated from source code", re.IGNORECASE)


def _package_structure_rows(text: str) -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    in_table = False
    for line in text.splitlines():
        if line.startswith("| Subpackage"):
            in_table = True
            continue
        if in_table and line.startswith("| ---"):
            continue
        if in_table and line.startswith("|"):
            cells = [cell.strip() for cell in line.strip("|").split("|")]
            if len(cells) >= 3:
                rows.append((cells[0].strip("`"), cells[2]))
            continue
        if in_table:
            break
    return rows


def test_domain_symbol_tables_resolve_to_importable_modules() -> None:
    """Published domain tables are part of the facade check, not only three layers."""
    text = (API_ROOT / "domain.md").read_text(encoding="utf-8")
    missing: list[str] = []
    for line in text.splitlines():
        if not line.startswith("|"):
            continue
        cells = [cell.strip() for cell in line.strip("|").split("|")]
        if len(cells) < 2:
            continue
        left = cells[0].strip("`")
        right = cells[1].strip("`")
        if left.startswith("bioetl."):
            module_name = left
            symbol = ""
        elif right.startswith("bioetl."):
            module_name = right
            symbol = left
        else:
            continue
        try:
            module = importlib.import_module(module_name)
        except ImportError as exc:
            missing.append(f"domain.md: cannot import {module_name}: {exc}")
            continue
        if not symbol or symbol == module_name.rsplit(".", maxsplit=1)[-1]:
            continue
        exported = set(getattr(module, "__all__", ())) | set(dir(module))
        if symbol not in exported and not hasattr(module, symbol):
            missing.append(f"domain.md: {module_name} missing public symbol {symbol}")
    assert missing == [], "\n".join(missing)


def test_api_layer_pages_are_curated_not_autogenerated() -> None:
    for path in LAYER_PAGES:
        text = path.read_text(encoding="utf-8")
        assert _AUTOGEN.search(text) is None, f"{path} still claims autogen"
        assert "curated published reference" in text.lower(), path


def test_api_layer_key_public_symbols_exist_on_named_packages() -> None:
    missing: list[str] = []
    for path in LAYER_PAGES:
        for subpackage, symbols_cell in _package_structure_rows(
            path.read_text(encoding="utf-8")
        ):
            if "no active" in symbols_cell.lower():
                continue
            names = _IDENT.findall(symbols_cell)
            if not names:
                missing.append(
                    f"{path.name}: {subpackage} has no backtick-wrapped public symbols"
                )
                continue
            module_name = f"bioetl.{subpackage}"
            try:
                module = importlib.import_module(module_name)
            except ImportError as exc:
                missing.append(f"{path.name}: cannot import {module_name}: {exc}")
                continue
            exported = set(getattr(module, "__all__", ())) | set(dir(module))
            for token in names:
                if token in exported or hasattr(module, token):
                    continue
                missing.append(
                    f"{path.name}: {module_name} missing public symbol {token}"
                )
    assert missing == [], "\n".join(missing)
