schema_version: "1.0.0"
workflow:
  name: chembl_target_protein_classification
  version: "1.0.0"
  defaults:
    run_options:
      run_type: backfill
      dry_run: false
      log_level: INFO
  steps:
    - kind: pipeline
      step_id: run_chembl_target_protein_classification
      pipeline_name: chembl_target_protein_classification
