schema_version: "1.0.0"
workflow:
  name: semanticscholar_publication
  version: "1.0.0"
  defaults:
    run_options:
      run_type: backfill
      dry_run: false
      log_level: INFO
  steps:
    - kind: pipeline
      step_id: run_semanticscholar_publication
      pipeline_name: semanticscholar_publication
