"""Pipeline-level silver schema contracts."""

from __future__ import annotations

import pyarrow as pa
import pytest

from bioetl.composition.factories.pipeline.registry_manifest import PIPELINE_CONFIGS

# fmt: off
PIPELINE_SCHEMA_EXPECTATIONS: dict[str, list[tuple[str, pa.DataType]]] = {
    "chembl_activity": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("_state", pa.string()),
        ("action_type", pa.string()),
        ("action_type_description", pa.string()),
        ("action_type_parent_type", pa.string()),
        ("activity_comment", pa.string()),
        ("activity_id", pa.string()),
        ("activity_properties", pa.string()),
        ("assay_id", pa.string()),
        ("assay_description", pa.string()),
        ("assay_type", pa.string()),
        ("assay_variant_accession", pa.string()),
        ("assay_variant_mutation", pa.string()),
        ("bao_endpoint", pa.string()),
        ("bao_format", pa.string()),
        ("bao_label", pa.string()),
        ("canonical_smiles", pa.string()),
        ("data_validity_comment", pa.string()),
        ("data_validity_description", pa.string()),
        ("publication_id", pa.string()),
        ("journal", pa.string()),
        ("publication_doi", pa.string()),
        ("publication_pmid", pa.string()),
        ("publication_pmc_id", pa.string()),
        ("publication_year", pa.int64()),
        ("ligand_efficiency_bei", pa.float64()),
        ("ligand_efficiency_le", pa.float64()),
        ("ligand_efficiency_lle", pa.float64()),
        ("ligand_efficiency_sei", pa.float64()),
        ("manual_curation_flag", pa.float64()),  # Float for nullable int
        ("molecule_id", pa.string()),
        ("molecule_pref_name", pa.string()),
        ("original_activity_id", pa.float64()),  # Float for nullable int
        ("parent_molecule_id", pa.string()),
        ("pchembl_value", pa.float64()),
        ("potential_duplicate", pa.int64()),
        ("qudt_units", pa.string()),
        ("record_id", pa.int64()),
        ("relation", pa.string()),
        ("src_id", pa.int64()),
        ("standard_flag", pa.int64()),
        ("standard_relation", pa.string()),
        ("standard_text_value", pa.string()),
        ("standard_type", pa.string()),
        ("standard_units", pa.string()),
        ("standard_upper_value", pa.float64()),
        ("standard_value", pa.float64()),
        ("target_id", pa.string()),
        ("target_organism", pa.string()),
        ("target_pref_name", pa.string()),
        ("target_taxonomy_id", pa.float64()),
        ("text_value", pa.string()),
        ("toid", pa.float64()),  # Float for nullable int
        ("type", pa.string()),
        ("units", pa.string()),
        ("uo_units", pa.string()),
        ("upper_value", pa.float64()),
        ("value", pa.float64()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "chembl_assay": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("aidx", pa.string()),
        ("assay_category", pa.string()),
        ("assay_cell_type", pa.string()),
        ("assay_id", pa.string()),
        ("assay_classifications", pa.string()),
        ("assay_group", pa.string()),
        ("assay_organism", pa.string()),
        ("assay_parameters", pa.string()),
        ("assay_pref_name", pa.string()),
        ("assay_strain", pa.string()),
        ("assay_subcellular_fraction", pa.string()),
        ("assay_taxonomy_id", pa.float64()),  # Float for nullable int
        ("assay_test_type", pa.string()),
        ("assay_tissue", pa.string()),
        ("assay_type", pa.string()),
        ("assay_type_description", pa.string()),
        ("bao_format", pa.string()),
        ("bao_label", pa.string()),
        ("cell_id", pa.string()),
        ("confidence_description", pa.string()),
        ("confidence_score", pa.int64()),
        ("description", pa.string()),
        ("publication_id", pa.string()),
        ("relationship_description", pa.string()),
        ("relationship_type", pa.string()),
        ("score", pa.float64()),
        ("src_assay_id", pa.string()),
        ("src_id", pa.int64()),
        ("target_id", pa.string()),
        ("tissue_id", pa.string()),
        ("variant_accession", pa.string()),
        ("variant_isoform", pa.string()),
        ("variant_mutation", pa.string()),
        ("variant_organism", pa.string()),
        ("variant_sequence", pa.string()),
        ("variant_sequence_json", pa.string()),
        ("variant_taxonomy_id", pa.float64()),  # Float for nullable int
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "chembl_assay_parameters": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("assay_id", pa.string()),
        ("assay_param_id", pa.int64()),
        ("comments", pa.string()),
        ("relation", pa.string()),
        ("standard_relation", pa.string()),
        ("standard_text_value", pa.string()),
        ("standard_type", pa.string()),
        ("standard_units", pa.string()),
        ("standard_value", pa.float64()),
        ("text_value", pa.string()),
        ("type", pa.string()),
        ("units", pa.string()),
        ("value", pa.float64()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "chembl_cell_line": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("cell_id", pa.string()),
        ("cell_description", pa.string()),
        ("cell_name", pa.string()),
        ("cell_source_organism", pa.string()),
        ("cell_source_taxonomy_id", pa.int64()),
        ("cell_source_tissue", pa.string()),
        ("cellosaurus_id", pa.string()),
        ("cl_lincs_id", pa.string()),
        ("efo_id", pa.string()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "chembl_compound_record": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("compound_key", pa.string()),
        ("compound_name", pa.string()),
        ("publication_id", pa.string()),
        ("molecule_id", pa.string()),
        ("record_id", pa.int64()),
        ("src_compound_id", pa.string()),
        ("src_id", pa.int64()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "chembl_publication": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_source", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("_lookup_method", pa.string()),
        ("_original_id", pa.string()),
        ("authors", pa.string()),
        ("title", pa.string()),
        ("journal", pa.string()),
        ("publication_year", pa.int64()),
        ("volume", pa.string()),
        ("issue", pa.string()),
        ("page_first", pa.string()),
        ("page_last", pa.string()),
        ("publication_id", pa.string()),
        ("publication_doi", pa.string()),
        ("publication_pmid", pa.string()),
        ("publication_pmc_id", pa.string()),
        ("doi", pa.string()),
        ("pmc_id", pa.string()),  # Not available from ChEMBL (None values)
        ("pmid", pa.string()),
        ("abstract", pa.string()),
        ("affiliation_list", pa.string()),  # Not available from ChEMBL (None values)
        ("author_keys", pa.string()),  # Pipe-delimited Surname_F keys
        ("author_orcids", pa.string()),  # Not available from ChEMBL (None values)
        ("publication_type", pa.string()),
        ("publication_type_unified", pa.string()),
        ("publication_subclass", pa.string()),
        ("publication_class", pa.string()),
        ("publication_date", pa.string()),  # Not available from ChEMBL (None values)
        ("language", pa.string()),  # Not available from ChEMBL (None values)
        ("is_oa", pa.bool_()),  # Not available from ChEMBL (None values)
        ("src_id", pa.int64()),
        ("citations_received", pa.int64()),
        ("citations_made", pa.int64()),
        ("chembl_release", pa.string()),
        ("creation_date", pa.string()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "chembl_publication_similarity": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("avg_tani", pa.float64()),
        ("doc_1", pa.int64()),
        ("doc_2", pa.int64()),
        ("max_tani", pa.float64()),
        ("mol_tani", pa.float64()),
        ("pubmed_id1", pa.string()),
        ("pubmed_id2", pa.string()),
        ("sim_id", pa.int64()),
        ("tid_tani", pa.float64()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "chembl_publication_term": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("publication_id", pa.string()),
        ("mesh_id", pa.string()),
        ("qualifier", pa.string()),
        ("term", pa.string()),
        ("term_type", pa.string()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "chembl_molecule": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("atc_classifications", pa.string()),
        ("availability_type", pa.float64()),  # Float for nullable int
        ("black_box_warning", pa.int64()),
        ("canonical_smiles", pa.string()),
        ("chirality", pa.int64()),
        ("cross_references", pa.string()),
        ("dosed_ingredient", pa.int64()),
        ("first_approval", pa.float64()),  # Float for nullable int
        ("first_in_class", pa.int64()),
        ("helm_notation", pa.string()),
        ("hierarchy_active_chembl_id", pa.string()),
        ("hierarchy_child_chembl_id", pa.string()),
        ("hierarchy_parent_chembl_id", pa.string()),
        ("inchi_key", pa.string()),
        ("inorganic_flag", pa.int64()),
        ("max_phase", pa.int64()),
        ("molecule_id", pa.string()),
        ("molecule_hierarchy", pa.string()),
        ("molecule_properties", pa.string()),
        ("molecule_species", pa.string()),
        ("molecule_structures", pa.string()),
        ("molecule_synonyms", pa.string()),
        ("molecule_type", pa.string()),
        ("natural_product", pa.int64()),
        ("oral", pa.bool_()),
        ("parenteral", pa.bool_()),
        ("polymer_flag", pa.int64()),
        ("pref_name", pa.string()),
        ("prodrug", pa.int64()),
        ("aromatic_ring_count", pa.int64()),
        ("hba_count", pa.int64()),
        ("hbd_count", pa.int64()),
        ("heavy_atom_count", pa.int64()),
        ("logp", pa.float64()),
        ("logp_method", pa.string()),
        ("molecular_formula", pa.string()),
        ("molecular_weight", pa.float64()),
        ("mw_freebase", pa.float64()),
        ("polar_surface_area", pa.float64()),
        ("qed_score", pa.float64()),
        ("ro3_pass", pa.string()),
        ("ro5_violation_count", pa.int64()),
        ("rotatable_bond_count", pa.int64()),
        ("standard_inchi", pa.string()),
        ("structure_type", pa.string()),
        ("therapeutic_flag", pa.bool_()),
        ("topical", pa.bool_()),
        ("usan_stem", pa.string()),
        ("usan_stem_definition", pa.string()),
        ("usan_substem", pa.string()),
        ("usan_year", pa.float64()),  # Float for nullable int
        ("withdrawn_flag", pa.bool_()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "chembl_target": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("component_accessions", pa.string()),
        ("component_descriptions", pa.string()),
        ("component_ids", pa.string()),
        ("component_relationships", pa.string()),
        ("component_types", pa.string()),
        ("cross_references", pa.string()),
        ("description", pa.string()),
        ("downgraded", pa.bool_()),
        ("organism", pa.string()),
        ("organism_class", pa.string()),
        ("pipeline_stages", pa.string()),
        ("pref_name", pa.string()),
        ("primary_component_id", pa.float64()),
        ("species_group_flag", pa.bool_()),
        ("target_component_synonyms", pa.string()),
        ("target_components", pa.string()),
        ("target_id", pa.string()),
        ("target_type", pa.string()),
        ("taxonomy_id", pa.float64()),  # Float for nullable int
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "chembl_target_component": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("accession", pa.string()),
        ("component_id", pa.int64()),
        ("component_type", pa.string()),
        ("description", pa.string()),
        ("organism", pa.string()),
        ("protein_classification_id", pa.int64()),
        ("protein_classification_ids", pa.string()),
        ("protein_classifications", pa.string()),
        ("target_component_synonyms", pa.string()),
        ("target_component_xrefs", pa.string()),
        ("taxonomy_id", pa.int64()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "chembl_protein_class": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("class_level", pa.int64()),
        ("definition", pa.string()),
        ("downgraded", pa.int64()),
        ("parent_id", pa.int64()),
        ("pref_name", pa.string()),
        ("protein_class_desc", pa.string()),
        ("protein_class_id", pa.int64()),
        ("replaced_by", pa.int64()),
        ("short_name", pa.string()),
        ("sort_order", pa.int64()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "chembl_tissue": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("bto_id", pa.string()),
        ("caloha_id", pa.string()),
        ("efo_id", pa.string()),
        ("pref_name", pa.string()),
        ("tissue_id", pa.string()),
        ("uberon_id", pa.string()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "chembl_subcellular_fraction": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("assay_count", pa.int64()),
        ("example_assay_id", pa.string()),
        ("subcellular_fraction", pa.string()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "pubchem_compound": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("canonical_smiles", pa.string()),
        ("molecule_id", pa.string()),
        ("complexity", pa.float64()),
        ("conformer_count_3d", pa.float64()),
        ("conformer_rmsd_3d", pa.float64()),
        ("effective_rotor_count_3d", pa.float64()),
        ("exact_mass", pa.float64()),
        ("feature_acceptor_count_3d", pa.float64()),
        ("feature_anion_count_3d", pa.float64()),
        ("feature_cation_count_3d", pa.float64()),
        ("feature_count_3d", pa.float64()),
        ("feature_donor_count_3d", pa.float64()),
        ("feature_hydrophobe_count_3d", pa.float64()),
        ("feature_ring_count_3d", pa.float64()),
        ("inchi", pa.string()),
        ("inchi_key", pa.string()),
        ("isomeric_smiles", pa.string()),
        ("iupac_name", pa.string()),
        ("molecular_formula", pa.string()),
        ("molecular_weight", pa.float64()),
        ("monoisotopic_mass", pa.float64()),
        ("tpsa", pa.float64()),
        ("x_steric_quadrupole_3d", pa.float64()),
        ("xlogp", pa.float64()),
        ("y_steric_quadrupole_3d", pa.float64()),
        ("z_steric_quadrupole_3d", pa.float64()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "uniprot_protein": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("accession", pa.string()),
        ("acetylation", pa.string()),
        ("active_sites", pa.string()),
        ("activity_regulation", pa.string()),
        ("annotation_score", pa.int64()),
        ("binding_sites", pa.string()),
        ("catalytic_activity", pa.string()),
        ("cellular_component", pa.string()),
        ("chembl_ids", pa.string()),
        ("disease_involvement", pa.string()),
        ("disulfide_bond", pa.string()),
        ("domains", pa.string()),
        ("drugbank_ids", pa.string()),
        ("entry_name", pa.string()),
        ("features_json", pa.string()),
        ("function_comment", pa.string()),
        ("gene_names", pa.list_(pa.string())),
        ("genus", pa.string()),
        ("glycosylation", pa.string()),
        ("go_terms", pa.string()),
        ("interpro_xrefs", pa.string()),
        ("intramembrane", pa.string()),
        ("isoform_ids", pa.string()),
        ("isoform_names", pa.string()),
        ("isoform_synonyms", pa.string()),
        ("lipidation", pa.string()),
        ("modified_residue", pa.string()),
        ("molecular_function", pa.string()),
        ("organism_id", pa.int64()),
        ("pathway", pa.string()),
        ("pdb_xrefs", pa.string()),
        ("pfam_xrefs", pa.string()),
        ("phosphorylation", pa.string()),
        ("phylum", pa.string()),
        ("propeptide", pa.string()),
        ("protein_existence", pa.string()),
        ("protein_name", pa.string()),
        ("reaction_ec_numbers", pa.string()),
        ("reactions", pa.string()),
        ("reactome_xrefs", pa.string()),
        ("reviewed", pa.bool_()),
        ("sequence_length", pa.int64()),
        ("signal_peptide", pa.string()),
        ("similarity_comment", pa.string()),
        ("subcellular_location", pa.string()),
        ("superkingdom", pa.string()),
        ("tissue_specificity", pa.string()),
        ("topology", pa.string()),
        ("transmembrane", pa.string()),
        ("ubiquitination", pa.string()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "uniprot_idmapping": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("all_mappings", pa.string()),
        ("annotation_score", pa.int64()),
        ("gene_primary", pa.string()),
        ("mapping_status", pa.string()),
        ("organism_common", pa.string()),
        ("organism_scientific", pa.string()),
        ("protein_name", pa.string()),
        ("reviewed", pa.bool_()),
        ("sequence_length", pa.int64()),
        ("sequence_mass", pa.int64()),
        ("target_id", pa.string()),
        ("taxonomy_id", pa.int64()),
        ("uniprot_accession", pa.string()),
        ("uniprot_entry_name", pa.string()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "pubmed_publication": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_source", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("_lookup_method", pa.string()),
        ("_original_id", pa.string()),
        ("abstract", pa.string()),
        ("abstract_structured", pa.bool_()),
        ("affiliation_list", pa.string()),
        ("affiliation_structured", pa.string()),
        ("author_count", pa.int64()),
        ("author_keys", pa.string()),
        ("authors", pa.string()),
        ("authors_with_affiliations", pa.string()),
        ("chemical_count", pa.int64()),
        ("chemicals", pa.string()),
        ("citation_subset", pa.string()),
        ("citations_made", pa.int64()),
        ("country", pa.string()),
        ("databanks", pa.string()),
        ("date_completed", pa.string()),
        ("date_revised", pa.string()),
        ("doi", pa.string()),
        ("gene_symbols", pa.string()),
        ("grant_count", pa.int64()),
        ("issn", pa.string()),
        ("issue", pa.string()),
        ("journal", pa.string()),
        ("journal_iso_abbrev", pa.string()),
        ("journal_issn_type", pa.string()),
        ("journal_name_short", pa.string()),
        ("keyword_count", pa.int64()),
        ("language", pa.string()),
        ("medline_pgn", pa.string()),
        ("mesh_heading_count", pa.int64()),
        ("mid", pa.string()),
        ("nlm_unique_id", pa.string()),
        ("page_first", pa.string()),
        ("page_last", pa.string()),
        ("page_range", pa.string()),
        ("pii", pa.string()),
        ("pmc_id", pa.string()),
        ("pmid", pa.string()),
        ("pub_date", pa.string()),
        ("pub_day", pa.int64()),
        ("pub_month", pa.int64()),
        ("publication_class", pa.string()),
        ("publication_date", pa.string()),
        ("publication_status", pa.string()),
        ("publication_subclass", pa.string()),
        ("publication_type", pa.string()),
        ("publication_type_list", pa.string()),
        ("publication_type_unified", pa.string()),
        ("publication_types", pa.list_(pa.string())),
        ("publication_year", pa.int64()),
        ("publisher_id", pa.string()),
        ("subject_keywords", pa.list_(pa.string())),
        ("subject_mesh", pa.list_(pa.string())),
        ("title", pa.string()),
        ("volume", pa.string()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "crossref_publication": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_source", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("_lookup_method", pa.string()),
        ("_original_id", pa.string()),
        ("abstract", pa.string()),
        ("affiliation_list", pa.string()),
        ("alternative_id", pa.string()),
        ("author_details", pa.string()),
        ("author_keys", pa.string()),
        ("author_orcids", pa.string()),
        ("authors", pa.string()),
        ("citations_made", pa.int64()),
        ("citations_received", pa.int64()),
        ("content_domain_crossmark_restriction", pa.bool_()),
        ("content_domain_domains", pa.string()),
        ("doi", pa.string()),
        ("issn", pa.string()),
        ("issn_electronic", pa.string()),
        ("issn_list", pa.string()),
        ("issn_print", pa.string()),
        ("issue", pa.string()),
        ("journal", pa.string()),
        ("journal_name_short", pa.string()),
        ("language", pa.string()),
        ("license_url", pa.string()),
        ("page_first", pa.string()),
        ("page_last", pa.string()),
        ("pmc_id", pa.string()),
        ("pmid", pa.string()),
        ("publication_class", pa.string()),
        ("publication_date", pa.string()),
        ("publication_subclass", pa.string()),
        ("publication_type", pa.string()),
        ("publication_type_unified", pa.string()),
        ("publication_year", pa.int64()),
        ("published", pa.string()),
        ("published_online", pa.string()),
        ("published_print", pa.string()),
        ("publisher", pa.string()),
        ("references", pa.string()),
        ("subject_keywords", pa.list_(pa.string())),
        ("title", pa.string()),
        ("volume", pa.string()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "openalex_publication": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_source", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("_lookup_method", pa.string()),
        ("_original_id", pa.string()),
        ("abstract", pa.string()),
        ("affiliation_list", pa.string()),
        ("author_keys", pa.string()),
        ("author_openalex_ids", pa.string()),
        ("author_orcids", pa.string()),
        ("authors", pa.string()),
        ("citations_made", pa.int64()),
        ("citations_received", pa.int64()),
        ("doi", pa.string()),
        ("fwci", pa.float64()),
        ("grants", pa.string()),
        ("institution_country_codes", pa.list_(pa.string())),
        ("institution_ids", pa.list_(pa.string())),
        ("is_oa", pa.bool_()),
        ("is_retracted", pa.bool_()),
        ("issn", pa.string()),
        ("issue", pa.string()),
        ("journal", pa.string()),
        ("language", pa.string()),
        ("mag_id", pa.string()),
        ("oa_status", pa.string()),
        ("openalex_id", pa.string()),
        ("page_first", pa.string()),
        ("page_last", pa.string()),
        ("pmc_id", pa.string()),
        ("pmid", pa.string()),
        ("primary_topic", pa.string()),
        ("publication_class", pa.string()),
        ("publication_date", pa.string()),
        ("publication_subclass", pa.string()),
        ("publication_type", pa.string()),
        ("publication_type_unified", pa.string()),
        ("publication_year", pa.int64()),
        ("publisher", pa.string()),
        ("ror_ids", pa.string()),
        ("subject_keywords", pa.list_(pa.string())),
        ("subject_mesh", pa.list_(pa.string())),
        ("subject_topics", pa.string()),
        ("title", pa.string()),
        ("volume", pa.string()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
    "semanticscholar_publication": [
        ("entity_id", pa.string()),
        ("content_hash", pa.string()),
        ("_run_id", pa.string()),
        ("_run_type", pa.string()),
        ("_source_batch_id", pa.string()),
        ("_source", pa.string()),
        ("_ingestion_ts", pa.string()),
        ("_index", pa.int64()),
        ("_lookup_method", pa.string()),
        ("_original_id", pa.string()),
        ("abstract", pa.string()),
        ("affiliation_list", pa.string()),
        ("author_h_indices", pa.string()),
        ("author_keys", pa.string()),
        ("author_orcids", pa.string()),
        ("author_s2_ids", pa.string()),
        ("authors", pa.string()),
        ("citation_contexts", pa.string()),
        ("citations_made", pa.int64()),
        ("citations_received", pa.int64()),
        ("corpus_id", pa.int64()),
        ("dblp_id", pa.string()),
        ("doi", pa.string()),
        ("influential_citation_count", pa.int64()),
        ("is_oa", pa.bool_()),
        ("issue", pa.string()),
        ("journal", pa.string()),
        ("oa_status", pa.string()),
        ("open_access_url", pa.string()),
        ("page_first", pa.string()),
        ("page_last", pa.string()),
        ("page_range", pa.string()),
        ("paper_id", pa.string()),
        ("pmc_id", pa.string()),
        ("pmid", pa.string()),
        ("publication_class", pa.string()),
        ("publication_date", pa.string()),
        ("publication_subclass", pa.string()),
        ("publication_type", pa.string()),
        ("publication_type_unified", pa.string()),
        ("publication_types", pa.string()),
        ("publication_year", pa.int64()),
        ("subject_fields", pa.string()),
        ("title", pa.string()),
        ("tldr", pa.string()),
        ("volume", pa.string()),
        ("_dq_error", pa.bool_()),
        ("_dq_warn", pa.bool_()),
    ],
}

PIPELINE_PRIMARY_KEYS: dict[str, str] = {
    "chembl_activity": "activity_id",
    "chembl_assay": "assay_id",
    "chembl_assay_parameters": "assay_param_id",
    "chembl_cell_line": "cell_id",
    "chembl_compound_record": "record_id",
    "chembl_publication": "publication_id",
    "chembl_publication_similarity": "sim_id",
    "chembl_publication_term": "publication_id",
    "chembl_molecule": "molecule_id",
    "chembl_target": "target_id",
    "chembl_target_component": "component_id",
    "chembl_protein_class": "protein_class_id",
    "chembl_tissue": "tissue_id",
    "chembl_subcellular_fraction": "subcellular_fraction",
    "pubchem_compound": "molecule_id",
    "uniprot_protein": "accession",
    "uniprot_idmapping": "target_id",
    "pubmed_publication": "pmid",
    "crossref_publication": "doi",
    "openalex_publication": "openalex_id",
    "semanticscholar_publication": "paper_id",
}
# fmt: on


def _pipeline_schema(pipeline_name: str) -> pa.Schema:
    for config in PIPELINE_CONFIGS:
        if config.pipeline_name == pipeline_name:
            assert config.silver_schema is not None
            return config.silver_schema
    raise KeyError(f"Unknown pipeline: {pipeline_name}")


def _expected_type(
    expected_fields: list[tuple[str, pa.DataType]], field_name: str
) -> pa.DataType:
    for name, dtype in expected_fields:
        if name == field_name:
            return dtype
    raise KeyError(f"Unknown field {field_name}")


def _invalid_value(expected_type: pa.DataType) -> object:
    if expected_type == pa.string():
        return 123
    if expected_type == pa.int64():
        return "not-an-int"
    if expected_type == pa.float64():
        return "not-a-float"
    if expected_type == pa.bool_():
        return "not-a-bool"
    if isinstance(expected_type, pa.ListType):
        return "not-a-list"
    raise AssertionError(f"Unhandled type {expected_type}")


def _valid_value(expected_type: pa.DataType) -> object:
    if expected_type == pa.string():
        return "id"
    if expected_type == pa.int64():
        return 1
    if expected_type == pa.float64():
        return 1.0
    if expected_type == pa.bool_():
        return True
    if isinstance(expected_type, pa.ListType):
        return []
    raise AssertionError(f"Unhandled type {expected_type}")


def _base_record(schema: pa.Schema) -> dict[str, object]:
    record: dict[str, object] = {
        "entity_id": "entity_1",
        "content_hash": "hash_1",
        "_run_id": "run_1",
        "_run_type": "incremental",
        "_source_batch_id": "batch_1",
        "_ingestion_ts": "2024-01-01T00:00:00Z",
    }
    if "_source" in schema.names:
        record["_source"] = "source"
    if "_index" in schema.names:
        record["_index"] = 0
    if "_lookup_method" in schema.names:
        record["_lookup_method"] = "direct"
    if "_original_id" in schema.names:
        record["_original_id"] = "orig"
    return record


@pytest.mark.unit
class TestPipelineSchemaCoverage:
    def test_all_pipeline_schemas_listed(self) -> None:
        pipeline_names = {
            config.pipeline_name
            for config in PIPELINE_CONFIGS
            if config.silver_schema is not None
        }
        assert pipeline_names == set(PIPELINE_SCHEMA_EXPECTATIONS.keys())


@pytest.mark.unit
class TestPipelineSchemaFields:
    @pytest.mark.parametrize(
        "pipeline_name,expected_fields",
        PIPELINE_SCHEMA_EXPECTATIONS.items(),
        ids=PIPELINE_SCHEMA_EXPECTATIONS.keys(),
    )
    def test_schema_field_names_and_types(
        self,
        pipeline_name: str,
        expected_fields: list[tuple[str, pa.DataType]],
    ) -> None:
        schema = _pipeline_schema(pipeline_name)
        expected_names = [name for name, _ in expected_fields]
        assert schema.names == expected_names
        for field_name, expected_type in expected_fields:
            assert schema.field(field_name).type == expected_type


@pytest.mark.unit
class TestPipelineSchemaValidation:
    @pytest.mark.parametrize(
        "pipeline_name,expected_fields",
        PIPELINE_SCHEMA_EXPECTATIONS.items(),
        ids=PIPELINE_SCHEMA_EXPECTATIONS.keys(),
    )
    def test_minimal_record_valid(
        self,
        pipeline_name: str,
        expected_fields: list[tuple[str, pa.DataType]],
    ) -> None:
        schema = _pipeline_schema(pipeline_name)
        primary_key = PIPELINE_PRIMARY_KEYS[pipeline_name]
        record = _base_record(schema)
        record[primary_key] = _valid_value(_expected_type(expected_fields, primary_key))
        table = pa.Table.from_pylist([record], schema=schema)
        assert table.num_rows == 1

    @pytest.mark.parametrize(
        "pipeline_name,expected_fields",
        PIPELINE_SCHEMA_EXPECTATIONS.items(),
        ids=PIPELINE_SCHEMA_EXPECTATIONS.keys(),
    )
    def test_invalid_primary_key_type_rejected(
        self,
        pipeline_name: str,
        expected_fields: list[tuple[str, pa.DataType]],
    ) -> None:
        schema = _pipeline_schema(pipeline_name)
        primary_key = PIPELINE_PRIMARY_KEYS[pipeline_name]
        record = _base_record(schema)
        record[primary_key] = _invalid_value(
            _expected_type(expected_fields, primary_key)
        )
        with pytest.raises((pa.ArrowInvalid, pa.ArrowTypeError)):
            pa.Table.from_pylist([record], schema=schema)
