"""Compact raw specs for publication structured-field governance."""

from __future__ import annotations

CROSSREF_PUBLICATION = "crossref.publication"
OPENALEX_PUBLICATION = "openalex.publication"
PUBMED_PUBLICATION = "pubmed.publication"
SEMANTICSCHOLAR_PUBLICATION = "semanticscholar.publication"
ORDERED_SEQUENCE = "ordered_sequence"
UNORDERED_SET = "unordered_set"
ORCID = "orcid"
PUBLICATION_TYPE = "publication_type"

PUBLICATION_STRUCTURED_FIELD_POLICY_SPECS: tuple[
    tuple[str, str, str, str | None, str | None], ...
] = (
    (CROSSREF_PUBLICATION, "affiliation_list", UNORDERED_SET, None, None),
    (CROSSREF_PUBLICATION, "alternative_id", UNORDERED_SET, None, None),
    (CROSSREF_PUBLICATION, "author_details", ORDERED_SEQUENCE, None, None),
    (CROSSREF_PUBLICATION, "author_orcids", UNORDERED_SET, ORCID, None),
    (CROSSREF_PUBLICATION, "issn_list", UNORDERED_SET, "issn", None),
    (CROSSREF_PUBLICATION, "authors", ORDERED_SEQUENCE, None, None),
    (CROSSREF_PUBLICATION, "content_domain_domains", UNORDERED_SET, None, None),
    (CROSSREF_PUBLICATION, "references", ORDERED_SEQUENCE, None, None),
    (CROSSREF_PUBLICATION, "subject_keywords", UNORDERED_SET, None, None),
    (OPENALEX_PUBLICATION, "affiliation_list", UNORDERED_SET, None, None),
    (
        OPENALEX_PUBLICATION,
        "author_openalex_ids",
        UNORDERED_SET,
        "openalex_author",
        None,
    ),
    (OPENALEX_PUBLICATION, "author_orcids", UNORDERED_SET, ORCID, None),
    (OPENALEX_PUBLICATION, "authors", ORDERED_SEQUENCE, None, None),
    (OPENALEX_PUBLICATION, "grants", UNORDERED_SET, None, None),
    (OPENALEX_PUBLICATION, "grants_raw_json", ORDERED_SEQUENCE, None, None),
    (OPENALEX_PUBLICATION, "grants_canonical_json", UNORDERED_SET, None, None),
    (OPENALEX_PUBLICATION, "institution_country_codes", UNORDERED_SET, None, None),
    (
        OPENALEX_PUBLICATION,
        "institution_ids",
        UNORDERED_SET,
        "openalex_institution",
        None,
    ),
    (OPENALEX_PUBLICATION, "issn_list", UNORDERED_SET, "issn", None),
    (OPENALEX_PUBLICATION, "ror_ids", UNORDERED_SET, "ror", None),
    (
        OPENALEX_PUBLICATION,
        "primary_topic",
        ORDERED_SEQUENCE,
        "openalex_topic",
        None,
    ),
    (OPENALEX_PUBLICATION, "primary_topic_raw_json", ORDERED_SEQUENCE, None, None),
    (
        OPENALEX_PUBLICATION,
        "primary_topic_canonical_json",
        ORDERED_SEQUENCE,
        "openalex_topic",
        None,
    ),
    (OPENALEX_PUBLICATION, "subject_keywords", UNORDERED_SET, None, None),
    (OPENALEX_PUBLICATION, "subject_mesh", UNORDERED_SET, None, None),
    (OPENALEX_PUBLICATION, "subject_topics", UNORDERED_SET, "openalex_topic", None),
    (PUBMED_PUBLICATION, "affiliation_list", UNORDERED_SET, None, None),
    (PUBMED_PUBLICATION, "affiliation_structured", UNORDERED_SET, None, None),
    (
        PUBMED_PUBLICATION,
        "affiliation_structured_raw_json",
        ORDERED_SEQUENCE,
        None,
        None,
    ),
    (
        PUBMED_PUBLICATION,
        "affiliation_structured_canonical_json",
        UNORDERED_SET,
        None,
        None,
    ),
    (PUBMED_PUBLICATION, "author_orcids", UNORDERED_SET, ORCID, None),
    (PUBMED_PUBLICATION, "authors", ORDERED_SEQUENCE, None, None),
    (PUBMED_PUBLICATION, "authors_with_affiliations", ORDERED_SEQUENCE, None, None),
    (
        PUBMED_PUBLICATION,
        "authors_with_affiliations_raw_json",
        ORDERED_SEQUENCE,
        None,
        None,
    ),
    (
        PUBMED_PUBLICATION,
        "authors_with_affiliations_canonical_json",
        ORDERED_SEQUENCE,
        None,
        None,
    ),
    (PUBMED_PUBLICATION, "chemicals", UNORDERED_SET, None, None),
    (PUBMED_PUBLICATION, "databanks", UNORDERED_SET, None, None),
    (PUBMED_PUBLICATION, "gene_symbols", UNORDERED_SET, None, None),
    (PUBMED_PUBLICATION, "issn_list", UNORDERED_SET, "issn", None),
    (
        PUBMED_PUBLICATION,
        "publication_types",
        UNORDERED_SET,
        None,
        PUBLICATION_TYPE,
    ),
    (PUBMED_PUBLICATION, "subject_keywords", UNORDERED_SET, None, None),
    (PUBMED_PUBLICATION, "subject_mesh", UNORDERED_SET, None, None),
    (SEMANTICSCHOLAR_PUBLICATION, "affiliation_list", UNORDERED_SET, None, None),
    (
        SEMANTICSCHOLAR_PUBLICATION,
        "author_h_indices",
        ORDERED_SEQUENCE,
        None,
        None,
    ),
    (
        SEMANTICSCHOLAR_PUBLICATION,
        "author_h_indices_raw_json",
        ORDERED_SEQUENCE,
        None,
        None,
    ),
    (
        SEMANTICSCHOLAR_PUBLICATION,
        "author_h_indices_canonical_json",
        ORDERED_SEQUENCE,
        None,
        None,
    ),
    (SEMANTICSCHOLAR_PUBLICATION, "author_orcids", UNORDERED_SET, ORCID, None),
    (
        SEMANTICSCHOLAR_PUBLICATION,
        "author_s2_ids",
        UNORDERED_SET,
        "semantic_scholar_author",
        None,
    ),
    (SEMANTICSCHOLAR_PUBLICATION, "authors", ORDERED_SEQUENCE, None, None),
    (SEMANTICSCHOLAR_PUBLICATION, "issn_list", UNORDERED_SET, "issn", None),
    (
        SEMANTICSCHOLAR_PUBLICATION,
        "citation_contexts",
        ORDERED_SEQUENCE,
        None,
        None,
    ),
    (
        SEMANTICSCHOLAR_PUBLICATION,
        "citation_contexts_raw_json",
        ORDERED_SEQUENCE,
        None,
        None,
    ),
    (
        SEMANTICSCHOLAR_PUBLICATION,
        "citation_contexts_canonical_json",
        ORDERED_SEQUENCE,
        None,
        None,
    ),
    (
        SEMANTICSCHOLAR_PUBLICATION,
        "publication_types",
        UNORDERED_SET,
        None,
        PUBLICATION_TYPE,
    ),
    (
        SEMANTICSCHOLAR_PUBLICATION,
        "publication_types_raw_json",
        ORDERED_SEQUENCE,
        None,
        None,
    ),
    (
        SEMANTICSCHOLAR_PUBLICATION,
        "publication_types_canonical_json",
        UNORDERED_SET,
        None,
        PUBLICATION_TYPE,
    ),
    (SEMANTICSCHOLAR_PUBLICATION, "subject_fields", UNORDERED_SET, None, None),
    (
        SEMANTICSCHOLAR_PUBLICATION,
        "subject_fields_raw_json",
        ORDERED_SEQUENCE,
        None,
        None,
    ),
    (
        SEMANTICSCHOLAR_PUBLICATION,
        "subject_fields_canonical_json",
        UNORDERED_SET,
        None,
        None,
    ),
)
