#!/usr/bin/env python3
"""Generate/check the documentation cleanup inventory.

The inventory is intentionally deterministic: it is derived from tracked files,
bounded local documentation scans, normalized duplicate groups for scanned
documents, and the generated artifact routing registry. It does not use
wall-clock time.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import urllib.parse
from collections import Counter, defaultdict
from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover - PyYAML is present in project envs.
    yaml = None


PROJECT_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_JSON = (
    PROJECT_ROOT / "docs/reports/generated/documentation-cleanup-inventory.json"
)
DEFAULT_MD = PROJECT_ROOT / "docs/reports/generated/documentation-cleanup-inventory.md"
ROUTING_CONFIG = PROJECT_ROOT / "configs/quality/generated_artifact_routing.yaml"
STRUCTURE_CATALOG = PROJECT_ROOT / "configs/quality/repo_structure_catalog.yaml"

DOC_ROOTS = (
    ".github/ISSUES/",
    "docs/",
    "reports/",
    "plans/",
    "reviews/",
    "audits/",
    "analyses/",
    "research/",
    "architecture/",
    "diagrams/",
)
ROOT_DOCS = {
    "AGENTS.md",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "GEMINI.md",
    "README.md",
    "best_practices.md",
    "mkdocs.yml",
}
DOC_EXTENSIONS = {
    ".md",
    ".rst",
    ".txt",
    ".mmd",
    ".mermaid",
    ".csv",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
}
TEXT_EXTENSIONS = {
    ".md",
    ".rst",
    ".txt",
    ".mmd",
    ".mermaid",
    ".csv",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
}
TEXT_SCAN_EXTENSIONS = {
    ".md",
    ".rst",
    ".txt",
    ".mmd",
    ".mermaid",
}
MAX_TEXT_SCAN_BYTES = 256_000
CANONICAL_FILES = {
    "README.md",
    "CHANGELOG.md",
    "mkdocs.yml",
    "AGENTS.md",
    "docs/00-project/NORMATIVE_SOURCES.md",
    "docs/00-project/RULES.md",
    "docs/01-requirements/REQUIREMENTS.md",
    "docs/00-project/glossary.md",
    "docs/00-project/00-map.md",
    "docs/00-project/architecture-index.md",
}
ROOT_DOC_KINDS = {
    "AGENTS.md": "ai_runtime_entrypoint",
    "CHANGELOG.md": "release_history",
    "CONTRIBUTING.md": "contributor_entrypoint",
    "GEMINI.md": "ai_runtime_mirror",
    "README.md": "project_entrypoint",
    "best_practices.md": "vendor_review_guidance",
    "mkdocs.yml": "documentation_tool_config",
}
GENERATED_PATH_MARKERS = (
    "/generated/",
    "/bundles/",
    "/svg/",
    "/png/",
    "/descriptions/",
)
WORKING_PATH_PREFIXES = (
    "docs/plans/",
    "docs/reports/",
    "reports/",
    "plans/",
    "reviews/",
    "audits/",
    "analyses/",
    "research/",
)
WORKING_NAME_RE = re.compile(
    r"(^|/)(plan|audit|review|investigation|roadmap|migration|closeout|issue-pack|report)[-_]",
    re.IGNORECASE,
)
GENERATED_MARKER_RE = re.compile(
    r"auto-generated|do not edit|do not modify|machine-generated|"
    r"this file is generated|generated by|generated from",
    re.IGNORECASE,
)
LINK_RE = re.compile(r"(?<!!)\[([^\]]+)\]\(([^)]+)\)")
SKIP_TEXT_SCAN_PATHS = {
    "reports/configs_merged.md",
    "reports/documentation_merged.md",
    "reports/merged_output.txt",
    "reports/project_structure.md",
}
SKIP_TEXT_SCAN_SUFFIXES = {".csv", ".json"}
MAX_LOCAL_DOC_REPORT_FILES = 25_000
QUARANTINED_PATH_MARKERS = (
    "/.quarantined",
    ".quarantined",
)


@dataclass(frozen=True)
class Route:
    route_id: str
    generator: str
    output_kind: str
    commit_policy: str
    outputs: tuple[str, ...]
    notes: str


def _repo_relative(path: Path) -> str:
    return path.relative_to(PROJECT_ROOT).as_posix()


def _run_git_ls_files() -> list[str]:
    result = subprocess.run(
        ["git", "ls-files"],
        cwd=PROJECT_ROOT,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    return result.stdout.splitlines()


def _is_quarantined_path(path: str) -> bool:
    return path.startswith(".quarantined") or any(
        marker in path for marker in QUARANTINED_PATH_MARKERS
    )


def _scan_error(path: str, error: str) -> dict[str, str]:
    return {"path": path, "error": error}


def _safe_iter_local_doc_tree(root_relative: str) -> tuple[list[str], list[dict[str, str]]]:
    """Scan an explicit local docs root without shelling out to broad traversal."""
    root = PROJECT_ROOT / root_relative
    if not root.exists():
        return [], []

    paths: list[str] = []
    errors: list[dict[str, str]] = []
    stack = [root]

    while stack:
        current = stack.pop()
        relative_current = _repo_relative(current)
        if _is_quarantined_path(relative_current):
            errors.append(_scan_error(relative_current, "QuarantinedPath"))
            continue

        try:
            with os.scandir(current) as iterator:
                entries = sorted(iterator, key=lambda entry: entry.name)
        except OSError as error:
            errors.append(_scan_error(relative_current, error.__class__.__name__))
            continue

        for entry in entries:
            entry_path = Path(entry.path)
            relative = _repo_relative(entry_path)
            try:
                if entry.is_dir(follow_symlinks=False):
                    if _is_quarantined_path(relative):
                        errors.append(_scan_error(relative, "QuarantinedPath"))
                    else:
                        stack.append(entry_path)
                    continue
                if entry.is_file(follow_symlinks=False) and _is_doc_like(relative):
                    paths.append(relative)
                    if len(paths) > MAX_LOCAL_DOC_REPORT_FILES:
                        errors.append(
                            _scan_error(root_relative, "LocalScanFileLimitExceeded")
                        )
                        return sorted(set(paths)), errors
            except OSError as error:
                errors.append(_scan_error(relative, error.__class__.__name__))
    return sorted(set(paths)), errors


def _safe_iter_local_docs_reports() -> tuple[list[str], list[dict[str, str]]]:
    return _safe_iter_local_doc_tree("docs/reports")


def _is_doc_like(path: str) -> bool:
    suffix = Path(path).suffix.lower()
    return path in ROOT_DOCS or (
        path.startswith(DOC_ROOTS) and suffix in DOC_EXTENSIONS
    )


def _read_text(path: str) -> str:
    if path in SKIP_TEXT_SCAN_PATHS:
        return ""
    full = PROJECT_ROOT / path
    try:
        with full.open("rb") as handle:
            data = handle.read(MAX_TEXT_SCAN_BYTES + 1)
    except OSError:
        return ""
    if len(data) > MAX_TEXT_SCAN_BYTES:
        return ""
    return data.decode("utf-8", errors="ignore")


def _should_scan_text(path: str) -> bool:
    suffix = Path(path).suffix.lower()
    if suffix not in TEXT_SCAN_EXTENSIONS:
        return False
    if path in SKIP_TEXT_SCAN_PATHS:
        return False
    if path.startswith(".github/ISSUES/"):
        return False
    if path.startswith("reports/") and path != "reports/README.md":
        return False
    if path.startswith("docs/reports/") and path not in {
        "docs/reports/README.md",
        "docs/reports/index.md",
    }:
        return False
    if path.startswith("docs/00-project/ai/skills/_references/"):
        return False
    if path.startswith("docs/02-architecture/diagrams/") and path not in {
        "docs/02-architecture/diagrams/README.md",
    }:
        return False
    if suffix in SKIP_TEXT_SCAN_SUFFIXES:
        return False
    return True


def _extract_owner(text: str) -> str | None:
    for line in text[:1500].splitlines():
        if line.startswith("Owner:"):
            return line.split(":", 1)[1].strip() or None
        if line.startswith("owner:"):
            return line.split(":", 1)[1].strip() or None
    return None


def _extract_declared_status(text: str) -> str | None:
    for line in text[:1500].splitlines():
        stripped = line.strip()
        if stripped.startswith("Status:"):
            return stripped.split(":", 1)[1].strip() or None
        if stripped.startswith("status:"):
            return stripped.split(":", 1)[1].strip() or None
        if stripped.startswith("*Status:"):
            return stripped.strip("*").split(":", 1)[1].strip() or None
    return None


def _extract_declared_class(text: str) -> str | None:
    for line in text[:1500].splitlines():
        stripped = line.strip()
        if stripped.startswith("Class:"):
            return stripped.split(":", 1)[1].strip() or None
        if stripped.startswith("class:"):
            return stripped.split(":", 1)[1].strip() or None
    return None


def _surface_family(path: str, status: str) -> str:
    if status == "Canonical":
        return "canonical"
    if status == "Archived" or path.startswith("docs/99-archive/"):
        return "archive"
    if status == "Generated":
        return "generated"
    if status == "Working":
        return "working"
    if path.startswith("docs/00-project/ai/skills/_references/"):
        return "mirror"
    if status in {"Duplicate", "Deprecated"}:
        return "duplicate"
    if status == "Unknown":
        return "unknown"
    return "active"


def _load_routes() -> list[Route]:
    if yaml is None or not ROUTING_CONFIG.exists():
        return []
    raw = yaml.safe_load(ROUTING_CONFIG.read_text(encoding="utf-8")) or {}
    routes: list[Route] = []
    for item in raw.get("routes", []):
        routes.append(
            Route(
                route_id=str(item.get("id", "")),
                generator=str(item.get("generator", "")),
                output_kind=str(item.get("output_kind", "")),
                commit_policy=str(item.get("commit_policy", "")),
                outputs=tuple(str(output) for output in item.get("outputs", [])),
                notes=str(item.get("notes", "")),
            )
        )
    return routes


def _matches_output(path: str, output: str) -> bool:
    if output.endswith("/"):
        return path.startswith(output)
    if "*" in output:
        pattern = "^" + re.escape(output).replace(r"\*", ".*") + "$"
        return re.match(pattern, path) is not None
    return path == output


def _route_for(path: str, routes: list[Route]) -> Route | None:
    for route in routes:
        if any(_matches_output(path, output) for output in route.outputs):
            return route
    return None


def _load_structure_catalog() -> dict[str, Any]:
    if yaml is None or not STRUCTURE_CATALOG.exists():
        return {}
    payload = yaml.safe_load(STRUCTURE_CATALOG.read_text(encoding="utf-8")) or {}
    assert isinstance(payload, dict)
    return payload


def _plan_lifecycle_map(catalog: dict[str, Any]) -> dict[str, str]:
    plans = catalog.get("plans", {})
    if not isinstance(plans, dict):
        return {}
    result: dict[str, str] = {}
    for item in plans.get("allowed_files", []):
        if isinstance(item, dict) and isinstance(item.get("path"), str):
            result[item["path"]] = str(item.get("lifecycle", "unknown"))
    return result


def _docs_draft_successor_map(catalog: dict[str, Any]) -> dict[str, str]:
    drafts = catalog.get("docs_drafts", {})
    if not isinstance(drafts, dict):
        return {}
    result: dict[str, str] = {}
    for item in drafts.get("allowed_files", []):
        if isinstance(item, dict) and isinstance(item.get("path"), str):
            result[item["path"]] = str(item.get("canonical_successor", ""))
    return result


def _github_issue_number(path: str) -> int | None:
    if not path.startswith(".github/ISSUES/"):
        return None
    name = Path(path).name
    for match in re.finditer(r"(?<!\d)(\d{4,6})(?!\d)", name):
        value = int(match.group(1))
        if 1900 <= value <= 2099:
            continue
        if value >= 3000:
            return value
    return None


def _github_issue_lifecycle(path: str) -> str | None:
    if not path.startswith(".github/ISSUES/"):
        return None
    name = Path(path).name
    if name in {"README.md", "CREATION_GUIDE.md"}:
        return "guide"
    if name.endswith("INDEX.md"):
        return "index"
    if "ISSUE-PACK" in name:
        return "issue_pack"
    if _github_issue_number(path) is not None:
        return "live_issue_mirror"
    if name.startswith(("PLAN-", "TECH-DEBT-ZERO-BURNDOWN-EPIC")):
        return "active_draft"
    return "active_draft"


def _reports_lifecycle(path: str) -> str | None:
    if path.startswith("docs/reports/generated/"):
        return "docs_reports_generated_or_route_owned"
    if path in {"docs/reports/README.md", "docs/reports/index.md"}:
        return "docs_reports_curated_entrypoint"
    if path.startswith("docs/reports/evidence/"):
        return "docs_reports_retention_sensitive_evidence"
    if path.startswith("docs/reports/"):
        return "docs_reports_curated_or_historical_report"
    if not path.startswith("reports/"):
        return None
    if "/test-runs/" in path or path.startswith("reports/test-telemetry/"):
        return "generated_test_run_evidence"
    if "closeout" in path:
        return "closeout_evidence"
    if any(token in path for token in ("baseline", "inventory", "governance")):
        return "active_quality_baseline"
    return "working_report"


def _skill_reference_lifecycle(path: str) -> str | None:
    if path.startswith("docs/00-project/ai/skills/_references/"):
        return "generated_skill_reference_mirror"
    if path.startswith("docs/00-project/ai/skills/local/") and "/references/" in path:
        return "published_skill_reference_redirect"
    if path.startswith("docs/00-project/ai/skills/global/.system/") and path.endswith(
        "/license.txt"
    ):
        return "generated_skill_license_mirror"
    if path.startswith("docs/00-project/ai/skills/global/") and "/LICENSE" in path:
        return "generated_skill_license_mirror"
    return None


def _tracking_state(path: str, tracked: set[str]) -> str:
    if path in tracked:
        return "tracked"
    if path.startswith("docs/reports/"):
        return "ignored_local"
    return "untracked_local"


def _path_lifecycle(
    path: str,
    plan_lifecycle: dict[str, str],
    docs_draft_successors: dict[str, str],
) -> str | None:
    if path == "docs/plans/README.md":
        return "plans_governance_entrypoint"
    if path == "reports/README.md":
        return "reports_workspace_entrypoint"
    return (
        _github_issue_lifecycle(path)
        or _skill_reference_lifecycle(path)
        or plan_lifecycle.get(path)
        or (
            "docs_draft_with_canonical_successor"
            if path in docs_draft_successors
            else None
        )
        or _reports_lifecycle(path)
    )


def _generated_route_exception(
    *,
    status: str,
    route: Route | None,
    diagram_kind: str | None,
    lifecycle: str | None,
) -> str | None:
    if status != "Generated" or route is not None:
        return None
    if diagram_kind:
        return f"diagram_kind:{diagram_kind}"
    if lifecycle in {
        "generated_skill_reference_mirror",
        "generated_skill_license_mirror",
    }:
        return lifecycle
    return None


def _outgoing_links(text: str) -> list[str]:
    links: list[str] = []
    for match in LINK_RE.finditer(text):
        raw = match.group(2).strip()
        if not raw or raw.startswith(
            ("#", "http://", "https://", "mailto:", "tel:", "app://")
        ):
            continue
        if re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", raw) and not re.match(
            r"^[A-Za-z]:[\\/]", raw
        ):
            continue
        target = raw.split()[0].split("#", 1)[0]
        if not target:
            continue
        links.append(urllib.parse.unquote(target))
    return links


def _project_root_aliases() -> tuple[str, ...]:
    root = PROJECT_ROOT.resolve().as_posix().rstrip("/")
    aliases = {root}

    windows_drive_match = re.match(r"^([A-Za-z]):/(.+)$", root)
    if windows_drive_match:
        drive, rest = windows_drive_match.groups()
        aliases.add(f"/mnt/{drive.lower()}/{rest}")
        aliases.add(f"/mnt/{drive.upper()}/{rest}")

    wsl_mount_match = re.match(r"^/mnt/([A-Za-z])/(.+)$", root)
    if wsl_mount_match:
        drive, rest = wsl_mount_match.groups()
        aliases.add(f"{drive.lower()}:/{rest}")
        aliases.add(f"{drive.upper()}:/{rest}")

    return tuple(sorted(aliases, key=len, reverse=True))


def _repo_relative_absolute_link(target: str) -> str | None:
    normalized = target.replace("\\", "/")
    for root in _project_root_aliases():
        if normalized == root:
            return ""
        if normalized.startswith(f"{root}/"):
            return normalized[len(root) + 1 :]
    return None


def _collapse_posix_path(path: str) -> str | None:
    parts: list[str] = []
    for part in path.replace("\\", "/").split("/"):
        if not part or part == ".":
            continue
        if part == "..":
            if not parts:
                return None
            parts.pop()
            continue
        parts.append(part)
    return "/".join(parts)


def _resolve_link(path: str, target: str) -> str | None:
    line_ref_match = re.match(
        r"(.+\.(?:md|py|yaml|yml|json|csv|toml|txt|mmd|mermaid)):\d+$",
        target,
    )
    if line_ref_match:
        target = line_ref_match.group(1)
    repo_relative_absolute = _repo_relative_absolute_link(target)
    if repo_relative_absolute is not None:
        return repo_relative_absolute

    normalized = target.replace("\\", "/")
    if Path(normalized).is_absolute() or re.match(r"^[A-Za-z]:/", normalized):
        return None

    base = Path(path).parent.as_posix()
    joined = normalized if base in {"", "."} else f"{base}/{normalized}"
    return _collapse_posix_path(joined)


def _duplicate_groups(texts: dict[str, str]) -> dict[str, int]:
    by_hash: dict[str, list[str]] = defaultdict(list)
    for path, text in texts.items():
        if not text:
            continue
        normalized = "\n".join(
            line.rstrip() for line in text.replace("\r\n", "\n").split("\n")
        ).strip()
        if not normalized:
            continue
        by_hash[sha256(normalized.encode("utf-8")).hexdigest()].append(path)
    groups: dict[str, int] = {}
    group_id = 1
    for members in sorted(
        (sorted(paths) for paths in by_hash.values() if len(paths) > 1),
        key=lambda paths: (paths[0], len(paths)),
    ):
        for path in members:
            groups[path] = group_id
        group_id += 1
    return groups


def _diagram_kind(path: str) -> str | None:
    if not path.startswith("docs/02-architecture/diagrams/"):
        return None
    if path.endswith(".mmd"):
        if "/class-diagrams/90-pkg-" in path:
            return "diagram_generated_source"
        if (
            "/architecture/" in path
            or "/class-diagrams/" in path
            or "/foundation/" in path
        ):
            return "diagram_canonical_source"
    if path.endswith(".mermaid") and "/views/" in path:
        return "diagram_decomposed_view"
    if "/svg/" in path or "/png/" in path:
        return "diagram_render_artifact"
    if "/bundles/" in path:
        return "diagram_bundle"
    if "/descriptions/" in path:
        return "diagram_description"
    if "/governance/" in path or path.endswith("/diagrams/README.md"):
        return "diagram_governance"
    if "/manifests/" in path or "/tooling/" in path:
        return "diagram_tooling"
    return "diagram_support"


def _classify(
    path: str,
    text: str,
    duplicate_group: int | None,
    route: Route | None,
    lifecycle: str | None,
) -> tuple[str, str, str]:
    declared = (_extract_declared_status(text) or "").lower()
    declared_class = (_extract_declared_class(text) or "").lower()
    diagram_kind = _diagram_kind(path)
    generated_marker = GENERATED_MARKER_RE.search(text[:2500] or "") is not None

    if path.startswith(".github/ISSUES/"):
        if lifecycle in {"guide", "index"}:
            return "Active", "current", "keep"
        if lifecycle == "live_issue_mirror":
            return "Working", "review-required", "reconcile-with-github-state"
        return "Working", "review-required", "archive-after-github-state-check"
    if path in CANONICAL_FILES or path.startswith("docs/02-architecture/decisions/"):
        return "Canonical", "current", "keep"
    if path in ROOT_DOCS:
        return "Active", "current", "keep"
    if path.startswith("docs/99-archive/"):
        return "Archived", "historical", "keep"
    if lifecycle in {
        "plans_governance_entrypoint",
        "reports_workspace_entrypoint",
        "docs_reports_curated_entrypoint",
        "docs_reports_retention_sensitive_evidence",
        "published_skill_reference_redirect",
        "docs_draft_with_canonical_successor",
    }:
        return "Active", "current", "keep"
    if lifecycle in {
        "generated_skill_reference_mirror",
        "generated_skill_license_mirror",
        "docs_reports_generated_or_route_owned",
        "generated_test_run_evidence",
    }:
        return "Generated", "regenerate", "generate-automatically"
    if lifecycle == "active_backlog":
        return "Active", "current", "keep"
    if lifecycle == "supporting_context":
        return "Working", "review-required", "archive-after-migration"
    if lifecycle == "closeout_evidence":
        return "Working", "retention-sensitive", "keep"
    if lifecycle == "active_quality_baseline":
        return "Working", "current", "keep"
    if lifecycle == "docs_reports_curated_or_historical_report":
        return "Working", "review-required", "archive-after-migration"
    if declared in {"deprecated", "retired"}:
        return "Deprecated", "migration-required", "replace-with-link"
    if "obsolete duplicate" in text[:1000].lower():
        return "Deprecated", "migration-required", "replace-with-link"
    if declared_class == "published-redirect":
        return "Active", "current", "keep"
    if (
        route
        or generated_marker
        or any(marker in path for marker in GENERATED_PATH_MARKERS)
    ):
        return "Generated", "regenerate", "generate-automatically"
    if duplicate_group and not path.startswith(
        ("docs/99-archive/", "reports/quality/")
    ):
        return "Duplicate", "migration-required", "merge"
    if diagram_kind and diagram_kind.startswith("diagram_"):
        if diagram_kind in {
            "diagram_canonical_source",
            "diagram_governance",
            "diagram_tooling",
        }:
            return "Active", "current", "keep"
        return "Generated", "regenerate", "generate-automatically"
    if path.startswith(WORKING_PATH_PREFIXES) or WORKING_NAME_RE.search(path):
        return "Working", "review-required", "archive-after-migration"
    if path.startswith(("architecture/", "diagrams/")):
        return "Working", "review-required", "archive-after-migration"
    if path.startswith("docs/") or path in ROOT_DOCS:
        return "Active", "current", "keep"
    return "Unknown", "review-required", "inventory-review"


def _build_inventory() -> dict[str, Any]:
    tracked_all = set(_run_git_ls_files())
    tracked = [path for path in sorted(tracked_all) if _is_doc_like(path)]
    local_docs_reports, scan_errors = _safe_iter_local_docs_reports()
    source_paths = sorted(set(tracked) | set(local_docs_reports))
    catalog = _load_structure_catalog()
    plan_lifecycle = _plan_lifecycle_map(catalog)
    docs_draft_successors = _docs_draft_successor_map(catalog)
    texts = {
        path: _read_text(path)
        for path in source_paths
        if _should_scan_text(path)
    }
    duplicate_groups = _duplicate_groups(texts)
    routes = _load_routes()
    incoming: Counter[str] = Counter()
    outgoing_counts: Counter[str] = Counter()

    for path, text in texts.items():
        outgoing = _outgoing_links(text)
        outgoing_counts[path] = len(outgoing)
        for target in outgoing:
            resolved = _resolve_link(path, target)
            if resolved:
                incoming[resolved] += 1

    records: list[dict[str, Any]] = []
    status_counts: Counter[str] = Counter()
    action_counts: Counter[str] = Counter()
    section_counts: Counter[str] = Counter()
    surface_counts: Counter[str] = Counter()
    lifecycle_counts: Counter[str] = Counter()
    tracking_state_counts: Counter[str] = Counter()
    github_issue_lifecycle_counts: Counter[str] = Counter()
    duplicate_group_count = len(set(duplicate_groups.values()))
    generated_without_route_count = 0
    generated_without_route_or_exception_count = 0

    for path in source_paths:
        text = texts.get(path, "")
        route = _route_for(path, routes)
        duplicate_group = duplicate_groups.get(path)
        lifecycle = _path_lifecycle(path, plan_lifecycle, docs_draft_successors)
        status, freshness, action = _classify(
            path, text, duplicate_group, route, lifecycle
        )
        diagram_kind = _diagram_kind(path)
        route_exception = _generated_route_exception(
            status=status,
            route=route,
            diagram_kind=diagram_kind,
            lifecycle=lifecycle,
        )
        surface_family = _surface_family(path, status)
        tracking_state = _tracking_state(path, tracked_all)
        issue_number = _github_issue_number(path)
        status_counts[status] += 1
        action_counts[action] += 1
        surface_counts[surface_family] += 1
        tracking_state_counts[tracking_state] += 1
        if lifecycle:
            lifecycle_counts[lifecycle] += 1
        if path.startswith(".github/ISSUES/") and lifecycle:
            github_issue_lifecycle_counts[lifecycle] += 1
        if status == "Generated" and not route:
            generated_without_route_count += 1
            if not route_exception:
                generated_without_route_or_exception_count += 1
        section = (
            path.split("/")[1]
            if path.startswith("docs/") and "/" in path
            else path.split("/")[0]
        )
        section_counts[section] += 1
        records.append(
            {
                "path": path,
                "extension": Path(path).suffix.lower() or "(none)",
                "section": section,
                "tracking_state": tracking_state,
                "owner": _extract_owner(text) or "BioETL Team",
                "declared_status": _extract_declared_status(text),
                "declared_class": _extract_declared_class(text),
                "lifecycle": lifecycle,
                "github_issue_number": issue_number,
                "github_issue_url": (
                    f"https://github.com/SatoryKono/BioactivityDataAcquisition/issues/{issue_number}"
                    if issue_number is not None
                    else None
                ),
                "catalog_lifecycle": plan_lifecycle.get(path),
                "canonical_successor": docs_draft_successors.get(path),
                "root_doc_kind": ROOT_DOC_KINDS.get(path),
                "surface_family": surface_family,
                "status": status,
                "freshness": freshness,
                "inbound_links": int(incoming[path]),
                "outbound_links": int(outgoing_counts[path]),
                "duplicate_group": duplicate_group,
                "duplicate_resolution": (
                    lifecycle
                    if lifecycle in {
                        "published_skill_reference_redirect",
                        "generated_skill_reference_mirror",
                    }
                    else None
                ),
                "diagram_kind": diagram_kind,
                "generated_route": route.route_id if route else None,
                "generated_route_exception": route_exception,
                "generator": route.generator if route else None,
                "commit_policy": route.commit_policy if route else None,
                "recommended_action": action,
            }
        )

    routes_payload = [
        {
            "id": route.route_id,
            "generator": route.generator,
            "output_kind": route.output_kind,
            "commit_policy": route.commit_policy,
            "outputs": list(route.outputs),
            "notes": route.notes,
        }
        for route in sorted(routes, key=lambda item: item.route_id)
    ]

    return {
        "schema_version": 1,
        "generator": "python -m scripts.docs generate-cleanup-inventory --update",
        "check_command": "python -m scripts.docs generate-cleanup-inventory --check",
        "source_inputs": [
            "git ls-files",
            "bounded docs/reports local ignored docs scan",
            "configs/quality/repo_structure_catalog.yaml",
            "configs/quality/generated_artifact_routing.yaml",
            "local markdown links",
        ],
        "summary": {
            "total_doc_like": len(records),
            "total_doc_like_tracked": sum(
                1 for row in records if row["tracking_state"] == "tracked"
            ),
            "total_doc_like_ignored_local": sum(
                1 for row in records if row["tracking_state"] == "ignored_local"
            ),
            "docs_reports_local_count": len(local_docs_reports),
            "by_status": dict(sorted(status_counts.items())),
            "by_surface_family": dict(sorted(surface_counts.items())),
            "by_tracking_state": dict(sorted(tracking_state_counts.items())),
            "by_lifecycle": dict(sorted(lifecycle_counts.items())),
            "github_issue_lifecycle_counts": dict(
                sorted(github_issue_lifecycle_counts.items())
            ),
            "by_recommended_action": dict(sorted(action_counts.items())),
            "by_section": dict(sorted(section_counts.items())),
            "duplicate_group_count": duplicate_group_count,
            "generated_without_route_count": generated_without_route_count,
            "generated_without_route_or_exception_count": generated_without_route_or_exception_count,
            "generated_route_count": len(routes_payload),
            "scan_errors": scan_errors,
            "scan_error_count": len(scan_errors),
        },
        "generated_routes": routes_payload,
        "files": records,
    }


def _md_table(headers: list[str], rows: list[list[object]]) -> list[str]:
    output = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        output.append("| " + " | ".join(str(cell) for cell in row) + " |")
    return output


def _render_markdown(payload: dict[str, Any]) -> str:
    summary = payload["summary"]
    files = payload["files"]
    generated_routes = payload["generated_routes"]

    lines: list[str] = [
        "# Documentation Cleanup Inventory",
        "",
        "> Generated by `python -m scripts.docs generate-cleanup-inventory --update`.",
        "> Do not edit this file manually; update the generator or routing registry instead.",
        "",
        "## Summary",
        "",
    ]
    lines.extend(
        _md_table(
            ["Metric", "Value"],
            [
                ["Doc-like files", summary["total_doc_like"]],
                ["Tracked doc-like files", summary["total_doc_like_tracked"]],
                [
                    "Ignored local docs/reports files",
                    summary["total_doc_like_ignored_local"],
                ],
                ["Duplicate groups", summary["duplicate_group_count"]],
                [
                    "Generated without route or exception",
                    summary["generated_without_route_or_exception_count"],
                ],
                ["Generated routes", summary["generated_route_count"]],
            ],
        )
    )
    lines.extend(["", "## Tracking State", ""])
    lines.extend(
        _md_table(
            ["Tracking State", "Count"],
            [[key, value] for key, value in summary["by_tracking_state"].items()],
        )
    )
    lines.extend(["", "## Lifecycle Counts", ""])
    lines.extend(
        _md_table(
            ["Lifecycle", "Count"],
            [[key, value] for key, value in summary["by_lifecycle"].items()],
        )
    )
    lines.extend(["", "## GitHub Issue Drafts And Packs", ""])
    lines.extend(
        _md_table(
            ["Lifecycle", "Count"],
            [
                [key, value]
                for key, value in summary["github_issue_lifecycle_counts"].items()
            ],
        )
    )
    lines.extend(["", "## Status Counts", ""])
    lines.extend(
        _md_table(
            ["Status", "Count"],
            [[key, value] for key, value in summary["by_status"].items()],
        )
    )
    lines.extend(["", "## Surface Families", ""])
    lines.extend(
        _md_table(
            ["Surface", "Count"],
            [[key, value] for key, value in summary["by_surface_family"].items()],
        )
    )
    lines.extend(["", "## Recommended Actions", ""])
    lines.extend(
        _md_table(
            ["Action", "Count"],
            [[key, value] for key, value in summary["by_recommended_action"].items()],
        )
    )

    high_signal = [
        row
        for row in files
        if row["status"] in {"Duplicate", "Deprecated", "Unknown"}
        or row["recommended_action"] in {"archive-after-migration", "inventory-review"}
    ][:80]
    lines.extend(["", "## Cleanup Candidates", ""])
    lines.extend(
        _md_table(
            ["Path", "Status", "Inbound", "Action"],
            [
                [
                    f"`{row['path']}`",
                    row["status"],
                    row["inbound_links"],
                    row["recommended_action"],
                ]
                for row in high_signal
            ],
        )
    )

    generated_examples = [
        row
        for row in files
        if row["status"] == "Generated"
        and (
            row["generated_route"]
            or row["generated_route_exception"]
            or row["diagram_kind"]
        )
    ][:80]
    lines.extend(["", "## Generated Artifact Examples", ""])
    lines.extend(
        _md_table(
            ["Path", "Route", "Exception", "Kind", "Generator"],
            [
                [
                    f"`{row['path']}`",
                    row["generated_route"] or "",
                    row["generated_route_exception"] or "",
                    row["diagram_kind"] or "",
                    row["generator"] or "",
                ]
                for row in generated_examples
            ],
        )
    )

    issue_examples = [
        row for row in files if str(row["path"]).startswith(".github/ISSUES/")
    ][:40]
    lines.extend(["", "## GitHub Issue Evidence Examples", ""])
    lines.extend(
        _md_table(
            ["Path", "Lifecycle", "Issue", "Action"],
            [
                [
                    f"`{row['path']}`",
                    row["lifecycle"] or "",
                    row["github_issue_number"] or "",
                    row["recommended_action"],
                ]
                for row in issue_examples
            ],
        )
    )

    docs_reports_examples = [
        row for row in files if str(row["path"]).startswith("docs/reports/")
    ][:40]
    lines.extend(["", "## Docs Reports Evidence Examples", ""])
    lines.extend(
        _md_table(
            ["Path", "Tracking", "Lifecycle", "Action"],
            [
                [
                    f"`{row['path']}`",
                    row["tracking_state"],
                    row["lifecycle"] or "",
                    row["recommended_action"],
                ]
                for row in docs_reports_examples
            ],
        )
    )

    lines.extend(["", "## Generated Route Registry", ""])
    lines.extend(
        _md_table(
            ["Route", "Generator", "Commit Policy"],
            [
                [route["id"], f"`{route['generator']}`", route["commit_policy"]]
                for route in generated_routes[:80]
            ],
        )
    )

    lines.extend(
        [
            "",
            "## Verification",
            "",
            "- `python -m scripts.docs generate-cleanup-inventory --check`",
            "- `python -m scripts.docs check-links --links --specs --configs`",
            "- `python -m scripts.docs check-drift --runtime-mirrors --freshness`",
            "",
            "The JSON sibling contains the complete per-file matrix.",
            "",
        ]
    )
    return "\n".join(lines)


def _write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def _generated_route_violations(payload: dict[str, Any]) -> list[str]:
    return sorted(
        str(row["path"])
        for row in payload.get("files", [])
        if isinstance(row, dict)
        and row.get("status") == "Generated"
        and not row.get("generated_route")
        and not row.get("generated_route_exception")
    )


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--update", action="store_true", help="Regenerate inventory files."
    )
    mode.add_argument(
        "--check", action="store_true", help="Check generated inventory drift."
    )
    parser.add_argument("--json-output", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--markdown-output", type=Path, default=DEFAULT_MD)
    parser.add_argument("--print-summary", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    payload = _build_inventory()
    json_content = (
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    )
    md_content = _render_markdown(payload)

    if args.print_summary:
        print(
            json.dumps(payload["summary"], ensure_ascii=False, indent=2, sort_keys=True)
        )

    if args.check:
        mismatches = []
        for path, content in (
            (args.json_output, json_content),
            (args.markdown_output, md_content),
        ):
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                mismatches.append(_repo_relative(path))
        if mismatches:
            for mismatch in mismatches:
                print(f"[drift] mismatch: {mismatch}")
            print(
                "[hint] run: python -m scripts.docs generate-cleanup-inventory --update"
            )
            return 1
        route_violations = _generated_route_violations(payload)
        if route_violations:
            print("[route-gap] Generated docs without route or exception:")
            for path in route_violations[:20]:
                print(f"  - {path}")
            if len(route_violations) > 20:
                print(f"  ... and {len(route_violations) - 20} more")
            print("[hint] add a route to configs/quality/generated_artifact_routing.yaml")
            return 1
        print("[documentation-cleanup-inventory] inventory is synchronized")
        return 0

    if args.update or not args.check:
        changed = [
            _write_if_changed(args.json_output, json_content),
            _write_if_changed(args.markdown_output, md_content),
        ]
        if any(changed):
            print("[documentation-cleanup-inventory] inventory updated")
        else:
            print("[documentation-cleanup-inventory] inventory already synchronized")
        return 0

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
