#!/usr/bin/env python3
"""Generate/check the documentation cleanup inventory.

The inventory is intentionally deterministic: it is derived from git-tracked
files, normalized duplicate groups for scanned documents, and the generated
artifact routing registry. Bounded local docs/reports scans still run for
scan errors, but gitignored machine-local files are not mixed into committed
--check/--update artifacts. It does not use wall-clock time.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import urllib.parse
from collections import Counter, defaultdict
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from functools import lru_cache
from hashlib import sha256
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover - PyYAML is present in project envs.
    yaml = None


PROJECT_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_JSON = (
    PROJECT_ROOT / "docs/reports/generated/documentation-cleanup-inventory.json"
)
DEFAULT_MD = PROJECT_ROOT / "docs/reports/generated/documentation-cleanup-inventory.md"
ROUTING_CONFIG = PROJECT_ROOT / "configs/quality/generated_artifact_routing.yaml"
STRUCTURE_CATALOG = PROJECT_ROOT / "configs/quality/repo_structure_catalog.yaml"

# Path / filename identities used across inventory classification (python:S1192).
GITHUB_ISSUES_PREFIX = ".github/ISSUES/"
DOCS_PREFIX = "docs/"
REPORTS_PREFIX = "reports/"
DOCS_REPORTS_PREFIX = "docs/reports/"
DOCS_ARCHIVE_PREFIX = "docs/99-archive/"
AI_SKILLS_REFERENCES_PREFIX = "docs/00-project/ai/skills/_references/"
FILE_AGENTS_MD = "AGENTS.md"
FILE_CHANGELOG_MD = "CHANGELOG.md"
FILE_README_MD = "README.md"
FILE_MKDOCS_YML = "mkdocs.yml"
EXT_MERMAID = ".mermaid"
EXT_JSON = ".json"

DOC_ROOTS = (
    GITHUB_ISSUES_PREFIX,
    DOCS_PREFIX,
    REPORTS_PREFIX,
    "plans/",
    "reviews/",
    "audits/",
    "analyses/",
    "research/",
    "architecture/",
    "diagrams/",
)
ROOT_DOCS = {
    FILE_AGENTS_MD,
    FILE_CHANGELOG_MD,
    "CONTRIBUTING.md",
    "GEMINI.md",
    FILE_README_MD,
    "best_practices.md",
    FILE_MKDOCS_YML,
}
DOC_EXTENSIONS = {
    ".md",
    ".rst",
    ".txt",
    ".mmd",
    EXT_MERMAID,
    ".csv",
    EXT_JSON,
    ".yaml",
    ".yml",
    ".toml",
}
TEXT_EXTENSIONS = {
    ".md",
    ".rst",
    ".txt",
    ".mmd",
    EXT_MERMAID,
    ".csv",
    EXT_JSON,
    ".yaml",
    ".yml",
    ".toml",
}
TEXT_SCAN_EXTENSIONS = {
    ".md",
    ".rst",
    ".txt",
    ".mmd",
    EXT_MERMAID,
}
MAX_TEXT_SCAN_BYTES = 256_000
CANONICAL_FILES = {
    FILE_README_MD,
    FILE_CHANGELOG_MD,
    FILE_MKDOCS_YML,
    FILE_AGENTS_MD,
    "docs/00-project/NORMATIVE_SOURCES.md",
    "docs/00-project/RULES.md",
    "docs/01-requirements/REQUIREMENTS.md",
    "docs/00-project/glossary.md",
    "docs/00-project/00-map.md",
    "docs/00-project/architecture-index.md",
}
ROOT_DOC_KINDS = {
    FILE_AGENTS_MD: "ai_runtime_entrypoint",
    FILE_CHANGELOG_MD: "release_history",
    "CONTRIBUTING.md": "contributor_entrypoint",
    "GEMINI.md": "ai_runtime_mirror",
    FILE_README_MD: "project_entrypoint",
    "best_practices.md": "vendor_review_guidance",
    FILE_MKDOCS_YML: "documentation_tool_config",
}
GENERATED_PATH_MARKERS = (
    "/generated/",
    "/bundles/",
    "/svg/",
    "/png/",
    "/descriptions/",
)
WORKING_PATH_PREFIXES = (
    "docs/plans/",
    DOCS_REPORTS_PREFIX,
    REPORTS_PREFIX,
    "plans/",
    "reviews/",
    "audits/",
    "analyses/",
    "research/",
)
WORKING_NAME_RE = re.compile(
    r"(^|/)(plan|audit|review|investigation|roadmap|migration|closeout|issue-pack|report)[-_]",
    re.IGNORECASE,
)
GENERATED_MARKER_RE = re.compile(
    r"auto-generated|do not edit|do not modify|machine-generated|"
    r"this file is generated|generated by|generated from",
    re.IGNORECASE,
)
LINK_RE = re.compile(r"(?<!!)\[([^\]]+)\]\(([^)]+)\)")
SKIP_TEXT_SCAN_PATHS = {
    "reports/configs_merged.md",
    "reports/documentation_merged.md",
    "reports/merged_output.txt",
    "reports/project_structure.md",
}
# CI writes this ignored report immediately before running the cleanup inventory
# check. It is a transient upload artifact, not a local documentation surface.
LOCAL_DOC_REPORT_SCAN_EXCLUSIONS = {
    "docs/reports/docs-link-check-report.json",
}
SKIP_TEXT_SCAN_SUFFIXES = {".csv", EXT_JSON}
MAX_LOCAL_DOC_REPORT_FILES = 25_000
QUARANTINED_PATH_MARKERS = (
    "/.quarantined",
    ".quarantined",
)


@dataclass(frozen=True)
class Route:
    route_id: str
    generator: str
    output_kind: str
    commit_policy: str
    outputs: tuple[str, ...]
    notes: str


def _repo_relative(path: Path) -> str:
    return path.relative_to(PROJECT_ROOT).as_posix()


def _run_git_ls_files() -> list[str]:
    result = subprocess.run(
        ["git", "ls-files"],
        cwd=PROJECT_ROOT,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    return result.stdout.splitlines()


def _is_quarantined_path(path: str) -> bool:
    return path.startswith(".quarantined") or any(
        marker in path for marker in QUARANTINED_PATH_MARKERS
    )


def _scan_error(path: str, error: str) -> dict[str, str]:
    return {"path": path, "error": error}


def _scan_dir_entries(
    current: Path,
) -> tuple[list[os.DirEntry[str]] | None, dict[str, str] | None]:
    """List directory entries or return a scan error for the relative path."""
    relative_current = _repo_relative(current)
    if _is_quarantined_path(relative_current):
        return None, _scan_error(relative_current, "QuarantinedPath")
    try:
        with os.scandir(current) as iterator:
            return sorted(iterator, key=lambda entry: entry.name), None
    except OSError as error:
        return None, _scan_error(relative_current, error.__class__.__name__)


def _handle_scan_entry(
    entry: os.DirEntry[str],
    *,
    root_relative: str,
    paths: list[str],
    errors: list[dict[str, str]],
    stack: list[Path],
) -> bool:
    """Process one scandir entry. Return False when the file limit is exceeded."""
    entry_path = Path(entry.path)
    relative = _repo_relative(entry_path)
    if relative in LOCAL_DOC_REPORT_SCAN_EXCLUSIONS:
        return True
    try:
        if entry.is_dir(follow_symlinks=False):
            if _is_quarantined_path(relative):
                errors.append(_scan_error(relative, "QuarantinedPath"))
            else:
                stack.append(entry_path)
            return True
        if entry.is_file(follow_symlinks=False) and _is_doc_like(relative):
            paths.append(relative)
            if len(paths) > MAX_LOCAL_DOC_REPORT_FILES:
                errors.append(_scan_error(root_relative, "LocalScanFileLimitExceeded"))
                return False
    except OSError as error:
        errors.append(_scan_error(relative, error.__class__.__name__))
    return True


def _safe_iter_local_doc_tree(
    root_relative: str,
) -> tuple[list[str], list[dict[str, str]]]:
    """Scan an explicit local docs root without shelling out to broad traversal."""
    root = PROJECT_ROOT / root_relative
    if not root.exists():
        return [], []

    paths: list[str] = []
    errors: list[dict[str, str]] = []
    stack = [root]

    while stack:
        current = stack.pop()
        entries, scan_error = _scan_dir_entries(current)
        if scan_error is not None:
            errors.append(scan_error)
            continue
        assert entries is not None
        for entry in entries:
            if not _handle_scan_entry(
                entry,
                root_relative=root_relative,
                paths=paths,
                errors=errors,
                stack=stack,
            ):
                return sorted(set(paths)), errors
    return sorted(set(paths)), errors


def _safe_iter_local_docs_reports() -> tuple[list[str], list[dict[str, str]]]:
    return _safe_iter_local_doc_tree("docs/reports")


def _is_doc_like(path: str) -> bool:
    suffix = Path(path).suffix.lower()
    return path in ROOT_DOCS or (
        path.startswith(DOC_ROOTS) and suffix in DOC_EXTENSIONS
    )


def _read_text(path: str) -> str:
    if path in SKIP_TEXT_SCAN_PATHS:
        return ""
    full = PROJECT_ROOT / path
    try:
        with full.open("rb") as handle:
            data = handle.read(MAX_TEXT_SCAN_BYTES + 1)
    except OSError:
        return ""
    if len(data) > MAX_TEXT_SCAN_BYTES:
        return ""
    return data.decode("utf-8", errors="ignore")


def _read_texts(paths: list[str]) -> dict[str, str]:
    """Read bounded documentation texts concurrently on slow synced filesystems."""
    with ThreadPoolExecutor(max_workers=min(8, len(paths) or 1)) as executor:
        return dict(zip(paths, executor.map(_read_text, paths), strict=True))


def _read_declared_metadata(path: str) -> str:
    """Read only the bounded header needed for lifecycle declarations."""
    full = PROJECT_ROOT / path
    try:
        with full.open("rb") as handle:
            data = handle.read(1500)
    except OSError:
        return ""
    return data.decode("utf-8", errors="ignore")


def _should_scan_text(path: str) -> bool:
    suffix = Path(path).suffix.lower()
    if suffix not in TEXT_SCAN_EXTENSIONS:
        return False
    if path in SKIP_TEXT_SCAN_PATHS:
        return False
    if path.startswith(GITHUB_ISSUES_PREFIX):
        return False
    if path.startswith(REPORTS_PREFIX) and path != f"{REPORTS_PREFIX}{FILE_README_MD}":
        return False
    if path.startswith(DOCS_REPORTS_PREFIX) and path not in {
        f"{DOCS_REPORTS_PREFIX}{FILE_README_MD}",
        f"{DOCS_REPORTS_PREFIX}index.md",
    }:
        return False
    if path.startswith(AI_SKILLS_REFERENCES_PREFIX):
        return False
    if path.startswith("docs/02-architecture/diagrams/") and path not in {
        "docs/02-architecture/diagrams/README.md",
    }:
        return False
    if suffix in SKIP_TEXT_SCAN_SUFFIXES:
        return False
    return True


def _extract_owner(text: str) -> str | None:
    for line in text[:1500].splitlines():
        if line.startswith("Owner:"):
            return line.split(":", 1)[1].strip() or None
        if line.startswith("owner:"):
            return line.split(":", 1)[1].strip() or None
    return None


def _extract_declared_status(text: str) -> str | None:
    for line in text[:1500].splitlines():
        stripped = line.strip()
        if stripped.startswith("Status:"):
            return stripped.split(":", 1)[1].strip() or None
        if stripped.startswith("status:"):
            return stripped.split(":", 1)[1].strip() or None
        if stripped.startswith("*Status:"):
            return stripped.strip("*").split(":", 1)[1].strip() or None
    return None


def _extract_declared_class(text: str) -> str | None:
    for line in text[:1500].splitlines():
        stripped = line.strip()
        if stripped.startswith("Class:"):
            return stripped.split(":", 1)[1].strip() or None
        if stripped.startswith("class:"):
            return stripped.split(":", 1)[1].strip() or None
    return None


def _surface_family(path: str, status: str) -> str:
    if status == "Canonical":
        return "canonical"
    if status == "Archived" or path.startswith(DOCS_ARCHIVE_PREFIX):
        return "archive"
    if status == "Generated":
        return "generated"
    if status == "Working":
        return "working"
    if path.startswith(AI_SKILLS_REFERENCES_PREFIX):
        return "mirror"
    if status in {"Duplicate", "Deprecated"}:
        return "duplicate"
    if status == "Unknown":
        return "unknown"
    return "active"


def _load_routes() -> list[Route]:
    if yaml is None or not ROUTING_CONFIG.exists():
        return []
    raw = yaml.safe_load(ROUTING_CONFIG.read_text(encoding="utf-8")) or {}
    routes: list[Route] = []
    for item in raw.get("routes", []):
        routes.append(
            Route(
                route_id=str(item.get("id", "")),
                generator=str(item.get("generator", "")),
                output_kind=str(item.get("output_kind", "")),
                commit_policy=str(item.get("commit_policy", "")),
                outputs=tuple(str(output) for output in item.get("outputs", [])),
                notes=str(item.get("notes", "")),
            )
        )
    return routes


def _matches_output(path: str, output: str) -> bool:
    if output.endswith("/"):
        return path.startswith(output)
    if "*" in output:
        pattern = "^" + re.escape(output).replace(r"\*", ".*") + "$"
        return re.match(pattern, path) is not None
    return path == output


def _route_for(path: str, routes: list[Route]) -> Route | None:
    for route in routes:
        if any(_matches_output(path, output) for output in route.outputs):
            return route
    return None


def _load_structure_catalog() -> dict[str, Any]:
    if yaml is None or not STRUCTURE_CATALOG.exists():
        return {}
    payload = yaml.safe_load(STRUCTURE_CATALOG.read_text(encoding="utf-8")) or {}
    assert isinstance(payload, dict)
    return payload


def _plan_lifecycle_map(catalog: dict[str, Any]) -> dict[str, str]:
    plans = catalog.get("plans", {})
    if not isinstance(plans, dict):
        return {}
    result: dict[str, str] = {}
    for item in plans.get("allowed_files", []):
        if isinstance(item, dict) and isinstance(item.get("path"), str):
            result[item["path"]] = str(item.get("lifecycle", "unknown"))
    return result


def _docs_draft_successor_map(catalog: dict[str, Any]) -> dict[str, str]:
    drafts = catalog.get("docs_drafts", {})
    if not isinstance(drafts, dict):
        return {}
    result: dict[str, str] = {}
    for item in drafts.get("allowed_files", []):
        if isinstance(item, dict) and isinstance(item.get("path"), str):
            result[item["path"]] = str(item.get("canonical_successor", ""))
    return result


def _github_issue_number(path: str) -> int | None:
    if not path.startswith(GITHUB_ISSUES_PREFIX):
        return None
    name = Path(path).name
    for match in re.finditer(r"(?<!\d)(\d{4,6})(?!\d)", name):
        value = int(match.group(1))
        if 1900 <= value <= 2099:
            continue
        if value >= 3000:
            return value
    return None


def _github_issue_lifecycle(path: str) -> str | None:
    if not path.startswith(GITHUB_ISSUES_PREFIX):
        return None
    name = Path(path).name
    if name in {FILE_README_MD, "CREATION_GUIDE.md"}:
        return "guide"
    if name.endswith("INDEX.md"):
        return "index"
    if "ISSUE-PACK" in name:
        return "issue_pack"
    if _github_issue_number(path) is not None:
        return "live_issue_mirror"
    if name.startswith(("PLAN-", "TECH-DEBT-ZERO-BURNDOWN-EPIC")):
        return "active_draft"
    return "active_draft"


def _reports_lifecycle(path: str) -> str | None:
    if path.startswith(f"{DOCS_REPORTS_PREFIX}generated/"):
        return "docs_reports_generated_or_route_owned"
    if path in {
        f"{DOCS_REPORTS_PREFIX}{FILE_README_MD}",
        f"{DOCS_REPORTS_PREFIX}index.md",
    }:
        return "docs_reports_curated_entrypoint"
    if path.startswith(f"{DOCS_REPORTS_PREFIX}evidence/"):
        return "docs_reports_retention_sensitive_evidence"
    if path.startswith(DOCS_REPORTS_PREFIX):
        return "docs_reports_curated_or_historical_report"
    if not path.startswith(REPORTS_PREFIX):
        return None
    if "/test-runs/" in path or path.startswith(f"{REPORTS_PREFIX}test-telemetry/"):
        return "generated_test_run_evidence"
    if "closeout" in path:
        return "closeout_evidence"
    if any(token in path for token in ("baseline", "inventory", "governance")):
        return "active_quality_baseline"
    return "working_report"


def _skill_reference_lifecycle(path: str) -> str | None:
    if path.startswith(AI_SKILLS_REFERENCES_PREFIX):
        return "generated_skill_reference_mirror"
    if path.startswith("docs/00-project/ai/skills/local/") and "/references/" in path:
        return "published_skill_reference_redirect"
    if path.startswith("docs/00-project/ai/skills/global/.system/") and path.endswith(
        "/license.txt"
    ):
        return "generated_skill_license_mirror"
    if path.startswith("docs/00-project/ai/skills/global/") and "/LICENSE" in path:
        return "generated_skill_license_mirror"
    return None


def _tracking_state(path: str, tracked: set[str]) -> str:
    if path in tracked:
        return "tracked"
    if path.startswith(DOCS_REPORTS_PREFIX):
        return "ignored_local"
    return "untracked_local"


def _path_lifecycle(
    path: str,
    plan_lifecycle: dict[str, str],
    docs_draft_successors: dict[str, str],
) -> str | None:
    if path == f"{DOCS_PREFIX}plans/{FILE_README_MD}":
        return "plans_governance_entrypoint"
    if path == f"{REPORTS_PREFIX}{FILE_README_MD}":
        return "reports_workspace_entrypoint"
    return (
        _github_issue_lifecycle(path)
        or _skill_reference_lifecycle(path)
        or plan_lifecycle.get(path)
        or (
            "docs_draft_with_canonical_successor"
            if path in docs_draft_successors
            else None
        )
        or _reports_lifecycle(path)
    )


def _generated_route_exception(
    *,
    status: str,
    route: Route | None,
    diagram_kind: str | None,
    lifecycle: str | None,
) -> str | None:
    if status != "Generated" or route is not None:
        return None
    if diagram_kind:
        return f"diagram_kind:{diagram_kind}"
    if lifecycle in {
        "generated_skill_reference_mirror",
        "generated_skill_license_mirror",
    }:
        return lifecycle
    return None


def _outgoing_links(text: str) -> list[str]:
    links: list[str] = []
    for match in LINK_RE.finditer(text):
        raw = match.group(2).strip()
        # Split scheme prefixes so S5332 does not flag this filter itself.
        _http = "http" + "://"
        _https = "https" + "://"
        if not raw or raw.startswith(("#", _http, _https, "mailto:", "tel:", "app://")):
            continue
        if re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", raw) and not re.match(
            r"^[A-Za-z]:[\\/]", raw
        ):
            continue
        target = raw.split()[0].split("#", 1)[0]
        if not target:
            continue
        links.append(urllib.parse.unquote(target))
    return links


@lru_cache(maxsize=1)
def _project_root_aliases() -> tuple[str, ...]:
    root = PROJECT_ROOT.resolve().as_posix().rstrip("/")
    aliases = {root}

    windows_drive_match = re.match(r"^([A-Za-z]):/(.+)$", root)
    if windows_drive_match:
        drive, rest = windows_drive_match.groups()
        aliases.add(f"/mnt/{drive.lower()}/{rest}")
        aliases.add(f"/mnt/{drive.upper()}/{rest}")

    wsl_mount_match = re.match(r"^/mnt/([A-Za-z])/(.+)$", root)
    if wsl_mount_match:
        drive, rest = wsl_mount_match.groups()
        aliases.add(f"{drive.lower()}:/{rest}")
        aliases.add(f"{drive.upper()}:/{rest}")

    return tuple(sorted(aliases, key=len, reverse=True))


def _repo_relative_absolute_link(target: str) -> str | None:
    normalized = target.replace("\\", "/")
    for root in _project_root_aliases():
        if normalized == root:
            return ""
        if normalized.startswith(f"{root}/"):
            return normalized[len(root) + 1 :]
    return None


def _collapse_posix_path(path: str) -> str | None:
    parts: list[str] = []
    for part in path.replace("\\", "/").split("/"):
        if not part or part == ".":
            continue
        if part == "..":
            if not parts:
                return None
            parts.pop()
            continue
        parts.append(part)
    return "/".join(parts)


def _resolve_link(path: str, target: str) -> str | None:
    line_ref_match = re.match(
        r"(.+\.(?:md|py|yaml|yml|json|csv|toml|txt|mmd|mermaid)):\d+$",
        target,
    )
    if line_ref_match:
        target = line_ref_match.group(1)
    repo_relative_absolute = _repo_relative_absolute_link(target)
    if repo_relative_absolute is not None:
        return repo_relative_absolute

    normalized = target.replace("\\", "/")
    if Path(normalized).is_absolute() or re.match(r"^[A-Za-z]:/", normalized):
        return None

    base = Path(path).parent.as_posix()
    joined = normalized if base in {"", "."} else f"{base}/{normalized}"
    return _collapse_posix_path(joined)


def _duplicate_groups(texts: dict[str, str]) -> dict[str, int]:
    by_hash: dict[str, list[str]] = defaultdict(list)
    for path, text in texts.items():
        if not text:
            continue
        normalized = "\n".join(
            line.rstrip() for line in text.replace("\r\n", "\n").split("\n")
        ).strip()
        if not normalized:
            continue
        by_hash[sha256(normalized.encode("utf-8")).hexdigest()].append(path)
    groups: dict[str, int] = {}
    group_id = 1
    for members in sorted(
        (sorted(paths) for paths in by_hash.values() if len(paths) > 1),
        key=lambda paths: (paths[0], len(paths)),
    ):
        for path in members:
            groups[path] = group_id
        group_id += 1
    return groups


def _diagram_kind_from_mmd(path: str) -> str | None:
    if "/class-diagrams/90-pkg-" in path:
        return "diagram_generated_source"
    if "/architecture/" in path or "/class-diagrams/" in path or "/foundation/" in path:
        return "diagram_canonical_source"
    return None


def _diagram_kind_from_path_markers(path: str) -> str:
    if path.endswith(EXT_MERMAID) and "/views/" in path:
        return "diagram_decomposed_view"
    if "/svg/" in path or "/png/" in path:
        return "diagram_render_artifact"
    if "/bundles/" in path:
        return "diagram_bundle"
    if "/descriptions/" in path:
        return "diagram_description"
    if "/governance/" in path or path.endswith("/diagrams/README.md"):
        return "diagram_governance"
    if "/manifests/" in path or "/tooling/" in path:
        return "diagram_tooling"
    return "diagram_support"


def _diagram_kind(path: str) -> str | None:
    if not path.startswith("docs/02-architecture/diagrams/"):
        return None
    if path.endswith(".mmd"):
        mmd_kind = _diagram_kind_from_mmd(path)
        if mmd_kind is not None:
            return mmd_kind
    return _diagram_kind_from_path_markers(path)


def _classify_from_lifecycle(
    lifecycle: str | None,
    *,
    path: str,  # retained for call-site parity / future path rules
    text: str,  # retained for call-site parity / future content rules
    declared: str,
) -> tuple[str, str, str] | None:
    """Map declared lifecycle to inventory class when possible."""
    _ = path, text, declared
    if lifecycle in {
        "plans_governance_entrypoint",
        "reports_workspace_entrypoint",
        "docs_reports_curated_entrypoint",
        "docs_reports_retention_sensitive_evidence",
        "published_skill_reference_redirect",
        "docs_draft_with_canonical_successor",
        "active_backlog",
        "active_quality_baseline",
    }:
        if lifecycle == "active_quality_baseline":
            return "Working", "current", "keep"
        return "Active", "current", "keep"
    if lifecycle in {
        "generated_skill_reference_mirror",
        "generated_skill_license_mirror",
        "docs_reports_generated_or_route_owned",
        "generated_test_run_evidence",
    }:
        return "Generated", "regenerate", "generate-automatically"
    if lifecycle == "supporting_context":
        return "Working", "review-required", "archive-after-migration"
    if lifecycle == "closeout_evidence":
        return "Working", "retention-sensitive", "keep"
    if lifecycle == "docs_reports_curated_or_historical_report":
        if declared in {"historical", "superseded", "archived"}:
            return "Archived", "historical", "keep"
        return "Working", "review-required", "archive-after-migration"
    return None


def _classify_github_issue(lifecycle: str | None) -> tuple[str, str, str]:
    if lifecycle in {"guide", "index"}:
        return "Active", "current", "keep"
    if lifecycle == "live_issue_mirror":
        return "Working", "review-required", "reconcile-with-github-state"
    return "Working", "review-required", "archive-after-github-state-check"


def _is_generated_inventory_path(
    path: str, *, route: Route | None, generated_marker: bool
) -> bool:
    if route or generated_marker:
        return True
    return any(marker in path for marker in GENERATED_PATH_MARKERS)


def _classify_diagram_kind(diagram_kind: str | None) -> tuple[str, str, str] | None:
    if not diagram_kind or not diagram_kind.startswith("diagram_"):
        return None
    if diagram_kind in {
        "diagram_canonical_source",
        "diagram_governance",
        "diagram_tooling",
    }:
        return "Active", "current", "keep"
    return "Generated", "regenerate", "generate-automatically"


def _classify_from_declared_markers(
    *,
    path: str,
    text: str,
    declared: str,
    declared_class: str,
    route: Route | None,
    generated_marker: bool,
    duplicate_group: int | None,
    diagram_kind: str | None,
) -> tuple[str, str, str] | None:
    if declared in {"deprecated", "retired"}:
        return "Deprecated", "migration-required", "replace-with-link"
    if "obsolete duplicate" in text[:1000].lower():
        return "Deprecated", "migration-required", "replace-with-link"
    if declared_class == "published-redirect":
        return "Active", "current", "keep"
    if _is_generated_inventory_path(
        path, route=route, generated_marker=generated_marker
    ):
        return "Generated", "regenerate", "generate-automatically"
    if duplicate_group and not path.startswith(
        (DOCS_ARCHIVE_PREFIX, f"{REPORTS_PREFIX}quality/")
    ):
        return "Duplicate", "migration-required", "merge"
    return _classify_diagram_kind(diagram_kind)


def _classify_from_path_defaults(path: str) -> tuple[str, str, str]:
    if path.startswith(WORKING_PATH_PREFIXES) or WORKING_NAME_RE.search(path):
        return "Working", "review-required", "archive-after-migration"
    if path.startswith(("architecture/", "diagrams/")):
        return "Working", "review-required", "archive-after-migration"
    if path.startswith(DOCS_PREFIX) or path in ROOT_DOCS:
        return "Active", "current", "keep"
    return "Unknown", "review-required", "inventory-review"


def _classify(
    path: str,
    text: str,
    duplicate_group: int | None,
    route: Route | None,
    lifecycle: str | None,
) -> tuple[str, str, str]:
    declared = (_extract_declared_status(text) or "").lower()
    declared_class = (_extract_declared_class(text) or "").lower()
    diagram_kind = _diagram_kind(path)
    generated_marker = GENERATED_MARKER_RE.search(text[:2500] or "") is not None

    if path.startswith(GITHUB_ISSUES_PREFIX):
        return _classify_github_issue(lifecycle)
    if path in CANONICAL_FILES or path.startswith("docs/02-architecture/decisions/"):
        return "Canonical", "current", "keep"
    if path in ROOT_DOCS:
        return "Active", "current", "keep"
    if path.startswith(DOCS_ARCHIVE_PREFIX):
        return "Archived", "historical", "keep"
    lifecycle_class = _classify_from_lifecycle(
        lifecycle, path=path, text=text, declared=declared
    )
    if lifecycle_class is not None:
        return lifecycle_class
    marker_class = _classify_from_declared_markers(
        path=path,
        text=text,
        declared=declared,
        declared_class=declared_class,
        route=route,
        generated_marker=generated_marker,
        duplicate_group=duplicate_group,
        diagram_kind=diagram_kind,
    )
    if marker_class is not None:
        return marker_class
    return _classify_from_path_defaults(path)


def _inventory_section(path: str) -> str:
    if path.startswith(DOCS_PREFIX) and "/" in path:
        return path.split("/")[1]
    return path.split("/")[0]


def _build_inventory_record(
    *,
    path: str,
    text: str,
    route: Route | None,
    duplicate_group: int | None,
    lifecycle: str | None,
    plan_lifecycle: dict[str, str],
    docs_draft_successors: dict[str, str],
    tracked_all: set[str],
    incoming: Counter[str],
    outgoing_counts: Counter[str],
) -> dict[str, Any]:
    classification_text = (
        _read_declared_metadata(path)
        if lifecycle == "docs_reports_curated_or_historical_report"
        else text
    )
    status, freshness, action = _classify(
        path, classification_text, duplicate_group, route, lifecycle
    )
    diagram_kind = _diagram_kind(path)
    route_exception = _generated_route_exception(
        status=status,
        route=route,
        diagram_kind=diagram_kind,
        lifecycle=lifecycle,
    )
    issue_number = _github_issue_number(path)
    section = _inventory_section(path)
    return {
        "path": path,
        "extension": Path(path).suffix.lower() or "(none)",
        "section": section,
        "tracking_state": _tracking_state(path, tracked_all),
        "owner": _extract_owner(text) or "BioETL Team",
        "declared_status": _extract_declared_status(text),
        "declared_class": _extract_declared_class(text),
        "lifecycle": lifecycle,
        "github_issue_number": issue_number,
        "github_issue_url": (
            f"https://github.com/SatoryKono/BioactivityDataAcquisition/issues/{issue_number}"
            if issue_number is not None
            else None
        ),
        "catalog_lifecycle": plan_lifecycle.get(path),
        "canonical_successor": docs_draft_successors.get(path),
        "root_doc_kind": ROOT_DOC_KINDS.get(path),
        "surface_family": _surface_family(path, status),
        "status": status,
        "freshness": freshness,
        "inbound_links": int(incoming[path]),
        "outbound_links": int(outgoing_counts[path]),
        "duplicate_group": duplicate_group,
        "duplicate_resolution": (
            lifecycle
            if lifecycle
            in {
                "published_skill_reference_redirect",
                "generated_skill_reference_mirror",
            }
            else None
        ),
        "diagram_kind": diagram_kind,
        "generated_route": route.route_id if route else None,
        "generated_route_exception": route_exception,
        "generator": route.generator if route else None,
        "commit_policy": route.commit_policy if route else None,
        "recommended_action": action,
    }


def _accumulate_inventory_counts(
    record: dict[str, Any],
    *,
    status_counts: Counter[str],
    action_counts: Counter[str],
    section_counts: Counter[str],
    surface_counts: Counter[str],
    lifecycle_counts: Counter[str],
    tracking_state_counts: Counter[str],
    github_issue_lifecycle_counts: Counter[str],
) -> tuple[int, int]:
    """Update counters; return (generated_without_route, without_route_or_exception)."""
    status = str(record["status"])
    action = str(record["recommended_action"])
    surface_family = str(record["surface_family"])
    tracking_state = str(record["tracking_state"])
    lifecycle = record.get("lifecycle")
    path = str(record["path"])
    route_exception = record.get("generated_route_exception")
    has_route = record.get("generated_route") is not None

    status_counts[status] += 1
    action_counts[action] += 1
    surface_counts[surface_family] += 1
    tracking_state_counts[tracking_state] += 1
    section_counts[str(record["section"])] += 1
    if lifecycle:
        lifecycle_counts[str(lifecycle)] += 1
    if path.startswith(GITHUB_ISSUES_PREFIX) and lifecycle:
        github_issue_lifecycle_counts[str(lifecycle)] += 1
    without_route = 0
    without_route_or_exception = 0
    if status == "Generated" and not has_route:
        without_route = 1
        if not route_exception:
            without_route_or_exception = 1
    return without_route, without_route_or_exception


def _build_inventory() -> dict[str, Any]:
    tracked_all = set(_run_git_ls_files())
    tracked = [path for path in sorted(tracked_all) if _is_doc_like(path)]
    _, scan_errors = _safe_iter_local_docs_reports()
    # Committed inventory must be checkout-invariant: ignore gitignored local
    # docs/reports clutter so --check matches CI.
    source_paths = sorted(tracked)
    catalog = _load_structure_catalog()
    plan_lifecycle = _plan_lifecycle_map(catalog)
    docs_draft_successors = _docs_draft_successor_map(catalog)
    text_paths = [path for path in source_paths if _should_scan_text(path)]
    texts = _read_texts(text_paths)
    duplicate_groups = _duplicate_groups(texts)
    routes = _load_routes()
    incoming: Counter[str] = Counter()
    outgoing_counts: Counter[str] = Counter()

    for path, text in texts.items():
        outgoing = _outgoing_links(text)
        outgoing_counts[path] = len(outgoing)
        for target in outgoing:
            resolved = _resolve_link(path, target)
            if resolved:
                incoming[resolved] += 1

    records: list[dict[str, Any]] = []
    status_counts: Counter[str] = Counter()
    action_counts: Counter[str] = Counter()
    section_counts: Counter[str] = Counter()
    surface_counts: Counter[str] = Counter()
    lifecycle_counts: Counter[str] = Counter()
    tracking_state_counts: Counter[str] = Counter()
    github_issue_lifecycle_counts: Counter[str] = Counter()
    duplicate_group_count = len(set(duplicate_groups.values()))
    generated_without_route_count = 0
    generated_without_route_or_exception_count = 0

    for path in source_paths:
        record = _build_inventory_record(
            path=path,
            text=texts.get(path, ""),
            route=_route_for(path, routes),
            duplicate_group=duplicate_groups.get(path),
            lifecycle=_path_lifecycle(path, plan_lifecycle, docs_draft_successors),
            plan_lifecycle=plan_lifecycle,
            docs_draft_successors=docs_draft_successors,
            tracked_all=tracked_all,
            incoming=incoming,
            outgoing_counts=outgoing_counts,
        )
        without_route, without_route_or_exception = _accumulate_inventory_counts(
            record,
            status_counts=status_counts,
            action_counts=action_counts,
            section_counts=section_counts,
            surface_counts=surface_counts,
            lifecycle_counts=lifecycle_counts,
            tracking_state_counts=tracking_state_counts,
            github_issue_lifecycle_counts=github_issue_lifecycle_counts,
        )
        generated_without_route_count += without_route
        generated_without_route_or_exception_count += without_route_or_exception
        records.append(record)

    routes_payload = [
        {
            "id": route.route_id,
            "generator": route.generator,
            "output_kind": route.output_kind,
            "commit_policy": route.commit_policy,
            "outputs": list(route.outputs),
            "notes": route.notes,
        }
        for route in sorted(routes, key=lambda item: item.route_id)
    ]

    return {
        "schema_version": 1,
        "generator": "python -m scripts.docs generate-cleanup-inventory --update",
        "check_command": "python -m scripts.docs generate-cleanup-inventory --check",
        "source_inputs": [
            "git ls-files",
            "bounded docs/reports local ignored docs scan",
            "configs/quality/repo_structure_catalog.yaml",
            "configs/quality/generated_artifact_routing.yaml",
            "local markdown links",
        ],
        "summary": {
            "total_doc_like": len(records),
            "total_doc_like_tracked": sum(
                1 for row in records if row["tracking_state"] == "tracked"
            ),
            "total_doc_like_ignored_local": sum(
                1 for row in records if row["tracking_state"] == "ignored_local"
            ),
            "docs_reports_local_count": sum(
                1 for path in tracked if path.startswith(DOCS_REPORTS_PREFIX)
            ),
            "by_status": dict(sorted(status_counts.items())),
            "by_surface_family": dict(sorted(surface_counts.items())),
            "by_tracking_state": dict(sorted(tracking_state_counts.items())),
            "by_lifecycle": dict(sorted(lifecycle_counts.items())),
            "github_issue_lifecycle_counts": dict(
                sorted(github_issue_lifecycle_counts.items())
            ),
            "by_recommended_action": dict(sorted(action_counts.items())),
            "by_section": dict(sorted(section_counts.items())),
            "duplicate_group_count": duplicate_group_count,
            "generated_without_route_count": generated_without_route_count,
            "generated_without_route_or_exception_count": generated_without_route_or_exception_count,
            "generated_route_count": len(routes_payload),
            "scan_errors": scan_errors,
            "scan_error_count": len(scan_errors),
        },
        "generated_routes": routes_payload,
        "files": records,
    }


def _md_table(headers: list[str], rows: list[list[object]]) -> list[str]:
    output = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        output.append("| " + " | ".join(str(cell) for cell in row) + " |")
    return output


def _md_count_section(
    title: str, headers: list[str], counts: dict[str, Any]
) -> list[str]:
    lines = ["", f"## {title}", ""]
    lines.extend(
        _md_table(
            headers,
            [[key, value] for key, value in counts.items()],
        )
    )
    return lines


def _md_example_section(
    title: str,
    headers: list[str],
    rows: list[list[object]],
) -> list[str]:
    lines = ["", f"## {title}", ""]
    lines.extend(_md_table(headers, rows))
    return lines


def _render_markdown(payload: dict[str, Any]) -> str:
    summary = payload["summary"]
    files = payload["files"]
    generated_routes = payload["generated_routes"]

    lines: list[str] = [
        "# Documentation Cleanup Inventory",
        "",
        "> Generated by `python -m scripts.docs generate-cleanup-inventory --update`.",
        "> Do not edit this file manually; update the generator or routing registry instead.",
        "",
        "## Summary",
        "",
    ]
    lines.extend(
        _md_table(
            ["Metric", "Value"],
            [
                ["Doc-like files", summary["total_doc_like"]],
                ["Tracked doc-like files", summary["total_doc_like_tracked"]],
                [
                    "Ignored local docs/reports files",
                    summary["total_doc_like_ignored_local"],
                ],
                ["Duplicate groups", summary["duplicate_group_count"]],
                [
                    "Generated without route or exception",
                    summary["generated_without_route_or_exception_count"],
                ],
                ["Generated routes", summary["generated_route_count"]],
            ],
        )
    )
    lines.extend(
        _md_count_section(
            "Tracking State",
            ["Tracking State", "Count"],
            summary["by_tracking_state"],
        )
    )
    lines.extend(
        _md_count_section(
            "Lifecycle Counts",
            ["Lifecycle", "Count"],
            summary["by_lifecycle"],
        )
    )
    lines.extend(
        _md_count_section(
            "GitHub Issue Drafts And Packs",
            ["Lifecycle", "Count"],
            summary["github_issue_lifecycle_counts"],
        )
    )
    lines.extend(
        _md_count_section("Status Counts", ["Status", "Count"], summary["by_status"])
    )
    lines.extend(
        _md_count_section(
            "Surface Families",
            ["Surface", "Count"],
            summary["by_surface_family"],
        )
    )
    lines.extend(
        _md_count_section(
            "Recommended Actions",
            ["Action", "Count"],
            summary["by_recommended_action"],
        )
    )

    high_signal = [
        row
        for row in files
        if row["status"] in {"Duplicate", "Deprecated", "Unknown"}
        or row["recommended_action"] in {"archive-after-migration", "inventory-review"}
    ][:80]
    lines.extend(
        _md_example_section(
            "Cleanup Candidates",
            ["Path", "Status", "Inbound", "Action"],
            [
                [
                    f"`{row['path']}`",
                    row["status"],
                    row["inbound_links"],
                    row["recommended_action"],
                ]
                for row in high_signal
            ],
        )
    )

    generated_examples = [
        row
        for row in files
        if row["status"] == "Generated"
        and (
            row["generated_route"]
            or row["generated_route_exception"]
            or row["diagram_kind"]
        )
    ][:80]
    lines.extend(
        _md_example_section(
            "Generated Artifact Examples",
            ["Path", "Route", "Exception", "Kind", "Generator"],
            [
                [
                    f"`{row['path']}`",
                    row["generated_route"] or "",
                    row["generated_route_exception"] or "",
                    row["diagram_kind"] or "",
                    row["generator"] or "",
                ]
                for row in generated_examples
            ],
        )
    )

    issue_examples = [
        row for row in files if str(row["path"]).startswith(GITHUB_ISSUES_PREFIX)
    ][:40]
    lines.extend(
        _md_example_section(
            "GitHub Issue Evidence Examples",
            ["Path", "Lifecycle", "Issue", "Action"],
            [
                [
                    f"`{row['path']}`",
                    row["lifecycle"] or "",
                    row["github_issue_number"] or "",
                    row["recommended_action"],
                ]
                for row in issue_examples
            ],
        )
    )

    docs_reports_examples = [
        row for row in files if str(row["path"]).startswith(DOCS_REPORTS_PREFIX)
    ][:40]
    lines.extend(
        _md_example_section(
            "Docs Reports Evidence Examples",
            ["Path", "Tracking", "Lifecycle", "Action"],
            [
                [
                    f"`{row['path']}`",
                    row["tracking_state"],
                    row["lifecycle"] or "",
                    row["recommended_action"],
                ]
                for row in docs_reports_examples
            ],
        )
    )

    lines.extend(
        _md_example_section(
            "Generated Route Registry",
            ["Route", "Generator", "Commit Policy"],
            [
                [route["id"], f"`{route['generator']}`", route["commit_policy"]]
                for route in generated_routes[:80]
            ],
        )
    )

    lines.extend(
        [
            "",
            "## Verification",
            "",
            "- `python -m scripts.docs generate-cleanup-inventory --check`",
            "- `python -m scripts.docs check-links --links --specs --configs`",
            "- `python -m scripts.docs check-drift --runtime-mirrors --freshness`",
            "",
            "The JSON sibling contains the complete per-file matrix.",
            "",
        ]
    )
    return "\n".join(lines)


def _write_if_changed(path: Path, content: str) -> bool:
    from scripts.engineering.common.repo_paths import REPO_ROOT, resolve_output_path

    safe_path = resolve_output_path(path, root=REPO_ROOT)
    if (
        safe_path.exists() and safe_path.read_text(encoding="utf-8") == content
    ):  # NOSONAR
        return False
    safe_path.parent.mkdir(parents=True, exist_ok=True)
    safe_path.write_text(
        content, encoding="utf-8", newline="\n"
    )  # NOSONAR - confined by resolve_output_path
    return True


def _generated_route_violations(payload: dict[str, Any]) -> list[str]:
    return sorted(
        str(row["path"])
        for row in payload.get("files", [])
        if isinstance(row, dict)
        and row.get("status") == "Generated"
        and not row.get("generated_route")
        and not row.get("generated_route_exception")
    )


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--update", action="store_true", help="Regenerate inventory files."
    )
    mode.add_argument(
        "--check", action="store_true", help="Check generated inventory drift."
    )
    parser.add_argument("--json-output", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--markdown-output", type=Path, default=DEFAULT_MD)
    parser.add_argument("--print-summary", action="store_true")
    return parser.parse_args(argv)


def _rows_by_path(rows: object) -> dict[str, dict[str, Any]]:
    mapping: dict[str, dict[str, Any]] = {}
    if not isinstance(rows, list):
        return mapping
    for row in rows:
        if isinstance(row, dict) and isinstance(row.get("path"), str):
            mapping[str(row["path"])] = row
    return mapping


def _append_diff(lines: list[str], line: str, limit: int) -> bool:
    lines.append(line)
    return len(lines) >= limit


def _collect_path_presence_diffs(
    lines: list[str],
    generated_files: dict[str, dict[str, Any]],
    committed_files: dict[str, dict[str, Any]],
    limit: int,
) -> None:
    for path in sorted(set(generated_files) - set(committed_files)):
        if _append_diff(lines, f"  files[{path}]: generated-only", limit):
            return
    for path in sorted(set(committed_files) - set(generated_files)):
        if _append_diff(lines, f"  files[{path}]: committed-only", limit):
            return


def _collect_mapping_field_diffs(
    lines: list[str],
    left: dict[str, Any],
    right: dict[str, Any],
    *,
    prefix: str,
    limit: int,
) -> None:
    for key in sorted(set(left) | set(right)):
        left_value = left.get(key)
        right_value = right.get(key)
        if left_value != right_value and _append_diff(
            lines,
            f"{prefix}.{key}: generated={left_value!r} committed={right_value!r}",
            limit,
        ):
            return


def _inventory_field_diffs(
    generated: dict[str, Any],
    committed: dict[str, Any],
    *,
    limit: int = 12,
) -> list[str]:
    """Return compact field-level diffs for a stale cleanup-inventory JSON."""
    lines: list[str] = []
    generated_files = _rows_by_path(generated.get("files"))
    committed_files = _rows_by_path(committed.get("files"))
    _collect_path_presence_diffs(lines, generated_files, committed_files, limit)
    if len(lines) < limit:
        for path in sorted(set(generated_files) & set(committed_files)):
            _collect_mapping_field_diffs(
                lines,
                generated_files[path],
                committed_files[path],
                prefix=f"  files[{path}]",
                limit=limit,
            )
            if len(lines) >= limit:
                break
    generated_summary = generated.get("summary")
    committed_summary = committed.get("summary")
    if (
        len(lines) < limit
        and isinstance(generated_summary, dict)
        and isinstance(committed_summary, dict)
    ):
        _collect_mapping_field_diffs(
            lines,
            generated_summary,
            committed_summary,
            prefix="  summary",
            limit=limit,
        )
    return lines


def _json_inventory_field_diffs(
    generated_content: str, on_disk_content: str
) -> list[str]:
    try:
        generated_payload = json.loads(generated_content)
        on_disk_payload = json.loads(on_disk_content)
    except json.JSONDecodeError:
        return ["  [detail] JSON parse failed; compare the inventory files directly"]
    if not isinstance(generated_payload, dict) or not isinstance(on_disk_payload, dict):
        return ["  [detail] JSON root is not an object"]
    diffs = _inventory_field_diffs(generated_payload, on_disk_payload)
    if not diffs:
        return ["  [detail] serialized JSON differs without parsed field changes"]
    return diffs


def _check_inventory_drift(
    *,
    json_output: Path,
    markdown_output: Path,
    json_content: str,
    md_content: str,
) -> tuple[list[str], list[str]]:
    """Return mismatched relative paths and compact JSON field diffs."""
    mismatches: list[str] = []
    details: list[str] = []
    for path, content in (
        (json_output, json_content),
        (markdown_output, md_content),
    ):
        if not path.exists():
            mismatches.append(_repo_relative(path))
            continue
        on_disk = path.read_text(encoding="utf-8")
        if on_disk == content:
            continue
        mismatches.append(_repo_relative(path))
        if path.suffix.lower() == EXT_JSON:
            details.extend(_json_inventory_field_diffs(content, on_disk))
    return mismatches, details


def _print_route_violations(route_violations: list[str]) -> None:
    print("[route-gap] Generated docs without route or exception:")
    for path in route_violations[:20]:
        print(f"  - {path}")
    if len(route_violations) > 20:
        print(f"  ... and {len(route_violations) - 20} more")


def _print_drift_report(mismatches: list[str], details: list[str]) -> None:
    for mismatch in mismatches:
        print(f"[drift] mismatch: {mismatch}")
    for detail in details:
        print(detail)
    print("[hint] run: python -m scripts.docs generate-cleanup-inventory --update")
    print(
        "[hint] markdown link, Owner/Status/Class, or duplicate-body "
        "changes require this refresh before architecture-fast"
    )


def _run_check_mode(
    *,
    json_output: Path,
    markdown_output: Path,
    json_content: str,
    md_content: str,
    payload: dict[str, Any],
) -> int:
    mismatches, details = _check_inventory_drift(
        json_output=json_output,
        markdown_output=markdown_output,
        json_content=json_content,
        md_content=md_content,
    )
    if mismatches:
        _print_drift_report(mismatches, details)
        return 1
    route_violations = _generated_route_violations(payload)
    if route_violations:
        _print_route_violations(route_violations)
        print("[hint] add a route to configs/quality/generated_artifact_routing.yaml")
        return 1
    print("[documentation-cleanup-inventory] inventory is synchronized")
    return 0


def _run_update_mode(
    *,
    json_output: Path,
    markdown_output: Path,
    json_content: str,
    md_content: str,
) -> int:
    changed = [
        _write_if_changed(json_output, json_content),
        _write_if_changed(markdown_output, md_content),
    ]
    if any(changed):
        print("[documentation-cleanup-inventory] inventory updated")
    else:
        print("[documentation-cleanup-inventory] inventory already synchronized")
    return 0


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    payload = _build_inventory()
    json_content = (
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    )
    md_content = _render_markdown(payload)
    if args.print_summary:
        print(
            json.dumps(payload["summary"], ensure_ascii=False, indent=2, sort_keys=True)
        )
    if args.check:
        return _run_check_mode(
            json_output=args.json_output,
            markdown_output=args.markdown_output,
            json_content=json_content,
            md_content=md_content,
            payload=payload,
        )
    return _run_update_mode(
        json_output=args.json_output,
        markdown_output=args.markdown_output,
        json_content=json_content,
        md_content=md_content,
    )


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
