"""Protocol definitions for CompositeConfig serialization."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Protocol

from bioetl.domain.composite.aggregation import (
    AggregationFunction,
    EnricherCardinality,
)
from bioetl.domain.composite.cross_validation import ComparisonMethod
from bioetl.domain.composite.strategy import (
    ConflictResolution,
    FallbackStrategy,
    MergeStrategy,
)

__all__ = ["CompositeConfigProtocol"]


class _SeedConfigProtocol(Protocol):
    @property
    def pipeline(self) -> str: ...
    @property
    def output_keys(self) -> tuple[str, ...]: ...
    @property
    def silver_table(self) -> str: ...
    @property
    def limit(self) -> int | None: ...


class _DependencyConfigProtocol(Protocol):
    @property
    def pipeline(self) -> str: ...
    @property
    def join_keys(self) -> tuple[str, ...]: ...
    @property
    def required(self) -> bool: ...
    @property
    def timeout_seconds(self) -> int: ...
    @property
    def silver_table(self) -> str | None: ...
    @property
    def key_source(self) -> str | None: ...
    @property
    def filter_field(self) -> str | None: ...
    @property
    def filter_fields(self) -> tuple[str, ...] | None: ...
    @property
    def key_filter(self) -> str | None: ...


class _AggregationFieldProtocol(Protocol):
    @property
    def source_field(self) -> str: ...
    @property
    def agg_function(self) -> AggregationFunction: ...
    @property
    def filter_condition(self) -> str | None: ...
    @property
    def output_field(self) -> str | None: ...


class _AggregationConfigProtocol(Protocol):
    @property
    def group_by(self) -> str: ...
    @property
    def order_by(self) -> tuple[str, ...]: ...
    @property
    def fields(self) -> Sequence[_AggregationFieldProtocol]: ...


class _EnricherConfigProtocol(Protocol):
    @property
    def pipeline(self) -> str: ...
    @property
    def join_keys(self) -> tuple[str, ...]: ...
    @property
    def required(self) -> bool: ...
    @property
    def timeout_seconds(self) -> int: ...
    @property
    def filter_condition(self) -> str | None: ...
    @property
    def silver_table(self) -> str | None: ...
    @property
    def limit(self) -> int | None: ...
    @property
    def fallback_strategy(self) -> FallbackStrategy: ...
    @property
    def cardinality(self) -> EnricherCardinality: ...
    @property
    def aggregation(self) -> _AggregationConfigProtocol | None: ...


class _ColumnGroupProtocol(Protocol):
    @property
    def name(self) -> str:
        """Column-group identifier."""
        ...

    @property
    def fields(self) -> tuple[str, ...]: ...
    @property
    def pattern(self) -> str | None: ...
    @property
    def provider_order(self) -> tuple[str, ...]: ...


class _MergeConfigProtocol(Protocol):
    @property
    def strategy(self) -> MergeStrategy: ...
    @property
    def conflict_resolution(self) -> ConflictResolution: ...
    @property
    def output_silver_path(self) -> str: ...
    @property
    def output_gold_path(self) -> str: ...
    @property
    def sort_by_silver(self) -> tuple[str, ...]: ...
    @property
    def sort_by_gold(self) -> tuple[str, ...]: ...
    @property
    def field_priorities(self) -> Mapping[str, tuple[str, ...]]: ...
    @property
    def normalization_compatibility_overrides(self) -> Mapping[str, str]: ...
    @property
    def field_mappings(self) -> Mapping[str, str]: ...
    @property
    def column_groups(self) -> Sequence[_ColumnGroupProtocol]: ...
    @property
    def exclude_fields(self) -> tuple[str, ...]: ...
    @property
    def preserve_all_sources(self) -> bool: ...


class _DQOverrideProtocol(Protocol):
    @property
    def soft_fail_threshold(self) -> float | None: ...
    @property
    def hard_fail_threshold(self) -> float | None: ...


class _DQConfigProtocol(Protocol):
    @property
    def soft_fail_threshold(self) -> float: ...
    @property
    def hard_fail_threshold(self) -> float: ...
    @property
    def required_fields(self) -> tuple[str, ...]: ...
    @property
    def enricher_overrides(self) -> Mapping[str, _DQOverrideProtocol]: ...


class _ExecutionConfigProtocol(Protocol):
    @property
    def max_concurrency(self) -> int: ...
    @property
    def checkpoint_enabled(self) -> bool: ...
    @property
    def retry_max_attempts(self) -> int: ...
    @property
    def retry_backoff_multiplier(self) -> float: ...


class _LineageConfigProtocol(Protocol):
    @property
    def track_field_sources(self) -> bool: ...
    @property
    def track_timestamps(self) -> bool: ...
    @property
    def track_status(self) -> bool: ...
    @property
    def provider_lookup_fields(self) -> Mapping[str, Mapping[str, str]]: ...
    @property
    def track_source_for_fields(self) -> tuple[str, ...]: ...


class _FieldComparisonProtocol(Protocol):
    @property
    def field_name(self) -> str: ...
    @property
    def method(self) -> ComparisonMethod: ...
    @property
    def threshold(self) -> float: ...


class _EnricherPairingProtocol(Protocol):
    @property
    def enricher_pipeline(self) -> str: ...
    @property
    def fields(self) -> Sequence[_FieldComparisonProtocol]: ...


class _CrossValidationConfigProtocol(Protocol):
    @property
    def enabled(self) -> bool: ...
    @property
    def warning_threshold(self) -> int: ...
    @property
    def error_threshold(self) -> int: ...
    @property
    def quarantine_threshold(self) -> int: ...
    @property
    def fuzzy_threshold(self) -> float: ...
    @property
    def numeric_tolerance(self) -> float: ...
    @property
    def enricher_pairings(self) -> Sequence[_EnricherPairingProtocol]: ...


class CompositeConfigProtocol(Protocol):
    @property
    def name(self) -> str:
        """Composite pipeline name."""
        ...

    @property
    def version(self) -> str:
        """Composite configuration version."""
        ...

    @property
    def seed(self) -> _SeedConfigProtocol:
        """Seed pipeline configuration for the composite."""
        ...

    @property
    def dependencies(self) -> Sequence[_DependencyConfigProtocol]:
        """Dependency pipeline configurations."""
        ...

    @property
    def enrichers(self) -> Sequence[_EnricherConfigProtocol]:
        """Enricher pipeline configurations."""
        ...

    @property
    def merge(self) -> _MergeConfigProtocol:
        """Merge and field-priority configuration."""
        ...

    @property
    def dq(self) -> _DQConfigProtocol:
        """Composite data-quality thresholds."""
        ...

    @property
    def execution(self) -> _ExecutionConfigProtocol:
        """Composite execution/retry configuration."""
        ...

    @property
    def lineage(self) -> _LineageConfigProtocol:
        """Composite lineage tracking configuration."""
        ...

    @property
    def cross_validation(self) -> _CrossValidationConfigProtocol:
        """Cross-validation pairing configuration."""
        ...
