"""Silver layer schema facade.

Re-exports all Silver PyArrow schemas while keeping a stable import path:
`bioetl.infrastructure.schemas.silver`.
"""

from __future__ import annotations

from bioetl.infrastructure.schemas.silver_chembl import (
    CHEMBL_ACTIVITY_SCHEMA,
    CHEMBL_ASSAY_PARAMETERS_SCHEMA,
    CHEMBL_ASSAY_SCHEMA,
    CHEMBL_CELL_LINE_SCHEMA,
    CHEMBL_COMPOUND_RECORD_SCHEMA,
    CHEMBL_DOCUMENT_SIMILARITY_SCHEMA,
    CHEMBL_DOCUMENT_TERM_SCHEMA,
    CHEMBL_MOLECULE_SCHEMA,
    CHEMBL_PROTEIN_CLASS_SCHEMA,
    CHEMBL_PUBLICATION_SCHEMA,
    CHEMBL_SUBCELLULAR_FRACTION_SCHEMA,
    CHEMBL_TARGET_COMPONENT_SCHEMA,
    CHEMBL_TARGET_PROTEIN_CLASSIFICATION_SCHEMA,
    CHEMBL_TARGET_SCHEMA,
    CHEMBL_TISSUE_SCHEMA,
)
from bioetl.infrastructure.schemas.silver_compounds import (
    PUBCHEM_COMPOUND_SCHEMA,
    UNIPROT_ID_MAPPING_SCHEMA,
    UNIPROT_PROTEIN_SCHEMA,
)
from bioetl.infrastructure.schemas.silver_publications import (
    CROSSREF_PUBLICATION_SCHEMA,
    OPENALEX_PUBLICATION_SCHEMA,
    PUBMED_PUBLICATION_SCHEMA,
    SEMANTICSCHOLAR_PUBLICATION_SCHEMA,
)

__all__ = [
    "CHEMBL_ACTIVITY_SCHEMA",
    "CHEMBL_ASSAY_PARAMETERS_SCHEMA",
    "CHEMBL_ASSAY_SCHEMA",
    "CHEMBL_CELL_LINE_SCHEMA",
    "CHEMBL_COMPOUND_RECORD_SCHEMA",
    "CHEMBL_DOCUMENT_SIMILARITY_SCHEMA",
    "CHEMBL_DOCUMENT_TERM_SCHEMA",
    "CHEMBL_MOLECULE_SCHEMA",
    "CHEMBL_PROTEIN_CLASS_SCHEMA",
    "CHEMBL_PUBLICATION_SCHEMA",
    "CHEMBL_SUBCELLULAR_FRACTION_SCHEMA",
    "CHEMBL_TARGET_COMPONENT_SCHEMA",
    "CHEMBL_TARGET_PROTEIN_CLASSIFICATION_SCHEMA",
    "CHEMBL_TARGET_SCHEMA",
    "CHEMBL_TISSUE_SCHEMA",
    "CROSSREF_PUBLICATION_SCHEMA",
    "OPENALEX_PUBLICATION_SCHEMA",
    "PUBCHEM_COMPOUND_SCHEMA",
    "PUBMED_PUBLICATION_SCHEMA",
    "SEMANTICSCHOLAR_PUBLICATION_SCHEMA",
    "UNIPROT_ID_MAPPING_SCHEMA",
    "UNIPROT_PROTEIN_SCHEMA",
]
