"""AUTO-GENERATED FILE. DO NOT EDIT MANUALLY."""

from __future__ import annotations

import pyarrow as pa

CHEMBL_ACTIVITY_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("action_type", pa.string()),
        pa.field("action_type_description", pa.string()),
        pa.field("action_type_parent_type", pa.string()),
        pa.field("activity_comment", pa.string()),
        pa.field("activity_id", pa.string()),
        pa.field("activity_properties", pa.string()),
        pa.field("assay_id", pa.string()),
        pa.field("assay_description", pa.string()),
        pa.field("assay_type", pa.string()),
        pa.field("assay_variant_accession", pa.string()),
        pa.field("assay_variant_mutation", pa.string()),
        pa.field("bao_endpoint", pa.string()),
        pa.field("bao_format", pa.string()),
        pa.field("bao_label", pa.string()),
        pa.field("canonical_smiles", pa.string()),
        pa.field("data_validity_comment", pa.string()),
        pa.field("data_validity_description", pa.string()),
        pa.field("publication_id", pa.string()),
        pa.field("journal", pa.string()),
        pa.field("publication_year", pa.int64()),
        pa.field("ligand_efficiency_bei", pa.float64()),
        pa.field("ligand_efficiency_le", pa.float64()),
        pa.field("ligand_efficiency_lle", pa.float64()),
        pa.field("ligand_efficiency_sei", pa.float64()),
        pa.field("manual_curation_flag", pa.float64()),
        pa.field("molecule_id", pa.string()),
        pa.field("molecule_pref_name", pa.string()),
        pa.field("original_activity_id", pa.float64()),
        pa.field("parent_molecule_id", pa.string()),
        pa.field("pchembl_value", pa.float64()),
        pa.field("potential_duplicate", pa.int64()),
        pa.field("qudt_units", pa.string()),
        pa.field("record_id", pa.int64()),
        pa.field("relation", pa.string()),
        pa.field("src_id", pa.int64()),
        pa.field("standard_flag", pa.int64()),
        pa.field("standard_relation", pa.string()),
        pa.field("standard_text_value", pa.string()),
        pa.field("standard_type", pa.string()),
        pa.field("standard_units", pa.string()),
        pa.field("standard_upper_value", pa.float64()),
        pa.field("standard_value", pa.float64()),
        pa.field("target_id", pa.string()),
        pa.field("target_organism", pa.string()),
        pa.field("target_pref_name", pa.string()),
        pa.field("target_taxonomy_id", pa.float64()),
        pa.field("text_value", pa.string()),
        pa.field("toid", pa.float64()),
        pa.field("type", pa.string()),
        pa.field("units", pa.string()),
        pa.field("uo_units", pa.string()),
        pa.field("upper_value", pa.float64()),
        pa.field("value", pa.float64()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

CHEMBL_ASSAY_PARAMETERS_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("assay_id", pa.string()),
        pa.field("assay_param_id", pa.int64()),
        pa.field("comments", pa.string()),
        pa.field("relation", pa.string()),
        pa.field("standard_relation", pa.string()),
        pa.field("standard_text_value", pa.string()),
        pa.field("standard_type", pa.string()),
        pa.field("standard_units", pa.string()),
        pa.field("standard_value", pa.float64()),
        pa.field("text_value", pa.string()),
        pa.field("type", pa.string()),
        pa.field("units", pa.string()),
        pa.field("value", pa.float64()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

CHEMBL_ASSAY_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("aidx", pa.string()),
        pa.field("assay_category", pa.string()),
        pa.field("assay_cell_type", pa.string()),
        pa.field("assay_id", pa.string()),
        pa.field("assay_classifications", pa.string()),
        pa.field("assay_group", pa.string()),
        pa.field("assay_organism", pa.string()),
        pa.field("assay_parameters", pa.string()),
        pa.field("assay_pref_name", pa.string()),
        pa.field("assay_strain", pa.string()),
        pa.field("assay_subcellular_fraction", pa.string()),
        pa.field("assay_taxonomy_id", pa.float64()),
        pa.field("assay_test_type", pa.string()),
        pa.field("assay_tissue", pa.string()),
        pa.field("assay_type", pa.string()),
        pa.field("assay_type_description", pa.string()),
        pa.field("bao_format", pa.string()),
        pa.field("bao_label", pa.string()),
        pa.field("cell_id", pa.string()),
        pa.field("confidence_description", pa.string()),
        pa.field("confidence_score", pa.int64()),
        pa.field("description", pa.string()),
        pa.field("publication_id", pa.string()),
        pa.field("relationship_description", pa.string()),
        pa.field("relationship_type", pa.string()),
        pa.field("score", pa.float64()),
        pa.field("src_assay_id", pa.string()),
        pa.field("src_id", pa.int64()),
        pa.field("target_id", pa.string()),
        pa.field("tissue_id", pa.string()),
        pa.field("variant_accession", pa.string()),
        pa.field("variant_isoform", pa.string()),
        pa.field("variant_mutation", pa.string()),
        pa.field("variant_organism", pa.string()),
        pa.field("variant_sequence", pa.string()),
        pa.field("variant_sequence_json", pa.string()),
        pa.field("variant_taxonomy_id", pa.float64()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

CHEMBL_CELL_LINE_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("cell_id", pa.string()),
        pa.field("cell_description", pa.string()),
        pa.field("cell_name", pa.string()),
        pa.field("cell_source_organism", pa.string()),
        pa.field("cell_source_tissue", pa.string()),
        pa.field("cellosaurus_id", pa.string()),
        pa.field("cl_lincs_id", pa.string()),
        pa.field("efo_id", pa.string()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

CHEMBL_COMPOUND_RECORD_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("compound_key", pa.string()),
        pa.field("compound_name", pa.string()),
        pa.field("publication_id", pa.string()),
        pa.field("molecule_id", pa.string()),
        pa.field("record_id", pa.int64()),
        pa.field("src_compound_id", pa.string()),
        pa.field("src_id", pa.int64()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

CHEMBL_DOCUMENT_SIMILARITY_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("avg_tani", pa.float64()),
        pa.field("doc_1", pa.int64()),
        pa.field("doc_2", pa.int64()),
        pa.field("max_tani", pa.float64()),
        pa.field("mol_tani", pa.float64()),
        pa.field("pubmed_id1", pa.string()),
        pa.field("pubmed_id2", pa.string()),
        pa.field("sim_id", pa.int64()),
        pa.field("tid_tani", pa.float64()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

CHEMBL_DOCUMENT_TERM_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("publication_id", pa.string()),
        pa.field("mesh_id", pa.string()),
        pa.field("qualifier", pa.string()),
        pa.field("term", pa.string()),
        pa.field("term_type", pa.string()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

CHEMBL_MOLECULE_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("atc_classifications", pa.string()),
        pa.field("availability_type", pa.float64()),
        pa.field("black_box_warning", pa.int64()),
        pa.field("canonical_smiles", pa.string()),
        pa.field("chirality", pa.int64()),
        pa.field("cross_references", pa.string()),
        pa.field("dosed_ingredient", pa.int64()),
        pa.field("first_approval", pa.float64()),
        pa.field("first_in_class", pa.int64()),
        pa.field("helm_notation", pa.string()),
        pa.field("hierarchy_active_chembl_id", pa.string()),
        pa.field("hierarchy_child_chembl_id", pa.string()),
        pa.field("hierarchy_parent_chembl_id", pa.string()),
        pa.field("inchi_key", pa.string()),
        pa.field("inorganic_flag", pa.int64()),
        pa.field("max_phase", pa.int64()),
        pa.field("molecule_id", pa.string()),
        pa.field("molecule_hierarchy", pa.string()),
        pa.field("molecule_properties", pa.string()),
        pa.field("molecule_species", pa.string()),
        pa.field("molecule_structures", pa.string()),
        pa.field("molecule_synonyms", pa.string()),
        pa.field("molecule_type", pa.string()),
        pa.field("natural_product", pa.int64()),
        pa.field("oral", pa.bool_()),
        pa.field("parenteral", pa.bool_()),
        pa.field("polymer_flag", pa.int64()),
        pa.field("pref_name", pa.string()),
        pa.field("prodrug", pa.int64()),
        pa.field("aromatic_ring_count", pa.int64()),
        pa.field("hba_count", pa.int64()),
        pa.field("hbd_count", pa.int64()),
        pa.field("heavy_atom_count", pa.int64()),
        pa.field("logp", pa.float64()),
        pa.field("logp_method", pa.string()),
        pa.field("molecular_formula", pa.string()),
        pa.field("molecular_weight", pa.float64()),
        pa.field("mw_freebase", pa.float64()),
        pa.field("polar_surface_area", pa.float64()),
        pa.field("qed_score", pa.float64()),
        pa.field("ro3_pass", pa.string()),
        pa.field("ro5_violation_count", pa.int64()),
        pa.field("rotatable_bond_count", pa.int64()),
        pa.field("standard_inchi", pa.string()),
        pa.field("structure_type", pa.string()),
        pa.field("therapeutic_flag", pa.bool_()),
        pa.field("topical", pa.bool_()),
        pa.field("usan_stem", pa.string()),
        pa.field("usan_stem_definition", pa.string()),
        pa.field("usan_substem", pa.string()),
        pa.field("usan_year", pa.float64()),
        pa.field("withdrawn_flag", pa.bool_()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

CHEMBL_PROTEIN_CLASS_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("class_level", pa.int64()),
        pa.field("definition", pa.string()),
        pa.field("downgraded", pa.int64()),
        pa.field("parent_id", pa.int64()),
        pa.field("pref_name", pa.string()),
        pa.field("protein_class_desc", pa.string()),
        pa.field("protein_class_id", pa.int64()),
        pa.field("replaced_by", pa.int64()),
        pa.field("short_name", pa.string()),
        pa.field("sort_order", pa.int64()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

CHEMBL_PUBLICATION_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_source", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("_lookup_method", pa.string()),
        pa.field("_original_id", pa.string()),
        pa.field("authors", pa.string()),
        pa.field("title", pa.string()),
        pa.field("journal", pa.string()),
        pa.field("publication_year", pa.int64()),
        pa.field("volume", pa.string()),
        pa.field("issue", pa.string()),
        pa.field("page_first", pa.string()),
        pa.field("page_last", pa.string()),
        pa.field("publication_id", pa.string()),
        pa.field("doi", pa.string()),
        pa.field("pmc_id", pa.string()),
        pa.field("pmid", pa.string()),
        pa.field("abstract", pa.string()),
        pa.field("affiliation_list", pa.string()),
        pa.field("author_keys", pa.string()),
        pa.field("author_orcids", pa.string()),
        pa.field("publication_type", pa.string()),
        pa.field("publication_class", pa.string()),
        pa.field("is_oa", pa.bool_()),
        pa.field("src_id", pa.int64()),
        pa.field("citations_received", pa.int64()),
        pa.field("chembl_release", pa.string()),
        pa.field("creation_date", pa.string()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

CHEMBL_SUBCELLULAR_FRACTION_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("assay_count", pa.int64()),
        pa.field("example_assay_id", pa.string()),
        pa.field("subcellular_fraction", pa.string()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

CHEMBL_TARGET_COMPONENT_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("accession", pa.string()),
        pa.field("component_id", pa.int64()),
        pa.field("component_type", pa.string()),
        pa.field("description", pa.string()),
        pa.field("organism", pa.string()),
        pa.field("protein_classification_id", pa.int64()),
        pa.field("protein_classifications", pa.string()),
        pa.field("target_component_synonyms", pa.string()),
        pa.field("target_component_xrefs", pa.string()),
        pa.field("taxonomy_id", pa.int64()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

CHEMBL_TARGET_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("cross_references", pa.string()),
        pa.field("description", pa.string()),
        pa.field("downgraded", pa.bool_()),
        pa.field("organism", pa.string()),
        pa.field("pipeline_stages", pa.string()),
        pa.field("pref_name", pa.string()),
        pa.field("primary_component_id", pa.float64()),
        pa.field("species_group_flag", pa.bool_()),
        pa.field("target_component_synonyms", pa.string()),
        pa.field("target_components", pa.string()),
        pa.field("target_id", pa.string()),
        pa.field("target_type", pa.string()),
        pa.field("taxonomy_id", pa.float64()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

CHEMBL_TISSUE_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("bto_id", pa.string()),
        pa.field("caloha_id", pa.string()),
        pa.field("efo_id", pa.string()),
        pa.field("pref_name", pa.string()),
        pa.field("tissue_id", pa.string()),
        pa.field("uberon_id", pa.string()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

CROSSREF_PUBLICATION_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_source", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("_lookup_method", pa.string()),
        pa.field("_original_id", pa.string()),
        pa.field("abstract", pa.string()),
        pa.field("author_details", pa.string()),
        pa.field("author_keys", pa.string()),
        pa.field("author_orcids", pa.string()),
        pa.field("authors", pa.string()),
        pa.field("citations_made", pa.int64()),
        pa.field("content_domain_crossmark_restriction", pa.bool_()),
        pa.field("doi", pa.string()),
        pa.field("issn", pa.string()),
        pa.field("issn_electronic", pa.string()),
        pa.field("issn_list", pa.string()),
        pa.field("issn_print", pa.string()),
        pa.field("issue", pa.string()),
        pa.field("journal", pa.string()),
        pa.field("journal_name_short", pa.string()),
        pa.field("language", pa.string()),
        pa.field("license_url", pa.string()),
        pa.field("page_first", pa.string()),
        pa.field("page_last", pa.string()),
        pa.field("pmc_id", pa.string()),
        pa.field("pmid", pa.string()),
        pa.field("publication_class", pa.string()),
        pa.field("publication_date", pa.string()),
        pa.field("publication_year", pa.int64()),
        pa.field("published", pa.string()),
        pa.field("published_online", pa.string()),
        pa.field("published_print", pa.string()),
        pa.field("publisher", pa.string()),
        pa.field("references", pa.string()),
        pa.field("title", pa.string()),
        pa.field("volume", pa.string()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

OPENALEX_PUBLICATION_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_source", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("_lookup_method", pa.string()),
        pa.field("_original_id", pa.string()),
        pa.field("abstract", pa.string()),
        pa.field("affiliation_list", pa.string()),
        pa.field("author_keys", pa.string()),
        pa.field("author_openalex_ids", pa.string()),
        pa.field("author_orcids", pa.string()),
        pa.field("authors", pa.string()),
        pa.field("citations_made", pa.int64()),
        pa.field("citations_received", pa.int64()),
        pa.field("doi", pa.string()),
        pa.field("fwci", pa.float64()),
        pa.field("grants", pa.string()),
        pa.field("is_oa", pa.bool_()),
        pa.field("is_retracted", pa.bool_()),
        pa.field("issn", pa.string()),
        pa.field("issue", pa.string()),
        pa.field("journal", pa.string()),
        pa.field("language", pa.string()),
        pa.field("mag_id", pa.string()),
        pa.field("oa_status", pa.string()),
        pa.field("openalex_id", pa.string()),
        pa.field("page_first", pa.string()),
        pa.field("page_last", pa.string()),
        pa.field("pmc_id", pa.string()),
        pa.field("pmid", pa.string()),
        pa.field("primary_topic", pa.string()),
        pa.field("publication_class", pa.string()),
        pa.field("publication_date", pa.string()),
        pa.field("publication_year", pa.int64()),
        pa.field("publisher", pa.string()),
        pa.field("ror_ids", pa.string()),
        pa.field("subject_topics", pa.string()),
        pa.field("title", pa.string()),
        pa.field("volume", pa.string()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

PUBCHEM_COMPOUND_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("canonical_smiles", pa.string()),
        pa.field("molecule_id", pa.string()),
        pa.field("complexity", pa.float64()),
        pa.field("conformer_count_3d", pa.float64()),
        pa.field("conformer_rmsd_3d", pa.float64()),
        pa.field("effective_rotor_count_3d", pa.float64()),
        pa.field("exact_mass", pa.float64()),
        pa.field("feature_acceptor_count_3d", pa.float64()),
        pa.field("feature_anion_count_3d", pa.float64()),
        pa.field("feature_cation_count_3d", pa.float64()),
        pa.field("feature_count_3d", pa.float64()),
        pa.field("feature_donor_count_3d", pa.float64()),
        pa.field("feature_hydrophobe_count_3d", pa.float64()),
        pa.field("feature_ring_count_3d", pa.float64()),
        pa.field("inchi", pa.string()),
        pa.field("inchi_key", pa.string()),
        pa.field("isomeric_smiles", pa.string()),
        pa.field("iupac_name", pa.string()),
        pa.field("molecular_formula", pa.string()),
        pa.field("molecular_weight", pa.float64()),
        pa.field("monoisotopic_mass", pa.float64()),
        pa.field("tpsa", pa.float64()),
        pa.field("x_steric_quadrupole_3d", pa.float64()),
        pa.field("xlogp", pa.float64()),
        pa.field("y_steric_quadrupole_3d", pa.float64()),
        pa.field("z_steric_quadrupole_3d", pa.float64()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

PUBMED_PUBLICATION_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_source", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("_lookup_method", pa.string()),
        pa.field("_original_id", pa.string()),
        pa.field("abstract", pa.string()),
        pa.field("affiliation_list", pa.string()),
        pa.field("affiliation_structured", pa.string()),
        pa.field("author_count", pa.int64()),
        pa.field("author_keys", pa.string()),
        pa.field("authors", pa.string()),
        pa.field("authors_with_affiliations", pa.string()),
        pa.field("chemical_count", pa.int64()),
        pa.field("chemicals", pa.string()),
        pa.field("citation_subset", pa.string()),
        pa.field("citations_made", pa.int64()),
        pa.field("country", pa.string()),
        pa.field("databanks", pa.string()),
        pa.field("date_completed", pa.string()),
        pa.field("date_revised", pa.string()),
        pa.field("doi", pa.string()),
        pa.field("gene_symbols", pa.string()),
        pa.field("grant_count", pa.int64()),
        pa.field("issn", pa.string()),
        pa.field("issue", pa.string()),
        pa.field("journal", pa.string()),
        pa.field("journal_iso_abbrev", pa.string()),
        pa.field("journal_issn_type", pa.string()),
        pa.field("journal_name_short", pa.string()),
        pa.field("keyword_count", pa.int64()),
        pa.field("language", pa.string()),
        pa.field("medline_pgn", pa.string()),
        pa.field("mesh_heading_count", pa.int64()),
        pa.field("nlm_unique_id", pa.string()),
        pa.field("page_first", pa.string()),
        pa.field("page_last", pa.string()),
        pa.field("page_range", pa.string()),
        pa.field("pmc_id", pa.string()),
        pa.field("pmid", pa.string()),
        pa.field("pub_date", pa.string()),
        pa.field("pub_day", pa.int64()),
        pa.field("pub_month", pa.int64()),
        pa.field("publication_class", pa.string()),
        pa.field("publication_date", pa.string()),
        pa.field("publication_status", pa.string()),
        pa.field("publication_type", pa.string()),
        pa.field("publication_type_list", pa.string()),
        pa.field("publication_year", pa.int64()),
        pa.field("title", pa.string()),
        pa.field("volume", pa.string()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

SEMANTICSCHOLAR_PUBLICATION_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_source", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("_lookup_method", pa.string()),
        pa.field("_original_id", pa.string()),
        pa.field("abstract", pa.string()),
        pa.field("affiliation_list", pa.string()),
        pa.field("author_h_indices", pa.string()),
        pa.field("author_keys", pa.string()),
        pa.field("author_orcids", pa.string()),
        pa.field("author_s2_ids", pa.string()),
        pa.field("citation_contexts", pa.string()),
        pa.field("citations_made", pa.int64()),
        pa.field("citations_received", pa.int64()),
        pa.field("corpus_id", pa.int64()),
        pa.field("dblp_id", pa.string()),
        pa.field("doi", pa.string()),
        pa.field("influential_citation_count", pa.int64()),
        pa.field("is_oa", pa.bool_()),
        pa.field("issue", pa.string()),
        pa.field("journal", pa.string()),
        pa.field("oa_status", pa.string()),
        pa.field("open_access_url", pa.string()),
        pa.field("page_first", pa.string()),
        pa.field("page_last", pa.string()),
        pa.field("page_range", pa.string()),
        pa.field("paper_id", pa.string()),
        pa.field("pmid", pa.string()),
        pa.field("publication_class", pa.string()),
        pa.field("publication_date", pa.string()),
        pa.field("publication_types", pa.string()),
        pa.field("publication_year", pa.int64()),
        pa.field("subject_fields", pa.string()),
        pa.field("title", pa.string()),
        pa.field("tldr", pa.string()),
        pa.field("volume", pa.string()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

UNIPROT_ID_MAPPING_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("all_mappings", pa.string()),
        pa.field("annotation_score", pa.int64()),
        pa.field("gene_primary", pa.string()),
        pa.field("mapping_status", pa.string()),
        pa.field("organism_common", pa.string()),
        pa.field("organism_scientific", pa.string()),
        pa.field("protein_name", pa.string()),
        pa.field("reviewed", pa.bool_()),
        pa.field("sequence_length", pa.int64()),
        pa.field("sequence_mass", pa.int64()),
        pa.field("target_id", pa.string()),
        pa.field("taxonomy_id", pa.int64()),
        pa.field("uniprot_accession", pa.string()),
        pa.field("uniprot_entry_name", pa.string()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)

UNIPROT_PROTEIN_SCHEMA = pa.schema(
    [
        pa.field("entity_id", pa.string()),
        pa.field("content_hash", pa.string()),
        pa.field("_run_id", pa.string()),
        pa.field("_run_type", pa.string()),
        pa.field("_source_batch_id", pa.string()),
        pa.field("_ingestion_ts", pa.string()),
        pa.field("_index", pa.int64()),
        pa.field("accession", pa.string()),
        pa.field("acetylation", pa.string()),
        pa.field("active_sites", pa.string()),
        pa.field("activity_regulation", pa.string()),
        pa.field("annotation_score", pa.int64()),
        pa.field("binding_sites", pa.string()),
        pa.field("catalytic_activity", pa.string()),
        pa.field("cellular_component", pa.string()),
        pa.field("chembl_ids", pa.string()),
        pa.field("disease_involvement", pa.string()),
        pa.field("disulfide_bond", pa.string()),
        pa.field("domains", pa.string()),
        pa.field("drugbank_ids", pa.string()),
        pa.field("entry_name", pa.string()),
        pa.field("features_json", pa.string()),
        pa.field("function_comment", pa.string()),
        pa.field("genus", pa.string()),
        pa.field("glycosylation", pa.string()),
        pa.field("go_terms", pa.string()),
        pa.field("interpro_xrefs", pa.string()),
        pa.field("intramembrane", pa.string()),
        pa.field("isoform_ids", pa.string()),
        pa.field("isoform_names", pa.string()),
        pa.field("isoform_synonyms", pa.string()),
        pa.field("lipidation", pa.string()),
        pa.field("modified_residue", pa.string()),
        pa.field("molecular_function", pa.string()),
        pa.field("organism_id", pa.int64()),
        pa.field("pathway", pa.string()),
        pa.field("pdb_xrefs", pa.string()),
        pa.field("pfam_xrefs", pa.string()),
        pa.field("phosphorylation", pa.string()),
        pa.field("phylum", pa.string()),
        pa.field("propeptide", pa.string()),
        pa.field("protein_existence", pa.string()),
        pa.field("protein_name", pa.string()),
        pa.field("reaction_ec_numbers", pa.string()),
        pa.field("reactions", pa.string()),
        pa.field("reactome_xrefs", pa.string()),
        pa.field("reviewed", pa.bool_()),
        pa.field("sequence_length", pa.int64()),
        pa.field("signal_peptide", pa.string()),
        pa.field("similarity_comment", pa.string()),
        pa.field("subcellular_location", pa.string()),
        pa.field("superkingdom", pa.string()),
        pa.field("tissue_specificity", pa.string()),
        pa.field("topology", pa.string()),
        pa.field("transmembrane", pa.string()),
        pa.field("ubiquitination", pa.string()),
        pa.field("_dq_error", pa.bool_()),
        pa.field("_dq_warn", pa.bool_()),
    ]
)
