"""ChEMBL Silver layer schemas facade."""

from __future__ import annotations

from bioetl.infrastructure.schemas.silver_chembl_core import (
    CHEMBL_ACTIVITY_SCHEMA,
    CHEMBL_ASSAY_SCHEMA,
    CHEMBL_CELL_LINE_SCHEMA,
    CHEMBL_PUBLICATION_SCHEMA,
    CHEMBL_SUBCELLULAR_FRACTION_SCHEMA,
    CHEMBL_TARGET_COMPONENT_SCHEMA,
    CHEMBL_TARGET_PROTEIN_CLASSIFICATION_SCHEMA,
    CHEMBL_TARGET_SCHEMA,
    CHEMBL_TISSUE_SCHEMA,
)
from bioetl.infrastructure.schemas.silver_chembl_extended import (
    CHEMBL_ASSAY_PARAMETERS_SCHEMA,
    CHEMBL_COMPOUND_RECORD_SCHEMA,
    CHEMBL_DOCUMENT_SIMILARITY_SCHEMA,
    CHEMBL_DOCUMENT_TERM_SCHEMA,
    CHEMBL_MOLECULE_SCHEMA,
    CHEMBL_PROTEIN_CLASS_SCHEMA,
)

__all__ = [
    "CHEMBL_ACTIVITY_SCHEMA",
    "CHEMBL_ASSAY_PARAMETERS_SCHEMA",
    "CHEMBL_ASSAY_SCHEMA",
    "CHEMBL_CELL_LINE_SCHEMA",
    "CHEMBL_COMPOUND_RECORD_SCHEMA",
    "CHEMBL_DOCUMENT_SIMILARITY_SCHEMA",
    "CHEMBL_DOCUMENT_TERM_SCHEMA",
    "CHEMBL_MOLECULE_SCHEMA",
    "CHEMBL_PROTEIN_CLASS_SCHEMA",
    "CHEMBL_PUBLICATION_SCHEMA",
    "CHEMBL_SUBCELLULAR_FRACTION_SCHEMA",
    "CHEMBL_TARGET_COMPONENT_SCHEMA",
    "CHEMBL_TARGET_PROTEIN_CLASSIFICATION_SCHEMA",
    "CHEMBL_TARGET_SCHEMA",
    "CHEMBL_TISSUE_SCHEMA",
]
