apiVersion: 1

datasources:
  - name: Quarantine Explorer
    type: yesoreyeram-infinity-datasource
    uid: quarantine-explorer
    access: proxy
    url: ${BIOETL_QUARANTINE_EXPLORER_URL:-http://host.docker.internal:8081}
    editable: true
    jsonData:
      allowedHosts:
        - ${BIOETL_QUARANTINE_EXPLORER_URL:-http://host.docker.internal:8081}
      auth_method: none
