"""Built-in transformer specification rows for factory registration."""

from __future__ import annotations

from typing import Final

TransformerSpecRow = tuple[str, str, str, str]

BUILTIN_TRANSFORMER_SPEC_ROWS: Final[tuple[TransformerSpecRow, ...]] = (
    (
        "chembl",
        "activity",
        "bioetl.application.pipelines.chembl.activity_transformer",
        "ActivityTransformer",
    ),
    (
        "chembl",
        "assay",
        "bioetl.application.pipelines.chembl.assay_transformer",
        "AssayTransformer",
    ),
    (
        "chembl",
        "assay_parameters",
        "bioetl.application.pipelines.chembl.assay_parameters_transformer",
        "AssayParametersTransformer",
    ),
    (
        "chembl",
        "cell_line",
        "bioetl.application.pipelines.chembl.cell_line_transformer",
        "CellLineTransformer",
    ),
    (
        "chembl",
        "compound_record",
        "bioetl.application.pipelines.chembl.compound_record_transformer",
        "CompoundRecordTransformer",
    ),
    (
        "chembl",
        "document",
        "bioetl.application.pipelines.chembl.publication_transformer",
        "PublicationTransformer",
    ),
    (
        "chembl",
        "document_similarity",
        "bioetl.application.pipelines.chembl.publication_similarity_transformer",
        "PublicationSimilarityTransformer",
    ),
    (
        "chembl",
        "document_term",
        "bioetl.application.pipelines.chembl.publication_term_transformer",
        "PublicationTermTransformer",
    ),
    (
        "chembl",
        "molecule",
        "bioetl.application.pipelines.chembl.molecule_transformer",
        "MoleculeTransformer",
    ),
    (
        "chembl",
        "subcellular_fraction",
        "bioetl.application.pipelines.chembl.subcellular_fraction_transformer",
        "SubcellularFractionTransformer",
    ),
    (
        "chembl",
        "protein_class",
        "bioetl.application.pipelines.chembl.protein_class_transformer",
        "ProteinClassTransformer",
    ),
    (
        "chembl",
        "target",
        "bioetl.application.pipelines.chembl.target_transformer",
        "TargetTransformer",
    ),
    (
        "chembl",
        "target_component",
        "bioetl.application.pipelines.chembl.target_component_transformer",
        "TargetComponentTransformer",
    ),
    (
        "pubchem",
        "compound",
        "bioetl.application.pipelines.pubchem.transformer",
        "PubChemCompoundTransformer",
    ),
    (
        "uniprot",
        "protein",
        "bioetl.application.pipelines.uniprot.transformer",
        "UniProtProteinTransformer",
    ),
    (
        "uniprot",
        "idmapping",
        "bioetl.application.pipelines.uniprot.idmapping_transformer",
        "IDMappingTransformer",
    ),
    (
        "pubmed",
        "publication",
        "bioetl.application.pipelines.pubmed.transformer",
        "PubMedPublicationTransformer",
    ),
    (
        "crossref",
        "publication",
        "bioetl.application.pipelines.crossref.transformer",
        "CrossRefPublicationTransformer",
    ),
    (
        "openalex",
        "publication",
        "bioetl.application.pipelines.openalex.transformer",
        "OpenAlexPublicationTransformer",
    ),
    (
        "semanticscholar",
        "publication",
        "bioetl.application.pipelines.semanticscholar.transformer",
        "SemanticScholarPublicationTransformer",
    ),
)
