%% View: Overview | Parent: 35-bootstrap-sequence-full.mermaid
%% @uniform width=140 height=56 max_title_len=3 max_desc_lines=0
flowchart TB

    N1["S5A"]
    N2["S5B"]
    N3["S1B"]
    N4["S2A"]
    N5["S2B"]
    N6["S4D"]
    N7["S4E"]
    N8["S4F"]
    N9["S6A"]
    N10["S6B"]
    N11["S6C"]
    N12["S7A"]
    N13["S7B"]
    N14["S7C"]
    N15["S8A"]

    N3 --> N4
    N4 --> N5
    N6 --> N1
    N7 --> N1
    N8 --> N1
    N1 --> N2
    N2 --> N9
    N9 --> N10
    N10 --> N11
    N11 --> N12
    N11 --> N13
    N11 --> N14
    N12 --> N15
    N13 --> N15
    N14 --> N15

    %% linkStyle: data 0-14
    linkStyle 0 stroke:#1E293B,stroke-width:3px
    linkStyle 1 stroke:#1E293B,stroke-width:3px
    linkStyle 2 stroke:#1E293B,stroke-width:3px
    linkStyle 3 stroke:#1E293B,stroke-width:3px
    linkStyle 4 stroke:#1E293B,stroke-width:3px
    linkStyle 5 stroke:#1E293B,stroke-width:3px
    linkStyle 6 stroke:#1E293B,stroke-width:3px
    linkStyle 7 stroke:#1E293B,stroke-width:3px
    linkStyle 8 stroke:#1E293B,stroke-width:3px
    linkStyle 9 stroke:#1E293B,stroke-width:3px
    linkStyle 10 stroke:#1E293B,stroke-width:3px
    linkStyle 11 stroke:#1E293B,stroke-width:3px
    linkStyle 12 stroke:#1E293B,stroke-width:3px
    linkStyle 13 stroke:#1E293B,stroke-width:3px
    linkStyle 14 stroke:#1E293B,stroke-width:3px
