server:
  http_listen_port: 3200
  grpc_listen_port: 4317
  grpc_server_max_recv_msg_size: 33554432
  log_level: info

distributor:
  rate_limit_bytes: 33554432

ingester:
  max_block_duration: 5m

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
    cache: memcached
    memcached:
      consistent_hash: true
      host: localhost
      service: memcached
      update_interval: 1m

metrics_generator:
  registry:
    external_labels:
      cluster: bioetl
  storage:
    path: /tmp/tempo/wal

overrides:
  defaults:
    metrics_generator:
      processors: [batch, resource_detection, spanmetrics]
