"""Generated publication field group lookup tables."""

from __future__ import annotations

__all__ = ["FIELD_TO_GROUP_VALUE_MAPPING", "GROUP_DISPLAY_NAMES_BY_VALUE"]

GROUP_DISPLAY_NAMES_BY_VALUE: dict[str, str] = {
    "id_and_status": "ID & Status",
    "bibliography": "Bibliography",
    "author_and_affiliations": "Author & Affiliations",
    "terms_and_keywords_and_topics": "Terms & Keywords & Topics",
    "citations_and_reference": "Citations & Reference",
    "date_and_places": "Date & Places",
    "publication_types": "Publication Types",
    "system_metadata": "System Metadata",
    "trash": "Trash (Excluded)",
}

FIELD_TO_GROUP_VALUE_MAPPING: dict[str, str] = {
    "alternative_id": "id_and_status",
    "chembl_release": "id_and_status",
    "content_hash": "system_metadata",
    "corpus_id": "id_and_status",
    "dblp_id": "id_and_status",
    "publication_id": "id_and_status",
    "doi": "id_and_status",
    "entity_id": "id_and_status",
    "mag_id": "id_and_status",
    "nlm_unique_id": "id_and_status",
    "openalex_id": "id_and_status",
    "paper_id": "id_and_status",
    "pmc_id": "id_and_status",
    "pmid": "id_and_status",
    "src_id": "trash",
    "abstract": "bibliography",
    "abstract_structured": "bibliography",
    "issn": "bibliography",
    "issn_electronic": "bibliography",
    "issn_list": "bibliography",
    "issn_print": "bibliography",
    "issue": "bibliography",
    "journal": "bibliography",
    "journal_full_title": "bibliography",
    "journal_iso_abbrev": "bibliography",
    "journal_issn_type": "bibliography",
    "journal_name_short": "bibliography",
    "page_first": "bibliography",
    "page_last": "bibliography",
    "page_range": "bibliography",
    "published": "date_and_places",
    "published_online": "date_and_places",
    "published_print": "date_and_places",
    "publisher": "bibliography",
    "publication_year": "date_and_places",
    "title": "bibliography",
    "venue": "bibliography",
    "volume": "bibliography",
    "affiliation_list": "author_and_affiliations",
    "affiliation_structured": "author_and_affiliations",
    "author_count": "author_and_affiliations",
    "author_details": "trash",
    "author_h_indices": "author_and_affiliations",
    "author_keys": "author_and_affiliations",
    "author_openalex_ids": "author_and_affiliations",
    "author_orcids": "author_and_affiliations",
    "author_s2_ids": "author_and_affiliations",
    "authors": "author_and_affiliations",
    "authors_with_affiliations": "author_and_affiliations",
    "country": "date_and_places",
    "institution_country_codes": "date_and_places",
    "institution_ids": "author_and_affiliations",
    "ror_ids": "author_and_affiliations",
    "creation_date": "date_and_places",
    "date_completed": "date_and_places",
    "date_revised": "date_and_places",
    "pub_date": "date_and_places",
    "pub_day": "date_and_places",
    "pub_month": "date_and_places",
    "publication_date": "date_and_places",
    "fields_of_study": "terms_and_keywords_and_topics",
    "chemical_count": "terms_and_keywords_and_topics",
    "chemicals": "terms_and_keywords_and_topics",
    "citation_subset": "terms_and_keywords_and_topics",
    "databanks": "terms_and_keywords_and_topics",
    "fwci": "citations_and_reference",
    "gene_symbols": "terms_and_keywords_and_topics",
    "keyword_count": "terms_and_keywords_and_topics",
    "mesh": "terms_and_keywords_and_topics",
    "mesh_heading_count": "terms_and_keywords_and_topics",
    "primary_topic": "terms_and_keywords_and_topics",
    "subject_fields": "terms_and_keywords_and_topics",
    "subject_keywords": "terms_and_keywords_and_topics",
    "subject_mesh": "terms_and_keywords_and_topics",
    "subject_topics": "terms_and_keywords_and_topics",
    "citation_contexts": "citations_and_reference",
    "citations_made": "citations_and_reference",
    "citations_received": "citations_and_reference",
    "content_domain_crossmark_restriction": "trash",
    "content_domain_domains": "trash",
    "grant_count": "citations_and_reference",
    "grants": "citations_and_reference",
    "influential_citation_count": "citations_and_reference",
    "is_oa": "id_and_status",
    "is_retracted": "id_and_status",
    "language": "trash",
    "license_url": "trash",
    "medline_pgn": "trash",
    "oa_status": "id_and_status",
    "open_access_url": "id_and_status",
    "publication_status": "id_and_status",
    "publication_type": "publication_types",
    "publication_types": "publication_types",
    "references": "citations_and_reference",
    "tldr": "terms_and_keywords_and_topics",
}
