"""Facade for Data Quality report value objects and enums."""

from __future__ import annotations

from bioetl.domain.value_objects.dq_report_builder import (
    BronzeDQReport,
    DQReportSummary,
    DQThresholds,
    GoldDQReport,
    MedallionLayer,
    SilverDQReport,
)
from bioetl.domain.value_objects.dq_report_enums import (
    BronzeDQCheckType,
    DQCheckStatus,
    DQReportFormat,
    DQReportStatus,
    GoldDQCheckType,
    SilverDQCheckType,
)
from bioetl.domain.value_objects.dq_report_results import (
    AnomalyDetectionResult,
    AnomalyMetric,
    BusinessRuleResult,
    BusinessRulesResult,
    CategoricalDistribution,
    CompletenessResult,
    ContentHashIntegrityResult,
    DataFreshnessResult,
    DeduplicationStatsResult,
    DriftLevel,
    EncodingValidationResult,
    FileIntegrityResult,
    ForeignKeyResult,
    NullRateResult,
    NumericDistribution,
    RecordCountResult,
    ReferentialIntegrityResult,
    SCDIntegrityResult,
    SchemaDriftResult,
    SchemaSnapshotResult,
    StatisticalMetric,
    StatisticalProfileResult,
    TypeConformanceResult,
    UniquenessResult,
    ValueDistributionResult,
)

__all__ = [
    "AnomalyDetectionResult",
    "AnomalyMetric",
    "BronzeDQCheckType",
    "BronzeDQReport",
    "BusinessRuleResult",
    "BusinessRulesResult",
    "CategoricalDistribution",
    "CompletenessResult",
    "ContentHashIntegrityResult",
    "DQCheckStatus",
    "DQReportFormat",
    "DQReportStatus",
    "DQReportSummary",
    "DQThresholds",
    "DataFreshnessResult",
    "DeduplicationStatsResult",
    "DriftLevel",
    "EncodingValidationResult",
    "FileIntegrityResult",
    "ForeignKeyResult",
    "GoldDQCheckType",
    "GoldDQReport",
    "MedallionLayer",
    "NullRateResult",
    "NumericDistribution",
    "RecordCountResult",
    "ReferentialIntegrityResult",
    "SCDIntegrityResult",
    "SchemaDriftResult",
    "SchemaSnapshotResult",
    "SilverDQCheckType",
    "SilverDQReport",
    "StatisticalMetric",
    "StatisticalProfileResult",
    "TypeConformanceResult",
    "UniquenessResult",
    "ValueDistributionResult",
]
