"""Local pyarrow stubs for BioETL basedpyright (PD7-4).

Make ``pa.field`` / ``pa.string`` / schema builders known so Silver schema
modules stop flooding Project Diagnostics, while keeping Table/Schema as
real classes with common factory methods.
"""

from __future__ import annotations

from collections.abc import Iterator
from typing import Any

class DataType:
    def __iter__(self) -> Iterator[Any]: ...
    def __getattr__(self, name: str) -> Any: ...

class Field:
    name: str
    type: DataType
    nullable: bool
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Schema:
    names: list[str]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Field]: ...
    def __getitem__(self, key: Any) -> Any: ...
    def field(self, i: Any) -> Field: ...
    def empty_table(self) -> Table: ...
    def __getattr__(self, name: str) -> Any: ...

class Array:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __getitem__(self, key: Any) -> Any: ...
    def to_pylist(self) -> list[Any]: ...
    def __getattr__(self, name: str) -> Any: ...

class ChunkedArray:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __getitem__(self, key: Any) -> Any: ...
    def to_pylist(self) -> list[Any]: ...
    def __getattr__(self, name: str) -> Any: ...

class Table:
    schema: Schema
    num_rows: int
    num_columns: int
    column_names: list[str]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Any) -> Any: ...
    def column(self, i: Any) -> ChunkedArray: ...
    def to_pydict(self) -> dict[str, list[Any]]: ...
    def to_pylist(self) -> list[dict[str, Any]]: ...
    def to_pandas(self, **kwargs: Any) -> Any: ...
    def select(self, columns: Any) -> Table: ...
    def slice(self, offset: int = ..., length: int | None = ...) -> Table: ...
    def cast(self, target_schema: Any, safe: bool = ...) -> Table: ...
    def drop(self, columns: Any) -> Table: ...
    def rename_columns(self, names: Any) -> Table: ...
    def combine_chunks(self) -> Table: ...
    def flatten(self) -> Table: ...
    def __getattr__(self, name: str) -> Any: ...
    @staticmethod
    def from_pydict(*args: Any, **kwargs: Any) -> Table: ...
    @staticmethod
    def from_pylist(*args: Any, **kwargs: Any) -> Table: ...
    @staticmethod
    def from_arrays(*args: Any, **kwargs: Any) -> Table: ...
    @staticmethod
    def from_pandas(*args: Any, **kwargs: Any) -> Table: ...
    @staticmethod
    def from_batches(*args: Any, **kwargs: Any) -> Table: ...

class RecordBatch:
    schema: Schema
    num_rows: int
    def __getattr__(self, name: str) -> Any: ...

class Scalar:
    def as_py(self) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...

def field(*args: Any, **kwargs: Any) -> Field: ...
def schema(*args: Any, **kwargs: Any) -> Schema: ...
def string(*args: Any, **kwargs: Any) -> DataType: ...
def utf8(*args: Any, **kwargs: Any) -> DataType: ...
def binary(*args: Any, **kwargs: Any) -> DataType: ...
def large_string(*args: Any, **kwargs: Any) -> DataType: ...
def large_binary(*args: Any, **kwargs: Any) -> DataType: ...
def bool_(*args: Any, **kwargs: Any) -> DataType: ...
def int8(*args: Any, **kwargs: Any) -> DataType: ...
def int16(*args: Any, **kwargs: Any) -> DataType: ...
def int32(*args: Any, **kwargs: Any) -> DataType: ...
def int64(*args: Any, **kwargs: Any) -> DataType: ...
def uint8(*args: Any, **kwargs: Any) -> DataType: ...
def uint16(*args: Any, **kwargs: Any) -> DataType: ...
def uint32(*args: Any, **kwargs: Any) -> DataType: ...
def uint64(*args: Any, **kwargs: Any) -> DataType: ...
def float16(*args: Any, **kwargs: Any) -> DataType: ...
def float32(*args: Any, **kwargs: Any) -> DataType: ...
def float64(*args: Any, **kwargs: Any) -> DataType: ...
def null(*args: Any, **kwargs: Any) -> DataType: ...
def timestamp(*args: Any, **kwargs: Any) -> DataType: ...
def date32(*args: Any, **kwargs: Any) -> DataType: ...
def date64(*args: Any, **kwargs: Any) -> DataType: ...
def time32(*args: Any, **kwargs: Any) -> DataType: ...
def time64(*args: Any, **kwargs: Any) -> DataType: ...
def duration(*args: Any, **kwargs: Any) -> DataType: ...
def decimal128(*args: Any, **kwargs: Any) -> DataType: ...
def decimal256(*args: Any, **kwargs: Any) -> DataType: ...
def list_(*args: Any, **kwargs: Any) -> DataType: ...
def large_list(*args: Any, **kwargs: Any) -> DataType: ...
def struct(*args: Any, **kwargs: Any) -> DataType: ...
def map_(*args: Any, **kwargs: Any) -> DataType: ...
def dictionary(*args: Any, **kwargs: Any) -> DataType: ...
def array(*args: Any, **kwargs: Any) -> Array: ...
def nulls(*args: Any, **kwargs: Any) -> Array: ...
def table(*args: Any, **kwargs: Any) -> Table: ...
def concat_tables(*args: Any, **kwargs: Any) -> Table: ...
def concat_arrays(*args: Any, **kwargs: Any) -> Array: ...
def record_batch(*args: Any, **kwargs: Any) -> RecordBatch: ...
def scalar(*args: Any, **kwargs: Any) -> Scalar: ...

class _Submodule:
    def __getattr__(self, name: str) -> Any: ...

types: _Submodule
compute: _Submodule
csv: _Submodule
parquet: _Submodule
feather: _Submodule
json: _Submodule
ipc: _Submodule
dataset: _Submodule
fs: _Submodule
cuda: _Submodule

def __getattr__(name: str) -> Any: ...

__version__: str
