"""Shard filter specs extracted from the graph sync kernel (AUD-002)."""

from __future__ import annotations

__all__ = [
    "DOCS_DRIFT_FILTER",
    "RUNTIME_EVIDENCE_LAYER_FILTER",
    "STORAGE_LAYER_FILTER",
    "WORKFLOW_GRAPH_FILTER",
    "RelationSpec",
    "ShardFilter",
    "ShardFilterSpec",
]


type RelationSpec = tuple[str, frozenset[str], frozenset[str]]
type ShardFilterSpec = tuple[frozenset[str], tuple[RelationSpec, ...]]
type ShardFilter = ShardFilterSpec

STORAGE_LAYER_FILTER: ShardFilterSpec = (
    frozenset(
        {
            "project",
            "pipeline_surface",
            "entity_config",
            "composite_config",
            "config_artifact",
            "storage_surface",
            "runtime_evidence_surface",
            "control_plane_artifact_surface",
            "run_instance_surface",
            "runtime_state_surface",
            "schema_field_surface",
        }
    ),
    (
        ("HAS_STORAGE_SURFACE", frozenset({"project"}), frozenset({"storage_surface"})),
        (
            "HAS_RUNTIME_EVIDENCE",
            frozenset({"project"}),
            frozenset({"runtime_evidence_surface"}),
        ),
        (
            "HAS_CONTROL_PLANE_ARTIFACT",
            frozenset({"project"}),
            frozenset({"control_plane_artifact_surface"}),
        ),
        (
            "HAS_RUN_INSTANCE",
            frozenset({"project"}),
            frozenset({"run_instance_surface"}),
        ),
        (
            "WRITES_TO",
            frozenset(
                {
                    "pipeline_surface",
                    "entity_config",
                    "composite_config",
                    "runtime_evidence_surface",
                }
            ),
            frozenset({"storage_surface"}),
        ),
        (
            "DEFINED_BY",
            frozenset({"pipeline_surface", "entity_config", "composite_config"}),
            frozenset({"config_artifact"}),
        ),
        ("PROMOTES_TO", frozenset({"storage_surface"}), frozenset({"storage_surface"})),
        (
            "EMITS_ARTIFACT",
            frozenset({"runtime_evidence_surface"}),
            frozenset({"control_plane_artifact_surface"}),
        ),
        (
            "MATERIALIZED_AS",
            frozenset({"control_plane_artifact_surface"}),
            frozenset({"storage_surface"}),
        ),
        (
            "REFERENCES_ARTIFACT",
            frozenset({"run_instance_surface"}),
            frozenset({"control_plane_artifact_surface"}),
        ),
        (
            "HAS_SCHEMA_FIELD",
            frozenset({"project", "storage_surface", "contract_surface"}),
            frozenset({"schema_field_surface"}),
        ),
        (
            "PROMOTES_FIELD_TO",
            frozenset({"schema_field_surface"}),
            frozenset({"schema_field_surface"}),
        ),
        (
            "DERIVES_FIELD_FROM",
            frozenset({"schema_field_surface"}),
            frozenset({"schema_field_surface"}),
        ),
        (
            "HAS_RUNTIME_STATE",
            frozenset({"project", "run_instance_surface"}),
            frozenset({"runtime_state_surface"}),
        ),
        (
            "REFERENCES_ARTIFACT",
            frozenset({"runtime_state_surface"}),
            frozenset({"control_plane_artifact_surface"}),
        ),
    ),
)
RUNTIME_EVIDENCE_LAYER_FILTER: ShardFilterSpec = (
    frozenset(
        {
            "project",
            "runtime_evidence_surface",
            "control_plane_artifact_surface",
            "run_instance_surface",
            "runtime_state_surface",
            "storage_surface",
            "module_surface",
            "doc_artifact",
            "test_artifact",
            "pipeline_surface",
            "contract_surface",
            "workflow_surface",
        }
    ),
    (
        (
            "HAS_RUNTIME_EVIDENCE",
            frozenset({"project"}),
            frozenset({"runtime_evidence_surface"}),
        ),
        (
            "HAS_CONTROL_PLANE_ARTIFACT",
            frozenset({"project"}),
            frozenset({"control_plane_artifact_surface"}),
        ),
        (
            "HAS_RUN_INSTANCE",
            frozenset({"project"}),
            frozenset({"run_instance_surface"}),
        ),
        (
            "BACKED_BY",
            frozenset({"runtime_evidence_surface"}),
            frozenset({"module_surface"}),
        ),
        (
            "DESCRIBED_IN",
            frozenset({"runtime_evidence_surface"}),
            frozenset({"doc_artifact"}),
        ),
        (
            "DESCRIBED_IN",
            frozenset({"run_instance_surface"}),
            frozenset({"doc_artifact", "test_artifact"}),
        ),
        (
            "DEPENDS_ON",
            frozenset({"run_instance_surface"}),
            frozenset({"pipeline_surface", "contract_surface"}),
        ),
        (
            "WRITES_TO",
            frozenset({"runtime_evidence_surface"}),
            frozenset({"storage_surface"}),
        ),
        (
            "EMITS_ARTIFACT",
            frozenset({"runtime_evidence_surface"}),
            frozenset({"control_plane_artifact_surface"}),
        ),
        (
            "MATERIALIZED_AS",
            frozenset({"control_plane_artifact_surface"}),
            frozenset({"storage_surface"}),
        ),
        (
            "REFERENCES_ARTIFACT",
            frozenset({"run_instance_surface"}),
            frozenset({"control_plane_artifact_surface"}),
        ),
        (
            "HAS_RUNTIME_STATE",
            frozenset({"project", "run_instance_surface"}),
            frozenset({"runtime_state_surface"}),
        ),
        (
            "DEPENDS_ON",
            frozenset({"runtime_state_surface"}),
            frozenset(
                {
                    "pipeline_surface",
                    "workflow_surface",
                    "runtime_evidence_surface",
                    "contract_surface",
                }
            ),
        ),
        (
            "REFERENCES_ARTIFACT",
            frozenset({"runtime_state_surface"}),
            frozenset({"control_plane_artifact_surface"}),
        ),
        (
            "DESCRIBED_IN",
            frozenset({"runtime_state_surface"}),
            frozenset({"doc_artifact"}),
        ),
    ),
)
WORKFLOW_GRAPH_FILTER: ShardFilterSpec = (
    frozenset(
        {
            "project",
            "workflow_surface",
            "workflow_job_surface",
            "workflow_call_surface",
            "workflow_matrix_variant_surface",
            "workflow_output_surface",
            "workflow_action_surface",
            "workflow_artifact_surface",
            "workflow_secret_surface",
            "script_surface",
            "file_surface",
            "directory_surface",
            "quality_gate",
        }
    ),
    (
        ("HAS_WORKFLOW", frozenset({"project"}), frozenset({"workflow_surface"})),
        (
            "CONTAINS",
            frozenset({"workflow_surface"}),
            frozenset({"workflow_job_surface"}),
        ),
        (
            "CALLS_WORKFLOW",
            frozenset({"workflow_surface", "workflow_job_surface"}),
            frozenset({"workflow_call_surface"}),
        ),
        (
            "HAS_MATRIX_VARIANT",
            frozenset({"workflow_job_surface"}),
            frozenset({"workflow_matrix_variant_surface"}),
        ),
        (
            "EMITS_OUTPUT",
            frozenset({"workflow_surface", "workflow_job_surface"}),
            frozenset({"workflow_output_surface"}),
        ),
        (
            "RUNS_VIA",
            frozenset({"workflow_job_surface"}),
            frozenset({"script_surface", "file_surface", "directory_surface"}),
        ),
        (
            "EXECUTES_GATE",
            frozenset({"workflow_job_surface"}),
            frozenset({"quality_gate"}),
        ),
        (
            "DEPENDS_ON",
            frozenset({"workflow_job_surface", "workflow_call_surface"}),
            frozenset(
                {
                    "workflow_job_surface",
                    "workflow_artifact_surface",
                    "workflow_surface",
                }
            ),
        ),
        (
            "USES_ACTION",
            frozenset({"workflow_job_surface"}),
            frozenset({"workflow_action_surface"}),
        ),
        (
            "PUBLISHES_ARTIFACT",
            frozenset({"workflow_job_surface"}),
            frozenset({"workflow_artifact_surface"}),
        ),
        (
            "REQUIRES_SECRET",
            frozenset({"workflow_job_surface"}),
            frozenset({"workflow_secret_surface"}),
        ),
    ),
)
DOCS_DRIFT_FILTER: ShardFilterSpec = (
    frozenset(
        {
            "doc_source_surface",
            "doc_artifact",
            "policy_surface",
            "doc_claim_surface",
            "module_surface",
            "script_surface",
            "config_artifact",
            "workflow_surface",
            "cli_command_surface",
            "file_surface",
            "directory_surface",
            "execution_path",
        }
    ),
    (
        (
            "DESCRIBES",
            frozenset({"doc_source_surface", "doc_artifact", "policy_surface"}),
            frozenset(
                {
                    "module_surface",
                    "script_surface",
                    "config_artifact",
                    "workflow_surface",
                    "cli_command_surface",
                    "file_surface",
                    "directory_surface",
                    "execution_path",
                }
            ),
        ),
        (
            "ASSERTS",
            frozenset({"doc_source_surface", "doc_artifact", "policy_surface"}),
            frozenset({"doc_claim_surface"}),
        ),
        (
            "DESCRIBED_IN",
            frozenset({"module_surface"}),
            frozenset({"doc_source_surface", "doc_artifact"}),
        ),
        (
            "ASSERTS_ABOUT",
            frozenset({"doc_claim_surface"}),
            frozenset(
                {
                    "module_surface",
                    "script_surface",
                    "config_artifact",
                    "workflow_surface",
                    "cli_command_surface",
                    "file_surface",
                    "directory_surface",
                    "execution_path",
                }
            ),
        ),
    ),
)
