"""Helpers extracted from the graph sync kernel (AUD-002)."""

from __future__ import annotations

__all__ = [
    "SNAPSHOT_RELATION_REQUIREMENTS",
]

SNAPSHOT_RELATION_REQUIREMENTS = (
    (
        "missing project -> HAS_REPO_ZONE -> repo_zone links",
        {"project"},
        "HAS_REPO_ZONE",
        {"repo_zone"},
    ),
    (
        "missing directory_surface -> CONTAINS -> file_surface links",
        {"directory_surface"},
        "CONTAINS",
        {"file_surface"},
    ),
    (
        "missing file_surface -> BACKS -> module_surface links",
        {"file_surface"},
        "BACKS",
        {"module_surface"},
    ),
    (
        "missing directory_surface -> HOUSES -> package_family links",
        {"directory_surface"},
        "HOUSES",
        {"package_family"},
    ),
    (
        "missing directory_surface -> HOUSES -> entity_config links",
        {"directory_surface"},
        "HOUSES",
        {"entity_config"},
    ),
    (
        "missing directory_surface -> HOUSES -> doc_source_surface links",
        {"directory_surface"},
        "HOUSES",
        {"doc_source_surface"},
    ),
    (
        "missing directory_surface -> HOUSES -> test_artifact links",
        {"directory_surface"},
        "HOUSES",
        {"test_artifact"},
    ),
    (
        "missing module_surface -> DECLARES -> class_surface links",
        {"module_surface"},
        "DECLARES",
        {"class_surface"},
    ),
    (
        "missing class_surface -> DECLARES -> method_surface links",
        {"class_surface"},
        "DECLARES",
        {"method_surface"},
    ),
    (
        "missing module_surface -> DECLARES -> function_surface links",
        {"module_surface"},
        "DECLARES",
        {"function_surface"},
    ),
    (
        "missing duplication_cluster promotion targets",
        {"duplication_cluster"},
        "CAN_PROMOTE_TO",
        None,
    ),
    (
        "missing duplication_cluster -> CONTAINS -> callable surface links",
        {"duplication_cluster"},
        "CONTAINS",
        {"method_surface", "function_surface"},
    ),
    (
        "missing callable duplication links",
        {"method_surface", "function_surface"},
        "SAME_SHAPE_AS",
        None,
    ),
    (
        "missing code surface -> HAS_COMPLEXITY_SIGNAL -> complexity_candidate links",
        {"module_surface", "class_surface", "function_surface", "method_surface"},
        "HAS_COMPLEXITY_SIGNAL",
        {"complexity_candidate"},
    ),
    (
        "missing complexity simplification candidates",
        {"complexity_candidate"},
        "CANDIDATE_FOR_SIMPLIFICATION",
        None,
    ),
    (
        "missing contract_surface -> DEPENDS_ON -> module_surface relations",
        {"contract_surface"},
        "DEPENDS_ON",
        {"module_surface"},
    ),
    (
        "missing contract_surface -> DESCRIBED_IN -> doc_artifact relations",
        {"contract_surface"},
        "DESCRIBED_IN",
        {"doc_artifact"},
    ),
    (
        "missing pipeline_surface operational runtime links",
        {"pipeline_surface"},
        "RUNS_VIA",
        {"execution_path"},
    ),
    (
        "missing pipeline_surface direct test coverage links",
        {"pipeline_surface"},
        "TESTED_BY",
        {"test_artifact"},
    ),
    (
        "missing pipeline_surface -> DEFINED_BY -> config_artifact links",
        {"pipeline_surface"},
        "DEFINED_BY",
        {"config_artifact"},
    ),
    (
        "missing pipeline_surface -> DESCRIBED_IN -> doc_artifact links",
        {"pipeline_surface"},
        "DESCRIBED_IN",
        {"doc_artifact"},
    ),
    (
        "missing pipeline_surface -> DEPENDS_ON -> module_surface links",
        {"pipeline_surface"},
        "DEPENDS_ON",
        {"module_surface"},
    ),
    (
        "missing module_surface -> DESCRIBED_IN -> doc_artifact links",
        {"module_surface"},
        "DESCRIBED_IN",
        {"doc_artifact"},
    ),
    (
        "missing entity_config -> DEPENDS_ON -> module_surface links",
        {"entity_config"},
        "DEPENDS_ON",
        {"module_surface"},
    ),
    (
        "missing alert_surface dependency links",
        {"alert_surface"},
        "DEPENDS_ON",
        {"pipeline_surface", "provider_surface"},
    ),
    (
        "missing alert_surface -> DEPENDS_ON -> contract_surface links",
        {"alert_surface"},
        "DEPENDS_ON",
        {"contract_surface"},
    ),
    (
        "missing alert_surface -> OBSERVED_BY -> dashboard_surface links",
        {"alert_surface"},
        "OBSERVED_BY",
        {"dashboard_surface"},
    ),
    (
        "missing project -> HAS_RUNTIME_EVIDENCE -> runtime_evidence_surface links",
        {"project"},
        "HAS_RUNTIME_EVIDENCE",
        {"runtime_evidence_surface"},
    ),
    (
        "missing project -> HAS_CONTROL_PLANE_ARTIFACT -> control_plane_artifact_surface links",
        {"project"},
        "HAS_CONTROL_PLANE_ARTIFACT",
        {"control_plane_artifact_surface"},
    ),
    (
        "missing project -> HAS_RUN_INSTANCE -> run_instance_surface links",
        {"project"},
        "HAS_RUN_INSTANCE",
        {"run_instance_surface"},
    ),
    (
        "missing project -> HAS_RUNTIME_STATE -> runtime_state_surface links",
        {"project"},
        "HAS_RUNTIME_STATE",
        {"runtime_state_surface"},
    ),
    (
        "missing project -> HAS_WORKFLOW -> workflow_surface links",
        {"project"},
        "HAS_WORKFLOW",
        {"workflow_surface"},
    ),
    (
        "missing project -> HAS_CLI_COMMAND -> cli_command_surface links",
        {"project"},
        "HAS_CLI_COMMAND",
        {"cli_command_surface"},
    ),
    (
        "missing workflow_surface -> CONTAINS -> workflow_job_surface links",
        {"workflow_surface"},
        "CONTAINS",
        {"workflow_job_surface"},
    ),
    (
        "missing workflow/workflow_job -> CALLS_WORKFLOW -> workflow_call_surface links",
        {"workflow_surface", "workflow_job_surface"},
        "CALLS_WORKFLOW",
        {"workflow_call_surface"},
    ),
    (
        "missing workflow_job_surface -> HAS_MATRIX_VARIANT -> workflow_matrix_variant_surface links",
        {"workflow_job_surface"},
        "HAS_MATRIX_VARIANT",
        {"workflow_matrix_variant_surface"},
    ),
    (
        "missing workflow/workflow_job -> EMITS_OUTPUT -> workflow_output_surface links",
        {"workflow_surface", "workflow_job_surface"},
        "EMITS_OUTPUT",
        {"workflow_output_surface"},
    ),
    (
        "missing workflow_job_surface -> RUNS_VIA operational target links",
        {"workflow_job_surface"},
        "RUNS_VIA",
        {"script_surface", "file_surface", "directory_surface"},
    ),
    (
        "missing workflow_job_surface -> EXECUTES_GATE -> quality_gate links",
        {"workflow_job_surface"},
        "EXECUTES_GATE",
        {"quality_gate"},
    ),
    (
        "missing workflow_job_surface -> USES_ACTION -> workflow_action_surface links",
        {"workflow_job_surface"},
        "USES_ACTION",
        {"workflow_action_surface"},
    ),
    (
        "missing workflow_job_surface -> PUBLISHES_ARTIFACT -> workflow_artifact_surface links",
        {"workflow_job_surface"},
        "PUBLISHES_ARTIFACT",
        {"workflow_artifact_surface"},
    ),
    (
        "missing workflow_job_surface -> REQUIRES_SECRET -> workflow_secret_surface links",
        {"workflow_job_surface"},
        "REQUIRES_SECRET",
        {"workflow_secret_surface"},
    ),
    (
        "missing cli_command_surface -> RUNS_VIA -> execution_path links",
        {"cli_command_surface"},
        "RUNS_VIA",
        {"execution_path"},
    ),
    (
        "missing cli_command_surface -> ACCEPTS_OPTION -> cli_option_surface links",
        {"cli_command_surface"},
        "ACCEPTS_OPTION",
        {"cli_option_surface"},
    ),
    (
        "missing cli_command_surface side effect links",
        {"cli_command_surface"},
        "SIDE_EFFECTS_ON",
        None,
    ),
    (
        "missing storage_surface -> HAS_SCHEMA_FIELD -> schema_field_surface links",
        {"storage_surface"},
        "HAS_SCHEMA_FIELD",
        {"schema_field_surface"},
    ),
    (
        "missing contract_surface -> HAS_SCHEMA_FIELD -> schema_field_surface links",
        {"contract_surface"},
        "HAS_SCHEMA_FIELD",
        {"schema_field_surface"},
    ),
    (
        "missing pipeline_surface -> WRITES_TO -> storage_surface links",
        {"pipeline_surface"},
        "WRITES_TO",
        {"storage_surface"},
    ),
    (
        "missing storage_surface promotion links",
        {"storage_surface"},
        "PROMOTES_TO",
        {"storage_surface"},
    ),
    (
        "missing runtime_evidence_surface -> WRITES_TO -> storage_surface links",
        {"runtime_evidence_surface"},
        "WRITES_TO",
        {"storage_surface"},
    ),
    (
        "missing runtime_evidence_surface -> EMITS_ARTIFACT -> control_plane_artifact_surface links",
        {"runtime_evidence_surface"},
        "EMITS_ARTIFACT",
        {"control_plane_artifact_surface"},
    ),
    (
        "missing control_plane_artifact_surface -> MATERIALIZED_AS -> storage_surface links",
        {"control_plane_artifact_surface"},
        "MATERIALIZED_AS",
        {"storage_surface"},
    ),
    (
        "missing run_instance_surface -> REFERENCES_ARTIFACT -> control_plane_artifact_surface links",
        {"run_instance_surface"},
        "REFERENCES_ARTIFACT",
        {"control_plane_artifact_surface"},
    ),
    (
        "missing run_instance_surface -> HAS_RUNTIME_STATE -> runtime_state_surface links",
        {"run_instance_surface"},
        "HAS_RUNTIME_STATE",
        {"runtime_state_surface"},
    ),
    (
        "missing runtime_state_surface dependency links",
        {"runtime_state_surface"},
        "DEPENDS_ON",
        {"pipeline_surface", "workflow_surface", "runtime_evidence_surface"},
    ),
    (
        "missing runtime_state_surface -> REFERENCES_ARTIFACT -> control_plane_artifact_surface links",
        {"runtime_state_surface"},
        "REFERENCES_ARTIFACT",
        {"control_plane_artifact_surface"},
    ),
    (
        "missing schema_field_surface promotion links",
        {"schema_field_surface"},
        "PROMOTES_FIELD_TO",
        {"schema_field_surface"},
    ),
    (
        "missing schema_field_surface derivation links",
        {"schema_field_surface"},
        "DERIVES_FIELD_FROM",
        {"schema_field_surface"},
    ),
    (
        "missing docs-to-code drift edges",
        {"doc_source_surface", "doc_artifact", "policy_surface"},
        "DESCRIBES",
        {
            "module_surface",
            "script_surface",
            "config_artifact",
            "workflow_surface",
            "cli_command_surface",
            "file_surface",
            "directory_surface",
            "execution_path",
        },
    ),
    (
        "missing ADR constraint edges",
        {"decision"},
        "CONSTRAINS",
        {
            "module_surface",
            "file_surface",
            "config_artifact",
            "test_artifact",
            "directory_surface",
        },
    ),
    (
        "missing doc claim extraction edges",
        {"doc_source_surface", "doc_artifact", "policy_surface"},
        "ASSERTS",
        {"doc_claim_surface"},
    ),
    (
        "missing doc claim traceability edges",
        {"doc_claim_surface"},
        "ASSERTS_ABOUT",
        {
            "module_surface",
            "script_surface",
            "config_artifact",
            "workflow_surface",
            "cli_command_surface",
            "file_surface",
            "directory_surface",
            "execution_path",
        },
    ),
    (
        "missing adapter_surface -> CONTAINS -> adapter_impl_surface links",
        {"adapter_surface"},
        "CONTAINS",
        {"adapter_impl_surface"},
    ),
)
