"""Row data for ChEMBL reference-identifier policy families."""

from __future__ import annotations

__all__ = ["CHEMBL_REFERENCE_IDENTIFIER_FAMILY_ROWS"]

CHEMBL_REFERENCE_IDENTIFIER_FAMILY_ROWS = (
    (
        "chembl",
        "chembl",
        "preserve_unknown_lexeme",
        (
            "chembl_activity.assay_id",
            "chembl_activity.molecule_id",
            "chembl_activity.parent_molecule_id",
            "chembl_activity.publication_id",
            "chembl_activity.target_id",
            "chembl_assay.assay_id",
            "chembl_assay.cell_id",
            "chembl_assay.publication_id",
            "chembl_assay.target_id",
            "chembl_assay.tissue_id",
            "chembl_assay_parameters.assay_id",
            "chembl_cell_line.cell_id",
            "chembl_compound_record.molecule_id",
            "chembl_compound_record.publication_id",
            "chembl_molecule.hierarchy_active_chembl_id",
            "chembl_molecule.hierarchy_child_chembl_id",
            "chembl_molecule.hierarchy_parent_chembl_id",
            "chembl_molecule.molecule_id",
            "chembl_publication.publication_id",
            "chembl_publication_term.publication_id",
            "chembl_subcellular_fraction.example_assay_id",
            "chembl_target.target_id",
            "chembl_tissue.tissue_id",
        ),
    ),
    (
        "ncbi_taxonomy",
        "ncbi_taxonomy",
        "preserve_numeric_range_for_dq_review",
        (
            "chembl_activity.target_taxonomy_id",
            "chembl_assay.assay_taxonomy_id",
            "chembl_assay.variant_taxonomy_id",
            "chembl_cell_line.cell_source_taxonomy_id",
            "chembl_target.taxonomy_id",
            "chembl_target_component.taxonomy_id",
        ),
    ),
    (
        "uniprot_accession",
        "uniprot_accession",
        "preserve_unknown_lexeme",
        (
            "chembl_activity.assay_variant_accession",
            "chembl_assay.variant_accession",
            "chembl_target.component_accessions",
            "chembl_target_component.accession",
        ),
    ),
    (
        "doi",
        "doi",
        "canonicalize_or_null_blank",
        (
            "chembl_activity.publication_doi",
            "chembl_publication.doi",
            "chembl_publication.publication_doi",
        ),
    ),
    (
        "pmid",
        "pmid",
        "reject_invalid_numeric_identifier",
        (
            "chembl_activity.publication_pmid",
            "chembl_publication.pmid",
            "chembl_publication.publication_pmid",
            "chembl_publication_similarity.pubmed_id1",
            "chembl_publication_similarity.pubmed_id2",
        ),
    ),
    (
        "pmcid",
        "pmcid",
        "preserve_unknown_lexeme",
        (
            "chembl_activity.publication_pmc_id",
            "chembl_publication.pmc_id",
            "chembl_publication.publication_pmc_id",
        ),
    ),
    (
        "mesh",
        "mesh",
        "preserve_unknown_lexeme",
        ("chembl_publication_term.mesh_id",),
    ),
)
