"""Default immutable ChEMBL policy registry payload."""

from __future__ import annotations

from bioetl.domain.normalization.profiles._chembl_policy_registry_data import (
    ChemblControlledVocabularyFamily,
    ChemblOntologyPolicyFamily,
    ChemblPolicyRegistryData,
    ChemblReferenceIdentifierFamily,
    ChemblStrictScalarFamily,
)
from bioetl.domain.normalization.profiles._chembl_policy_registry_reference_identifier_rows import (
    CHEMBL_REFERENCE_IDENTIFIER_FAMILY_ROWS,
)

DEFAULT_CHEMBL_POLICY_REGISTRY_DATA = ChemblPolicyRegistryData(
    strict_boolean_families=(
        ChemblStrictScalarFamily(
            family_name="bool_like",
            invalid_value_mode="coerce_common_boolean_lexemes",
            fields=(
                "chembl_molecule.therapeutic_flag",
                "chembl_molecule.oral",
                "chembl_molecule.parenteral",
                "chembl_molecule.topical",
                "chembl_molecule.withdrawn_flag",
                "chembl_publication.is_oa",
                "chembl_target.species_group_flag",
            ),
        ),
    ),
    strict_flag_families=(
        ChemblStrictScalarFamily(
            family_name="binary_flags",
            invalid_value_mode="coerce_common_flag_lexemes",
            fields=(
                "chembl_activity.standard_flag",
                "chembl_activity.potential_duplicate",
                "chembl_activity.manual_curation_flag",
                "chembl_molecule.black_box_warning",
                "chembl_molecule.dosed_ingredient",
                "chembl_molecule.polymer_flag",
                "chembl_protein_class.downgraded",
            ),
        ),
        ChemblStrictScalarFamily(
            family_name="provider_code_flags",
            invalid_value_mode="coerce_reviewed_flag_provider_codes",
            fields=(
                "chembl_molecule.first_in_class",
                "chembl_molecule.inorganic_flag",
                "chembl_molecule.natural_product",
                "chembl_molecule.prodrug",
            ),
        ),
    ),
    controlled_vocabularies=(
        ChemblControlledVocabularyFamily(
            family_name="activity_action_types",
            invalid_value_mode="preserve_unknown_uppercase_lexeme",
            fields=("chembl_activity.action_type",),
        ),
        ChemblControlledVocabularyFamily(
            family_name="raw_units",
            invalid_value_mode="preserve_unknown_lexeme",
            fields=(
                "chembl_activity.units",
                "chembl_assay_parameters.units",
            ),
        ),
        ChemblControlledVocabularyFamily(
            family_name="standard_units",
            invalid_value_mode="reject_unknown_lexeme",
            fields=(
                "chembl_activity.standard_units",
                "chembl_assay_parameters.standard_units",
            ),
        ),
        ChemblControlledVocabularyFamily(
            family_name="operators",
            invalid_value_mode="preserve_unknown_lexeme",
            fields=(
                "chembl_activity.relation",
                "chembl_assay_parameters.relation",
            ),
        ),
        ChemblControlledVocabularyFamily(
            family_name="assay_parameter_types",
            invalid_value_mode="preserve_unknown_uppercase_lexeme",
            fields=(
                "chembl_assay_parameters.type",
                "chembl_assay_parameters.parameter_type",
            ),
        ),
        ChemblControlledVocabularyFamily(
            family_name="assay_categories",
            invalid_value_mode="reject_unknown_lexeme",
            fields=("chembl_assay.assay_category",),
        ),
        ChemblControlledVocabularyFamily(
            family_name="assay_confidence_descriptions",
            invalid_value_mode="reject_unknown_lexeme",
            fields=("chembl_assay.confidence_description",),
        ),
        ChemblControlledVocabularyFamily(
            family_name="publication_oa_statuses",
            invalid_value_mode="reject_unknown_lexeme",
            fields=("chembl_publication.oa_status",),
        ),
        ChemblControlledVocabularyFamily(
            family_name="target_organism_classes",
            invalid_value_mode="reject_unknown_lexeme",
            fields=("chembl_target.organism_class",),
        ),
        ChemblControlledVocabularyFamily(
            family_name="target_component_types",
            invalid_value_mode="reject_unknown_json_array_element",
            fields=("chembl_target.component_types",),
        ),
        ChemblControlledVocabularyFamily(
            family_name="target_component_relationships",
            invalid_value_mode="reject_unknown_json_array_element",
            fields=("chembl_target.component_relationships",),
        ),
        ChemblControlledVocabularyFamily(
            family_name="subcellular_fractions",
            invalid_value_mode="preserve_unknown_lexeme",
            fields=(
                "chembl_assay.assay_subcellular_fraction",
                "chembl_subcellular_fraction.subcellular_fraction",
            ),
        ),
    ),
    ontology_families=(
        ChemblOntologyPolicyFamily(
            family_name="bao",
            fields=(
                "chembl_activity.bao_endpoint",
                "chembl_activity.bao_format",
                "chembl_assay.bao_format",
            ),
            code_label_fields=("chembl_assay.bao_label",),
            iri_fields=(
                "chembl_activity.bao_endpoint_iri",
                "chembl_activity.bao_format_iri",
                "chembl_assay.bao_format_iri",
            ),
            mapping_status_fields=(
                "chembl_activity.bao_endpoint_mapping_status",
                "chembl_activity.bao_format_mapping_status",
                "chembl_assay.bao_format_mapping_status",
            ),
            version_fields=(
                "chembl_activity.bao_ontology_version",
                "chembl_assay.bao_ontology_version",
            ),
        ),
        ChemblOntologyPolicyFamily(
            family_name="uo",
            fields=(
                "chembl_activity.uo_units",
                "chembl_assay_parameters.uo_units",
            ),
            iri_fields=(
                "chembl_activity.uo_unit_iri",
                "chembl_assay_parameters.uo_unit_iri",
            ),
            mapping_status_fields=(
                "chembl_activity.uo_unit_mapping_status",
                "chembl_assay_parameters.uo_unit_mapping_status",
            ),
            version_fields=(
                "chembl_activity.uo_ontology_version",
                "chembl_assay_parameters.uo_ontology_version",
            ),
        ),
        ChemblOntologyPolicyFamily(
            family_name="qudt",
            fields=(
                "chembl_activity.qudt_units",
                "chembl_assay_parameters.qudt_units",
            ),
            iri_fields=(
                "chembl_activity.qudt_unit_iri",
                "chembl_assay_parameters.qudt_unit_iri",
            ),
            mapping_status_fields=(
                "chembl_activity.qudt_unit_mapping_status",
                "chembl_assay_parameters.qudt_unit_mapping_status",
            ),
            version_fields=(
                "chembl_activity.qudt_ontology_version",
                "chembl_assay_parameters.qudt_ontology_version",
            ),
        ),
        ChemblOntologyPolicyFamily(
            family_name="bto",
            fields=("chembl_tissue.bto_id",),
            iri_fields=("chembl_tissue.bto_iri",),
            mapping_status_fields=("chembl_tissue.bto_mapping_status",),
            version_fields=("chembl_tissue.bto_ontology_version",),
        ),
        ChemblOntologyPolicyFamily(
            family_name="caloha",
            fields=("chembl_tissue.caloha_id",),
            companion_governance="identifier_only_no_companion_bundle",
        ),
        ChemblOntologyPolicyFamily(
            family_name="efo",
            fields=(
                "chembl_cell_line.efo_id",
                "chembl_tissue.efo_id",
            ),
            iri_fields=(
                "chembl_cell_line.efo_iri",
                "chembl_tissue.efo_iri",
            ),
            mapping_status_fields=(
                "chembl_cell_line.efo_mapping_status",
                "chembl_tissue.efo_mapping_status",
            ),
            version_fields=(
                "chembl_cell_line.efo_ontology_version",
                "chembl_tissue.efo_ontology_version",
            ),
        ),
        ChemblOntologyPolicyFamily(
            family_name="clo",
            fields=("chembl_cell_line.clo_id",),
            iri_fields=("chembl_cell_line.clo_iri",),
            mapping_status_fields=("chembl_cell_line.clo_mapping_status",),
            version_fields=("chembl_cell_line.clo_ontology_version",),
        ),
        ChemblOntologyPolicyFamily(
            family_name="uberon",
            fields=("chembl_tissue.uberon_id",),
            iri_fields=("chembl_tissue.uberon_iri",),
            mapping_status_fields=("chembl_tissue.uberon_mapping_status",),
            version_fields=("chembl_tissue.uberon_ontology_version",),
        ),
        ChemblOntologyPolicyFamily(
            family_name="cellosaurus",
            fields=("chembl_cell_line.cellosaurus_id",),
            companion_governance="identifier_only_no_companion_bundle",
        ),
    ),
    publication_classification_fields=(
        "publication_type_unified",
        "publication_subclass",
        "publication_class",
    ),
    reference_identifier_families=tuple(
        ChemblReferenceIdentifierFamily(
            family_name=family_name,
            reference_family=reference_family,
            invalid_value_mode=invalid_value_mode,
            fields=fields,
        )
        for family_name, reference_family, invalid_value_mode, fields in (
            CHEMBL_REFERENCE_IDENTIFIER_FAMILY_ROWS
        )
    ),
)

__all__ = ["DEFAULT_CHEMBL_POLICY_REGISTRY_DATA"]
