"""Reviewed bounded vocabularies for Prometheus metric label normalizers."""

from __future__ import annotations

from bioetl.infrastructure.observability._prometheus_metric_label_vocab_core import (
    _ALLOWED_FILTER_SOURCE_KIND_LABELS,
    _ALLOWED_FLOW_STAGE_LABELS,
    _ALLOWED_REASON_LABELS,
    _ALLOWED_RECORD_FLOW_INVARIANT_LABELS,
    _ALLOWED_RECORD_FLOW_INVARIANT_STATUS_LABELS,
    _ALLOWED_RUNTIME_STAGE_LABELS,
    _ALLOWED_SEVERITY_LABELS,
    _ALLOWED_STAGE_LABELS,
    _ALLOWED_TERMINAL_STATUS_LABELS,
)
from bioetl.infrastructure.observability._prometheus_metric_label_vocab_pipeline import (
    _ALLOWED_BATCH_LIFECYCLE_EVENT_LABELS,
    _ALLOWED_COMPOSITE_PHASE_ERROR_KIND_LABELS,
    _ALLOWED_COMPOSITE_PHASE_LOSS_KIND_LABELS,
    _ALLOWED_COMPOSITE_PHASE_RECORD_OUTCOME_LABELS,
    _ALLOWED_COMPOSITE_PHASE_RETRY_KIND_LABELS,
    _ALLOWED_PHASE_LABELS,
    _ALLOWED_POSTRUN_PHASE_LABELS,
    _ALLOWED_STAGE_MODEL_OUTCOME_LABELS,
    _ALLOWED_STAGE_MODEL_STAGE_LABELS,
)
from bioetl.infrastructure.observability._prometheus_metric_label_vocab_publication import (
    _ALLOWED_ADAPTER_OPERATION_LABELS,
    _ALLOWED_OBSERVABILITY_COMPONENT_LABELS,
    _ALLOWED_OBSERVABILITY_MODE_LABELS,
    _ALLOWED_PUBLICATION_STATUS_LABELS,
    _ALLOWED_PUBLICATION_TARGET_LABELS,
    _ALLOWED_PUBLICATION_VOCAB_FIELD_LABELS,
    _ALLOWED_PUBLICATION_VOCAB_HANDLING_LABELS,
    _ALLOWED_PUBLICATION_VOCAB_PROVIDER_LABELS,
    _DYNAMIC_ENDPOINT_SEGMENT_PATTERNS,
    _SOURCE_FILE_CLASS_BY_SUFFIX,
)
from bioetl.infrastructure.observability._prometheus_metric_label_vocab_quality import (
    _ALLOWED_DQ_CHECK_TYPE_LABELS,
    _ALLOWED_DQ_DISPOSITION_LABELS,
    _ALLOWED_STRUCTURAL_ACTION_LABELS,
    _ALLOWED_STRUCTURAL_COMPARISON_LABELS,
)
from bioetl.infrastructure.observability._prometheus_metric_label_vocab_silver import (
    _ALLOWED_SILVER_FILTER_FIELD_LABELS,
    _ALLOWED_SILVER_FILTER_REASON_CODE_LABELS,
    _ALLOWED_SILVER_FILTER_RULE_TYPE_LABELS,
)

__all__ = [
    "_ALLOWED_ADAPTER_OPERATION_LABELS",
    "_ALLOWED_BATCH_LIFECYCLE_EVENT_LABELS",
    "_ALLOWED_COMPOSITE_PHASE_ERROR_KIND_LABELS",
    "_ALLOWED_COMPOSITE_PHASE_LOSS_KIND_LABELS",
    "_ALLOWED_COMPOSITE_PHASE_RECORD_OUTCOME_LABELS",
    "_ALLOWED_COMPOSITE_PHASE_RETRY_KIND_LABELS",
    "_ALLOWED_DQ_CHECK_TYPE_LABELS",
    "_ALLOWED_DQ_DISPOSITION_LABELS",
    "_ALLOWED_FILTER_SOURCE_KIND_LABELS",
    "_ALLOWED_FLOW_STAGE_LABELS",
    "_ALLOWED_OBSERVABILITY_COMPONENT_LABELS",
    "_ALLOWED_OBSERVABILITY_MODE_LABELS",
    "_ALLOWED_PHASE_LABELS",
    "_ALLOWED_POSTRUN_PHASE_LABELS",
    "_ALLOWED_PUBLICATION_STATUS_LABELS",
    "_ALLOWED_PUBLICATION_TARGET_LABELS",
    "_ALLOWED_PUBLICATION_VOCAB_FIELD_LABELS",
    "_ALLOWED_PUBLICATION_VOCAB_HANDLING_LABELS",
    "_ALLOWED_PUBLICATION_VOCAB_PROVIDER_LABELS",
    "_ALLOWED_REASON_LABELS",
    "_ALLOWED_RECORD_FLOW_INVARIANT_LABELS",
    "_ALLOWED_RECORD_FLOW_INVARIANT_STATUS_LABELS",
    "_ALLOWED_RUNTIME_STAGE_LABELS",
    "_ALLOWED_SEVERITY_LABELS",
    "_ALLOWED_SILVER_FILTER_FIELD_LABELS",
    "_ALLOWED_SILVER_FILTER_REASON_CODE_LABELS",
    "_ALLOWED_SILVER_FILTER_RULE_TYPE_LABELS",
    "_ALLOWED_STAGE_LABELS",
    "_ALLOWED_STAGE_MODEL_OUTCOME_LABELS",
    "_ALLOWED_STAGE_MODEL_STAGE_LABELS",
    "_ALLOWED_STRUCTURAL_ACTION_LABELS",
    "_ALLOWED_STRUCTURAL_COMPARISON_LABELS",
    "_ALLOWED_TERMINAL_STATUS_LABELS",
    "_DYNAMIC_ENDPOINT_SEGMENT_PATTERNS",
    "_SOURCE_FILE_CLASS_BY_SUFFIX",
]
