#!/usr/bin/env python3
"""Generate/check compatibility facade snapshot companion docs."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "ci"))
    from _compatibility_registry import (  # type: ignore[import-not-found]
        DEFAULT_REGISTRY_PATH,
        DEFAULT_SRC_ROOT,
        CompatibilityRegistry,
        load_compatibility_registry,
        scan_docstring_tracked_modules,
        validate_measured_docstring_surface,
    )
else:
    raise SystemExit(
        "Run this generator as a script from the repository root, not as a package module."
    )


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = (
    ROOT / "docs" / "02-architecture" / "07-compatibility-facade-snapshot.md"
)
_FRONTMATTER_DELIMITER = "---"


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate/check the compatibility facade snapshot companion file."
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="Fail on drift.")
    mode.add_argument("--update", action="store_true", help="Rewrite snapshot file.")
    parser.add_argument(
        "--registry",
        default=str(DEFAULT_REGISTRY_PATH),
        help="Path to compatibility registry YAML.",
    )
    parser.add_argument(
        "--src-root",
        default=str(DEFAULT_SRC_ROOT),
        help="Source root used for docstring-tracking validation.",
    )
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT),
        help="Generated markdown snapshot path.",
    )
    return parser.parse_args()


def _render_path_list(paths: list[str]) -> list[str]:
    if not paths:
        return ["- None."]
    return [f"- `{path}`" for path in paths]


def _render_measured_only_modules(registry: CompatibilityRegistry) -> list[str]:
    if not registry.measured_only_modules:
        return ["- None."]

    lines: list[str] = []
    for row in registry.measured_only_modules:
        lines.append(
            f"- `{row.path}` — owner: `{row.owner}`, review: `{row.review_date}`, "
            f"policy: `{row.new_code_policy}`, promote on: `{row.promotion_trigger}`, "
            f"reason: {row.reason}"
        )
    return lines


def render_snapshot(
    registry: CompatibilityRegistry,
    *,
    discovered_docstring_modules: set[str],
    unexpected_docstring_modules: set[str],
    missing_measured_only_modules: set[str],
) -> str:
    tracked_paths = sorted(registry.measured_tracked_paths)
    discovered_paths = sorted(discovered_docstring_modules)
    unexpected_paths = sorted(unexpected_docstring_modules)
    missing_paths = sorted(missing_measured_only_modules)

    sections = [
        "# Compatibility Facade Snapshot (Generated)",
        "",
        "> Generated by `scripts/qa/generate_compatibility_facade_snapshot.py`. Do not edit manually.",
        "",
        "## Summary",
        "",
        f"- Registry YAML: `{DEFAULT_REGISTRY_PATH.relative_to(ROOT).as_posix()}`",
        f"- Curated inventory rows: `{len(registry.curated_rows)}`",
        f"- Transition debt rows: `{len(registry.transition_debt)}`",
        f"- Retained public entrypoints: `{len(registry.retained_entrypoints)}`",
        f"- Measured tracked modules: `{len(registry.measured_tracked_paths)}`",
        f"- Measured-only modules outside curated inventory: `{len(registry.measured_only_paths)}`",
        f"- Discovered docstring-tracked modules: `{len(discovered_paths)}`",
        f"- Unexpected docstring-tracked modules: `{len(unexpected_paths)}`",
        f"- Missing allowlisted measured-only modules: `{len(missing_paths)}`",
        "",
        "## Tracked Docstring Prefixes",
        "",
        *[f"- `{prefix}`" for prefix in registry.tracked_docstring_prefixes],
        "",
        "## Expected Measured Registry",
        "",
        *_render_path_list(tracked_paths),
        "",
        "## Measured-Only Allowlist",
        "",
        *_render_measured_only_modules(registry),
        "",
        "## Live Docstring Tracking Validation",
        "",
        "### Discovered Docstring-Tracked Modules",
        "",
        *_render_path_list(discovered_paths),
        "",
        "### Unexpected Docstring-Tracked Modules",
        "",
        *_render_path_list(unexpected_paths),
        "",
        "### Missing Allowlisted Measured-Only Modules",
        "",
        *_render_path_list(missing_paths),
        "",
    ]
    return "\n".join(sections)


def _split_frontmatter(text: str) -> tuple[str | None, str]:
    if not text.startswith(f"{_FRONTMATTER_DELIMITER}\n"):
        return None, text
    parts = text.split(f"\n{_FRONTMATTER_DELIMITER}\n", 1)
    if len(parts) != 2:
        return None, text
    frontmatter, body = parts
    return f"{frontmatter}\n{_FRONTMATTER_DELIMITER}\n", body


def main() -> int:
    args = _parse_args()
    registry = load_compatibility_registry(Path(args.registry))
    discovered = scan_docstring_tracked_modules(
        src_root=Path(args.src_root),
        prefixes=registry.tracked_docstring_prefixes,
    )
    unexpected, missing = validate_measured_docstring_surface(
        registry,
        src_root=Path(args.src_root),
    )
    rendered = render_snapshot(
        registry,
        discovered_docstring_modules=discovered,
        unexpected_docstring_modules=unexpected,
        missing_measured_only_modules=missing,
    )
    output_path = Path(args.output)
    current = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
    frontmatter, current_body = _split_frontmatter(current)

    if args.check:
        if current_body != rendered:
            print(f"[drift] mismatch: {output_path.as_posix()}")
            return 1
        if unexpected or missing:
            if unexpected:
                print("[drift] unexpected docstring-tracked modules:")
                for path in sorted(unexpected):
                    print(f"  - {path}")
            if missing:
                print("[drift] missing allowlisted measured-only modules:")
                for path in sorted(missing):
                    print(f"  - {path}")
            return 1
        print("[ok] compatibility facade snapshot is up to date")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    rendered_with_frontmatter = f"{frontmatter}{rendered}" if frontmatter else rendered
    output_path.write_text(rendered_with_frontmatter, encoding="utf-8")
    print(f"[updated] wrote {output_path.as_posix()}")
    if unexpected or missing:
        if unexpected:
            print("[warn] unexpected docstring-tracked modules:")
            for path in sorted(unexpected):
                print(f"  - {path}")
        if missing:
            print("[warn] missing allowlisted measured-only modules:")
            for path in sorted(missing):
                print(f"  - {path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
