"""Canonical field orders for composite pipeline schemas.

Defines the authoritative field ordering for composite publication output.
The order is derived from docs/schemas/publication_field_order.csv and
used by ColumnOrderer and tests to ensure deterministic column ordering.

Categories (6 groups, 167 fully-qualified fields):
  - id (1-24): Identifiers, content hashes, entity IDs
  - bibliography (25-83): Title, abstract, journal, pagination, year
  - author_and_affiliation (84-104): Authors, affiliations, institutions
  - date (105-114): Publication and revision dates
  - topics_and_keywords (115-130): MeSH, topics, keywords, chemicals
  - publication (131-167): Citations, OA, types, language, misc
"""

from __future__ import annotations

from typing import Final

__all__ = [
    "PUBLICATION_CANONICAL_CATEGORIES",
    "PUBLICATION_FIELD_ORDER",
]

# Canonical order of all 167 fully-qualified publication fields.
# Source of truth: docs/schemas/publication_field_order.csv
PUBLICATION_FIELD_ORDER: Final[tuple[str, ...]] = (
    # === id (1-24) ===
    "crossref.publication.alternative_id",
    "chembl.publication.chembl_release",
    "chembl.publication.content_hash",
    "crossref.publication.content_hash",
    "openalex.publication.content_hash",
    "pubmed.publication.content_hash",
    "semanticscholar.publication.content_hash",
    "semanticscholar.publication.corpus_id",
    "semanticscholar.publication.dblp_id",
    "chembl.publication.document_chembl_id",
    "chembl.publication.entity_id",
    "crossref.publication.entity_id",
    "openalex.publication.entity_id",
    "pubmed.publication.entity_id",
    "semanticscholar.publication.entity_id",
    "openalex.publication.mag_id",
    "pubmed.publication.nlm_unique_id",
    "openalex.publication.openalex_id",
    "semanticscholar.publication.paper_id",
    "pubmed.publication.pmc_id",
    "chembl.publication.pmid",
    "openalex.publication.pmid",
    "semanticscholar.publication.pmid",
    "chembl.publication.src_id",
    # === bibliography (25-83) ===
    "chembl.publication.abstract",
    "openalex.publication.abstract",
    "pubmed.publication.abstract",
    "semanticscholar.publication.abstract",
    "pubmed.publication.abstract_structured",
    "chembl.publication.doi",
    "pubmed.publication.doi",
    "crossref.publication.issn",
    "openalex.publication.issn",
    "pubmed.publication.issn",
    "crossref.publication.issn_electronic",
    "crossref.publication.issn_list",
    "crossref.publication.issn_print",
    "chembl.publication.issue",
    "crossref.publication.issue",
    "openalex.publication.issue",
    "pubmed.publication.issue",
    "semanticscholar.publication.issue",
    "chembl.publication.journal",
    "crossref.publication.journal",
    "openalex.publication.journal",
    "pubmed.publication.journal",
    "semanticscholar.publication.journal",
    "pubmed.publication.journal_iso_abbrev",
    "pubmed.publication.journal_issn_type",
    "crossref.publication.journal_name_short",
    "pubmed.publication.journal_name_short",
    "chembl.publication.page_first",
    "crossref.publication.page_first",
    "openalex.publication.page_first",
    "pubmed.publication.page_first",
    "semanticscholar.publication.page_first",
    "chembl.publication.page_last",
    "crossref.publication.page_last",
    "openalex.publication.page_last",
    "pubmed.publication.page_last",
    "semanticscholar.publication.page_last",
    "pubmed.publication.page_range",
    "semanticscholar.publication.page_range",
    "crossref.publication.published",
    "crossref.publication.published_online",
    "crossref.publication.published_print",
    "crossref.publication.publisher",
    "openalex.publication.publisher",
    "chembl.publication.publication_year",
    "crossref.publication.publication_year",
    "openalex.publication.publication_year",
    "pubmed.publication.publication_year",
    "semanticscholar.publication.publication_year",
    "chembl.publication.title",
    "crossref.publication.title",
    "openalex.publication.title",
    "pubmed.publication.title",
    "semanticscholar.publication.title",
    "chembl.publication.volume",
    "crossref.publication.volume",
    "openalex.publication.volume",
    "pubmed.publication.volume",
    "semanticscholar.publication.volume",
    # === author_and_affiliation (84-104) ===
    "pubmed.publication.affiliation_list",
    "openalex.publication.affiliation_list",
    "semanticscholar.publication.affiliation_list",
    "pubmed.publication.affiliation_structured",
    "pubmed.publication.author_count",
    "crossref.publication.author_details",
    "semanticscholar.publication.author_h_indices",
    "openalex.publication.author_openalex_ids",
    "crossref.publication.author_orcid_list",
    "openalex.publication.author_orcids",
    "semanticscholar.publication.author_orcids",
    "semanticscholar.publication.author_s2_ids",
    "chembl.publication.authors",
    "crossref.publication.authors",
    "openalex.publication.authors",
    "pubmed.publication.authors",
    "pubmed.publication.authors_with_affiliations",
    "pubmed.publication.country",
    "openalex.publication.institution_country_codes",
    "openalex.publication.institution_ids",
    "openalex.publication.ror_ids",
    # === date (105-114) ===
    "chembl.publication.creation_date",
    "pubmed.publication.date_completed",
    "pubmed.publication.date_revised",
    "pubmed.publication.pub_date",
    "pubmed.publication.pub_day",
    "pubmed.publication.pub_month",
    "crossref.publication.publication_date",
    "openalex.publication.publication_date",
    "pubmed.publication.publication_date",
    "semanticscholar.publication.publication_date",
    # === topics_and_keywords (115-130) ===
    "pubmed.publication.chemical_count",
    "pubmed.publication.chemicals",
    "pubmed.publication.citation_subset",
    "pubmed.publication.databanks",
    "openalex.publication.fwci",
    "pubmed.publication.gene_symbols",
    "pubmed.publication.keyword_count",
    "pubmed.publication.mesh_heading_count",
    "openalex.publication.primary_topic",
    "semanticscholar.publication.subject_fields",
    "crossref.publication.subject_keywords",
    "openalex.publication.subject_keywords",
    "pubmed.publication.subject_keywords",
    "openalex.publication.subject_mesh",
    "pubmed.publication.subject_mesh",
    "openalex.publication.subject_topics",
    # === publication (131-167) ===
    "semanticscholar.publication.citation_contexts",
    "chembl.publication.citations_made",
    "crossref.publication.citations_made",
    "openalex.publication.citations_made",
    "pubmed.publication.citations_made",
    "semanticscholar.publication.citations_made",
    "chembl.publication.citations_received",
    "crossref.publication.citations_received",
    "openalex.publication.citations_received",
    "semanticscholar.publication.citations_received",
    "crossref.publication.content_domain_crossmark_restriction",
    "crossref.publication.content_domain_domains",
    "pubmed.publication.grant_count",
    "openalex.publication.grants",
    "semanticscholar.publication.influential_citation_count",
    "openalex.publication.is_oa",
    "semanticscholar.publication.is_oa",
    "openalex.publication.is_retracted",
    "crossref.publication.language",
    "openalex.publication.language",
    "pubmed.publication.language",
    "crossref.publication.license_url",
    "pubmed.publication.medline_pgn",
    "openalex.publication.oa_status",
    "semanticscholar.publication.oa_status",
    "semanticscholar.publication.open_access_url",
    "pubmed.publication.publication_status",
    "chembl.publication.publication_type",
    "crossref.publication.publication_type",
    "openalex.publication.publication_type",
    "pubmed.publication.publication_type",
    "semanticscholar.publication.publication_type",
    "pubmed.publication.publication_type_list",
    "pubmed.publication.publication_types",
    "semanticscholar.publication.publication_types",
    "crossref.publication.references",
    "semanticscholar.publication.tldr",
)

# Canonical categories with their field ranges (1-indexed, inclusive).
PUBLICATION_CANONICAL_CATEGORIES: Final[dict[str, tuple[int, int]]] = {
    "id": (1, 24),
    "bibliography": (25, 83),
    "author_and_affiliation": (84, 104),
    "date": (105, 114),
    "topics_and_keywords": (115, 130),
    "publication": (131, 167),
}
