"""Centralized immutable constants for schema validation."""

from __future__ import annotations

from bioetl.domain.pubchem_standardization_catalog import (
    PUBCHEM_CHEMICAL_STANDARDIZATION_POLICY_VERSION,
    PUBCHEM_CHEMICAL_STANDARDIZATION_STATUSES,
    PUBCHEM_STANDARDIZATION_ENUM_CATALOG,
)
from bioetl.domain.schemas._chembl_enum_catalog import (
    ACTIVITY_ACTION_TYPES,
    ACTIVITY_STANDARD_TYPES,
    ACTIVITY_STANDARD_UNITS,
    ASSAY_CATEGORIES,
    ASSAY_GROUPS,
    ASSAY_PARAMETER_STANDARD_TYPES,
    ASSAY_TEST_TYPES,
    ASSAY_TYPES,
    CHEMBL_ENUM_CATALOG,
    CONFIDENCE_DESCRIPTIONS,
    DATA_VALIDITY_COMMENTS,
    MAX_PHASE_VALUES,
    MOLECULE_TYPES,
    OA_STATUS_VALUES,
    ONTOLOGY_MAPPING_STATUSES,
    PUBLICATION_TERM_TYPES,
    PUBLICATION_TYPES,
    RELATIONSHIP_TYPES,
    RO3_PASS_VALUES,
    STANDARD_RELATIONS,
    STRUCTURE_TYPES,
    SUBCELLULAR_FRACTIONS,
    TARGET_COMPONENT_RELATIONSHIPS,
    TARGET_COMPONENT_TYPES,
    TARGET_TYPES,
)
from bioetl.domain.schemas._schema_validation_patterns import (
    BAO_ID_PATTERN,
    BTO_ID_PATTERN,
    CALOHA_ID_PATTERN,
    CELLOSAURUS_ID_PATTERN,
    CHEMBL_ID_PATTERN,
    CLO_ID_PATTERN,
    EFO_ID_PATTERN,
    ISO_DATE_PATTERN,
    ISSN_PATTERN,
    ORCID_PATTERN,
    UBERON_ID_PATTERN,
    UO_ID_PATTERN,
)
from bioetl.domain.schemas._uniprot_enum_catalog import (
    UNIPROT_ENTRY_TYPES,
    UNIPROT_ENUM_CATALOG,
    UNIPROT_MAPPING_STATUSES,
    UNIPROT_PROTEIN_EXISTENCE_LEVELS,
    UNIPROT_PROTEIN_FLAGS,
)

# =============================================================================
# CANONICAL VALIDATION BOUNDS (Gold / Composite layer)
# =============================================================================
# Unified bounds for fields shared across providers (ChEMBL, PubChem).
# Silver schemas retain provider-specific bounds; these apply to Gold output.
# RF-NORM-02: Normalization Unification Plan.

CANONICAL_MOLECULAR_WEIGHT_RANGE: tuple[float, float] = (0.0, 100_000.0)
CANONICAL_HBA_COUNT_RANGE: tuple[int, int] = (0, 200)
CANONICAL_HBD_COUNT_RANGE: tuple[int, int] = (0, 200)
CANONICAL_ROTATABLE_BOND_COUNT_RANGE: tuple[int, int] = (0, 500)
CANONICAL_HEAVY_ATOM_COUNT_RANGE: tuple[int, int] = (0, 2000)
CANONICAL_LOGP_RANGE: tuple[float, float] = (-30.0, 30.0)
CANONICAL_POLAR_SURFACE_AREA_RANGE: tuple[float, float] = (0.0, 5000.0)
CANONICAL_SMILES_MAX_LENGTH: int = 20_000

# =============================================================================
# EXPORTS (for explicit re-export in __init__.py)
# =============================================================================

__all__ = [
    "ACTIVITY_ACTION_TYPES",
    "ACTIVITY_STANDARD_TYPES",
    "ACTIVITY_STANDARD_UNITS",
    "ASSAY_CATEGORIES",
    "ASSAY_GROUPS",
    "ASSAY_PARAMETER_STANDARD_TYPES",
    "ASSAY_TEST_TYPES",
    "ASSAY_TYPES",
    "BAO_ID_PATTERN",
    "BTO_ID_PATTERN",
    "CALOHA_ID_PATTERN",
    "CANONICAL_HBA_COUNT_RANGE",
    "CANONICAL_HBD_COUNT_RANGE",
    "CANONICAL_HEAVY_ATOM_COUNT_RANGE",
    "CANONICAL_LOGP_RANGE",
    "CANONICAL_MOLECULAR_WEIGHT_RANGE",
    "CANONICAL_POLAR_SURFACE_AREA_RANGE",
    "CANONICAL_ROTATABLE_BOND_COUNT_RANGE",
    "CANONICAL_SMILES_MAX_LENGTH",
    "CELLOSAURUS_ID_PATTERN",
    "CHEMBL_ENUM_CATALOG",
    "CHEMBL_ID_PATTERN",
    "CLO_ID_PATTERN",
    "CONFIDENCE_DESCRIPTIONS",
    "DATA_VALIDITY_COMMENTS",
    "EFO_ID_PATTERN",
    "ISO_DATE_PATTERN",
    "ISSN_PATTERN",
    "MAX_PHASE_VALUES",
    "MOLECULE_TYPES",
    "OA_STATUS_VALUES",
    "ONTOLOGY_MAPPING_STATUSES",
    "ORCID_PATTERN",
    "PUBCHEM_CHEMICAL_STANDARDIZATION_POLICY_VERSION",
    "PUBCHEM_CHEMICAL_STANDARDIZATION_STATUSES",
    "PUBCHEM_STANDARDIZATION_ENUM_CATALOG",
    "PUBLICATION_TERM_TYPES",
    "PUBLICATION_TYPES",
    "RELATIONSHIP_TYPES",
    "RO3_PASS_VALUES",
    "STANDARD_RELATIONS",
    "STRUCTURE_TYPES",
    "SUBCELLULAR_FRACTIONS",
    "TARGET_COMPONENT_RELATIONSHIPS",
    "TARGET_COMPONENT_TYPES",
    "TARGET_TYPES",
    "UBERON_ID_PATTERN",
    "UNIPROT_ENTRY_TYPES",
    "UNIPROT_ENUM_CATALOG",
    "UNIPROT_MAPPING_STATUSES",
    "UNIPROT_PROTEIN_EXISTENCE_LEVELS",
    "UNIPROT_PROTEIN_FLAGS",
    "UO_ID_PATTERN",
]
