"""Generate zero-arg Grok workflows for cyclic audit/fix prompt cards."""

from __future__ import annotations

from pathlib import Path

OUT = Path(".grok/workflows")

# prompt_id, workflow name, description, baked defaults (card tables).
CARDS: list[tuple[str, str, str, dict[str, str]]] = [
    (
        "prompt.architecture.cycle",
        "architecture-cycle",
        "Cyclic architecture audit (10 categories) then issues then fix waves",
        {
            "N": "10",
            "SCOPE": "src/bioetl/",
            "MODE": "full",
            "LANGUAGE": "ru",
            "AUDIT_MODE": "full",
            "INCLUDE_PIPELINE": "true",
            "LAYERS": "all",
            "SCORE_SOURCE": "live+committed",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MAX_ISSUES_PER_ITERATION": "5",
            "MAX_WAVES_PER_ITERATION": "3",
            "BASE_BRANCH": "main",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "WORK_BRANCH": "fix/architecture-audit-cycle",
        },
    ),
    (
        "prompt.audit.coderabbit-project-cycle",
        "audit-coderabbit-project-cycle",
        "Cyclic full-project audit plus CodeRabbit dual-pass",
        {
            "N": "10",
            "SCOPE": "all",
            "MODE": "full",
            "LANGUAGE": "ru",
            "AUDIT_MODE": "full",
            "CODERABBIT": "required-then-agent",
            "CR_MODE": "cli+app",
            "INCLUDE_DOMAINS": "all",
            "MAX_FILES_PER_SCOPE": "300",
            "MAX_ISSUES_PER_ITERATION": "5",
            "MAX_WAVES_PER_ITERATION": "3",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "BASE_BRANCH": "main",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "WORK_BRANCH": "fix/coderabbit-project-cycle",
        },
    ),
    (
        "prompt.audit.cycle.agents-memory",
        "audit-cycle-agents-memory",
        "Cyclic audit of AGENTS.md, runtime trees, and src/memory",
        {
            "N": "10",
            "SCOPE": "AGENTS.md .codex/ .junie/ .devin/ docs/00-project/ai/ scripts/ai/ src/memory/ scripts/memory/",
            "MODE": "full",
            "LANGUAGE": "ru",
            "AUDIT_MODE": "full",
            "CONTOURS": "runtime,scripts,memory",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MAX_ISSUES_PER_ITERATION": "5",
            "BASE_BRANCH": "main",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "WORK_BRANCH": "fix/audit-cycle-agents-memory",
        },
    ),
    (
        "prompt.audit.cycle.architecture",
        "audit-cycle-architecture",
        "Canonical cyclic architecture domain card (cycle pack #7)",
        {
            "N": "10",
            "SCOPE": "src/bioetl/ tests/architecture/",
            "MODE": "full",
            "LANGUAGE": "ru",
            "AUDIT_MODE": "full",
            "INCLUDE_PIPELINE": "true",
            "LAYERS": "all",
            "SCORE_SOURCE": "live+committed",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MAX_ISSUES_PER_ITERATION": "5",
            "MAX_WAVES_PER_ITERATION": "3",
            "BASE_BRANCH": "main",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "WORK_BRANCH": "fix/architecture-audit-cycle",
        },
    ),
    (
        "prompt.audit.cycle.coderabbit",
        "audit-cycle-coderabbit",
        "Canonical cyclic CodeRabbit domain card (cycle pack #10)",
        {
            "N": "10",
            "SCOPE": "all",
            "MODE": "full",
            "LANGUAGE": "ru",
            "AUDIT_MODE": "full",
            "CODERABBIT": "required-then-agent",
            "CR_MODE": "cli+app",
            "INCLUDE_DOMAINS": "all",
            "MAX_FILES_PER_SCOPE": "300",
            "MAX_ISSUES_PER_ITERATION": "5",
            "MAX_WAVES_PER_ITERATION": "3",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "BASE_BRANCH": "main",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "WORK_BRANCH": "fix/coderabbit-project-cycle",
        },
    ),
    (
        "prompt.audit.cycle.configs",
        "audit-cycle-configs",
        "Cyclic configs/schema audit then issues then fix",
        {
            "N": "10",
            "SCOPE": "configs/ pyproject.toml mkdocs.yml .importlinter commitlint.config.mjs package.json docker-compose.yml Dockerfile.bioetl .coderabbit.yaml",
            "MODE": "full",
            "LANGUAGE": "ru",
            "AUDIT_MODE": "full",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MAX_ISSUES_PER_ITERATION": "5",
            "BASE_BRANCH": "main",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "WORK_BRANCH": "fix/audit-cycle-configs",
        },
    ),
    (
        "prompt.audit.cycle.dashboards",
        "audit-cycle-dashboards",
        "Canonical cyclic dashboard render/design card (cycle pack #9)",
        {
            "N": "10",
            "SCOPE": "grafana/dashboards",
            "MODE": "full",
            "LANGUAGE": "ru",
            "DEPTH": "full",
            "AUDIT_MODE": "full",
            "CONTOURS": "render,density-area,density-scalar,fill,fit,reflow,visual,layout,data,copy,safety",
            "VIEWPORT": "1366x768",
            "THEME": "dark",
            "ZOOM": "100",
            "USER_ROLE": "operator",
            "MONITORING": "true",
            "INCLUDE_PIPELINE": "true",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MAX_ISSUES_PER_ITERATION": "5",
            "BASE_BRANCH": "main",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "WORK_BRANCH": "fix/dashboard-audit-cycle",
        },
    ),
    (
        "prompt.audit.cycle.diagrams",
        "audit-cycle-diagrams",
        "Cyclic diagrams audit then issues then fix",
        {
            "N": "10",
            "SCOPE": "docs/02-architecture/diagrams scripts/diagrams",
            "MODE": "full",
            "LANGUAGE": "ru",
            "AUDIT_MODE": "full",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MAX_ISSUES_PER_ITERATION": "5",
            "BASE_BRANCH": "main",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "WORK_BRANCH": "fix/audit-cycle-diagrams",
        },
    ),
    (
        "prompt.audit.cycle.docs",
        "audit-cycle-docs",
        "Cyclic documentation audit then issues then fix",
        {
            "N": "10",
            "SCOPE": "README.md docs/ mkdocs.yml scripts/docs/",
            "MODE": "full",
            "LANGUAGE": "ru",
            "AUDIT_MODE": "full",
            "INCLUDE_PIPELINE": "true",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MAX_ISSUES_PER_ITERATION": "5",
            "BASE_BRANCH": "main",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "WORK_BRANCH": "fix/audit-cycle-docs",
        },
    ),
    (
        "prompt.audit.cycle.tech-debt",
        "audit-cycle-tech-debt",
        "Cyclic tech-debt audit then issues then paydown (budgets never rise)",
        {
            "N": "10",
            "SCOPE": "src/bioetl/ configs/quality/",
            "MODE": "full",
            "LANGUAGE": "ru",
            "AUDIT_MODE": "full",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MAX_ISSUES_PER_ITERATION": "5",
            "BASE_BRANCH": "main",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "WORK_BRANCH": "fix/audit-cycle-tech-debt",
        },
    ),
    (
        "prompt.audit.cycle.telemetry",
        "audit-cycle-telemetry",
        "Cyclic observability/telemetry feed audit then issues then fix",
        {
            "N": "10",
            "SCOPE": "src/bioetl/infrastructure/observability grafana/prometheus-rules grafana/prometheus.yml grafana/provisioning docs/04-reference/observability",
            "MODE": "full",
            "LANGUAGE": "ru",
            "AUDIT_MODE": "full",
            "MONITORING": "true",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MAX_ISSUES_PER_ITERATION": "5",
            "BASE_BRANCH": "main",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "WORK_BRANCH": "fix/audit-cycle-telemetry",
        },
    ),
    (
        "prompt.audit.cycle.tests",
        "audit-cycle-tests",
        "Cyclic test-system audit then issues then fix",
        {
            "N": "10",
            "SCOPE": "tests/ configs/quality/ pyproject.toml",
            "MODE": "full",
            "LANGUAGE": "ru",
            "LANE": "unit",
            "AUDIT_MODE": "full",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MAX_ISSUES_PER_ITERATION": "5",
            "BASE_BRANCH": "main",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "WORK_BRANCH": "fix/audit-cycle-tests",
        },
    ),
    (
        "prompt.audit.docs-cycle",
        "audit-docs-cycle",
        "Legacy cyclic docs audit (prefer audit-cycle-docs)",
        {
            "N": "10",
            "SCOPE": "README.md docs/",
            "MODE": "full",
            "LANGUAGE": "ru",
            "AUDIT_MODE": "full",
            "INCLUDE_PIPELINE": "true",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MAX_ISSUES_PER_ITERATION": "5",
            "BASE_BRANCH": "main",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "WORK_BRANCH": "fix/audit-docs-cycle",
        },
    ),
    (
        "prompt.audit.dual-agent-cycle",
        "audit-dual-agent-cycle",
        "Dual-agent auditor/planner cyclic pack",
        {
            "AUDIT_PROMPT_SOURCE": "prompt.audit.sequential-run",
            "OUTER_CYCLES": "1",
            "SCOPE": "src/bioetl/",
            "MODE": "full",
            "LANGUAGE": "ru",
            "CODERABBIT": "required-then-agent",
            "PARALLEL_STREAMS": "2",
            "MAX_TASKS": "8",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "BASE_BRANCH": "main",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "WORK_BRANCH": "fix/audit-dual-agent-cycle",
        },
    ),
    (
        "prompt.audit.repo-tree-cycle",
        "audit-repo-tree-cycle",
        "Cyclic repository-tree hygiene audit then issues then fix",
        {
            "N": "10",
            "SCOPE": ".",
            "MODE": "full",
            "LANGUAGE": "ru",
            "AUDIT_MODE": "full",
            "INCLUDE_PIPELINE": "true",
            "STRICT_UNTRACKED": "true",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MAX_ISSUES_PER_ITERATION": "5",
            "BASE_BRANCH": "main",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "WORK_BRANCH": "fix/audit-repo-tree-cycle",
        },
    ),
    (
        "prompt.audit.sequential-run",
        "audit-sequential-run",
        "Sequential 1-10 cycle-pack run with ISSUE/FIX/CLOSE after each card",
        {
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "BASE_BRANCH": "main",
            "WORK_BRANCH": "fix/audit-seq",
            "LANGUAGE": "ru",
            "N": "1",
            "MODE": "full",
            "DEPTH": "full",
            "INCLUDE_PIPELINE": "true",
            "MONITORING": "true",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MAX_ISSUES_PER_STEP": "8",
            "REQUIRE_GH_TRACKING": "true",
            "CODERABBIT": "required-then-agent",
        },
    ),
    (
        "prompt.audit.tech-debt-cycle",
        "audit-tech-debt-cycle",
        "Legacy cyclic tech-debt audit (prefer audit-cycle-tech-debt)",
        {
            "N": "10",
            "SCOPE": "src/bioetl/ configs/quality/",
            "MODE": "full",
            "LANGUAGE": "ru",
            "AUDIT_MODE": "full",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MAX_ISSUES_PER_ITERATION": "5",
            "BASE_BRANCH": "main",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "WORK_BRANCH": "fix/audit-tech-debt-cycle",
        },
    ),
    (
        "prompt.audit.tests-cycle",
        "audit-tests-cycle",
        "Legacy cyclic tests audit (prefer audit-cycle-tests)",
        {
            "N": "10",
            "SCOPE": "tests/",
            "MODE": "full",
            "LANGUAGE": "ru",
            "LANE": "unit",
            "AUDIT_MODE": "full",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MAX_ISSUES_PER_ITERATION": "5",
            "BASE_BRANCH": "main",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "WORK_BRANCH": "fix/audit-tests-cycle",
        },
    ),
    (
        "prompt.observability.dashboard-audit-cycle",
        "dashboard-audit-cycle",
        "Cyclic Grafana audit contours then issues then fix/re-verify",
        {
            "N": "20",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "BASE_BRANCH": "main",
            "WORK_BRANCH": "fix/dashboard-audit-cycle",
            "SCOPE": "grafana/dashboards",
            "MODE": "full",
            "DEPTH": "full",
            "AUDIT_MODE": "full",
            "CONTOURS": "render,density-area,density-scalar,fill,fit,reflow,visual,layout,data,copy,safety",
            "VIEWPORT": "1366x768",
            "THEME": "dark",
            "ZOOM": "100",
            "USER_ROLE": "operator",
            "MONITORING": "true",
            "INCLUDE_PIPELINE": "true",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MAX_ISSUES_PER_ITERATION": "10",
            "LANGUAGE": "ru",
        },
    ),
    (
        "prompt.observability.dashboard-first-window-noscroll",
        "dashboard-first-window-noscroll",
        "Ultimate first-window no-scroll: test, fix, retest until consecutive greens",
        {
            "TASK": "ultimate first-window no-scroll on seven UIDs",
            "MODE": "full",
            "SCOPE": "grafana/dashboards",
            "WORK_BRANCH": "fix/dash-first-window-noscroll",
            "LANGUAGE": "ru",
            "MONITORING": "true",
            "VIEWPORT": "1366x768",
            "THEME": "dark,light",
            "ZOOM": "100",
            "N": "10",
            "CONSECUTIVE_PASS": "5",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
        },
    ),
    (
        "prompt.observability.dashboard-full-cycle",
        "dashboard-full-cycle",
        "Unified N=10 dashboard audit then GH issues then fix-to-close",
        {
            "N": "10",
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "BASE_BRANCH": "main",
            "WORK_BRANCH": "fix/dash-full-cycle",
            "SCOPE": "grafana/dashboards",
            "MODE": "full",
            "DEPTH": "full",
            "LANGUAGE": "ru",
            "MONITORING": "true",
            "THEME": "dark,light",
            "ZOOM": "100",
            "VIEWPORT": "1366x768",
            "USER_ROLE": "operator",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MAX_ISSUES_PER_ITERATION": "10",
        },
    ),
    (
        "prompt.observability.dashboard-panel-audit",
        "dashboard-panel-audit",
        "Five-phase panel audit: inventory, render, issues, fix, closeout",
        {
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "BASE": "main",
            "WORK_BRANCH": "fix/dashboard-panel-audit",
            "SCOPE": "grafana/dashboards",
            "MODE": "full",
            "CYCLE_COUNT": "1",
            "PHASES": "5",
            "AUDIT_MODE": "full",
            "REQUIRE_GH_TRACKING": "false",
            "LANGUAGE": "ru",
            "MONITORING": "true",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
        },
    ),
    (
        "prompt.observability.sequential-run",
        "observability-sequential-run",
        "Sequential observability folder run with issue/close gates",
        {
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "BASE": "origin/main",
            "WORK_BRANCH": "fix/observability-seq",
            "SCOPE": "grafana/dashboards",
            "LANGUAGE": "ru",
            "MODE": "full",
            "MONITORING": "true",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MAX_ISSUES_PER_STEP": "8",
            "REQUIRE_GH_TRACKING": "true",
        },
    ),
    (
        "prompt.tests.cycle",
        "tests-cycle",
        "Cyclic pytest run, triage, fix, retest, delta",
        {
            "REPO": "SatoryKono/BioactivityDataAcquisition",
            "BASE": "main",
            "WORK_BRANCH": "fix/test-cycle",
            "SCOPE": "all",
            "LANE": "full",
            "MODE": "full",
            "CYCLE_COUNT": "5",
            "MAX_FIXES_PER_CYCLE": "5",
            "PYTEST_EXTRA": "",
            "REQUIRE_GH_TRACKING": "false",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
            "MONITORING": "true",
            "LANGUAGE": "ru",
        },
    ),
    (
        "prompt.tests.fix-retest",
        "tests-fix-retest",
        "Narrow failing-test loop: run, fix, retest until green or blocked",
        {
            "SCOPE": "tests/",
            "LANE": "unit",
            "LANGUAGE": "ru",
            "MODE": "full",
            "WORK_BRANCH": "fix/tests-fix-retest",
            "MAX_FIXES": "8",
            "MONITORING": "true",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
        },
    ),
    (
        "prompt.tests.speed-optimization",
        "tests-speed-optimization",
        "Cyclic test-speed loop: measure, shrink, retest, no coverage loss",
        {
            "SCOPE": "tests/",
            "LANGUAGE": "ru",
            "MODE": "full",
            "WORK_BRANCH": "fix/tests-speed",
            "CYCLE_COUNT": "3",
            "MONITORING": "true",
            "ALLOW_ISSUE_WRITE": "true",
            "ALLOW_PUSH": "true",
            "ALLOW_MERGE": "false",
            "ALLOW_CLOSE": "true",
        },
    ),
]


def normalize_defaults(defaults: dict[str, str]) -> dict[str, str]:
    """Operator-run defaults: MONITORING=true, ALLOW_*=true, ALLOW_MERGE=false, MODE=full."""
    out = dict(defaults)
    out["MODE"] = "full"
    out["MONITORING"] = "true"
    out["ALLOW_ISSUE_WRITE"] = "true"
    out["ALLOW_PUSH"] = "true"
    out["ALLOW_CLOSE"] = "true"
    out["ALLOW_MERGE"] = "false"
    for key in list(out):
        if key.startswith("ALLOW_") and key != "ALLOW_MERGE":
            out[key] = "true"
    return out


def rhail_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render(
    name: str, prompt_id: str, description: str, defaults: dict[str, str]
) -> str:
    param_lines = "\n".join(f"- `{key}` = `{value}`" for key, value in defaults.items())
    baked = "\\n".join(f"{key}={value}" for key, value in defaults.items())
    scope = defaults.get("SCOPE", ".")
    n = defaults.get("N", defaults.get("CYCLE_COUNT", "1"))
    language = defaults.get("LANGUAGE", "ru")
    mode = defaults.get("MODE", "full")
    monitoring = defaults.get("MONITORING", "true")
    work_branch = defaults.get("WORK_BRANCH", f"fix/{name}")
    lines = [
        "let meta = #{",
        f'    name: "{name}",',
        f'    description: "{rhail_escape(description)}",',
        f'    when_to_use: "Run {prompt_id} with baked defaults; no args required",',
        "    phases: [",
        '        #{ title: "Audit", detail: "execute the prompt card against SCOPE" },',
        '        #{ title: "Issues", detail: "open or reuse GitHub issues for PROVEN findings" },',
        '        #{ title: "Fix", detail: "remediate until close or BLOCKED" },',
        "    ],",
        "};",
        "",
        'let scope = "' + rhail_escape(scope) + '";',
        'let n = "' + rhail_escape(str(n)) + '";',
        'let language = "' + rhail_escape(language) + '";',
        'let mode = "' + rhail_escape(mode) + '";',
        'let monitoring = "' + rhail_escape(monitoring) + '";',
        'let work_branch = "' + rhail_escape(work_branch) + '";',
        "if args != () {",
        "    if args.scope != () { scope = args.scope; }",
        "    if args.n != () { n = args.n.to_string(); }",
        "    if args.language != () { language = args.language; }",
        "    if args.mode != () { mode = args.mode; }",
        "    if args.monitoring != () { monitoring = args.monitoring; }",
        "    if args.work_branch != () { work_branch = args.work_branch; }",
        "}",
        "",
        'let baked = "' + rhail_escape(baked) + '";',
        "",
        'phase("Audit");',
        f'let prompt = "Execute BioETL operator-paste card {prompt_id}.\\n";',
        'prompt += "Windows Python: .\\\\.venv-win\\\\Scripts\\\\python.exe\\n";',
        f'prompt += "Render first: python -m scripts.ai.prompts render {prompt_id}\\n";',
        'prompt += "Then follow the rendered card. Do not invent DASH-* or REQ-* IDs.\\n";',
        'prompt += "Never commit to main. Never edit .env. Never raise tech-debt budgets.\\n";',
        'prompt += "Never start docker-compose.monitoring.yml unless MONITORING=true.\\n";',
        'prompt += "Use grep/read_file/run_terminal_command; do not answer from memory.\\n";',
        'prompt += "LANGUAGE=" + language + " MODE=" + mode + " N=" + n + "\\n";',
        'prompt += "SCOPE=" + scope + " WORK_BRANCH=" + work_branch + " MONITORING=" + monitoring + "\\n";',
        'prompt += "Baked defaults (override only if args provided):\\n" + baked + "\\n";',
        'prompt += "Write reports under reports/audit/. Return a short Russian summary with gate PASS|WARN|BLOCK, issue numbers, and artifact paths.\\n";',
        'prompt += "If no PROVEN findings after reading the checkout, say so explicitly.\\n";',
        "",
        'let audit = agent(prompt, #{ label: "audit", capability_mode: "all" });',
        "if audit == () || !audit.success {",
        '    complete(#{ summary: "audit agent failed", prompt_id: "'
        + prompt_id
        + '", gate: "BLOCK" });',
        "}",
        "",
        'phase("Issues");',
        f'let issues_prompt = "Continue the same BioETL task for {prompt_id}.\\n";',
        'issues_prompt += "From the audit just performed, search GitHub open AND closed issues and open PRs.\\n";',
        'issues_prompt += "Create at most MAX_ISSUES_PER_ITERATION issues for PROVEN P0-P2 findings.\\n";',
        'issues_prompt += "One issue per uid-or-path + requirement_id + root_cause. Dedup.\\n";',
        'issues_prompt += "If ALLOW_ISSUE_WRITE is false, emit payloads only, do not gh issue create.\\n";',
        'issues_prompt += "Baked defaults:\\n" + baked + "\\n";',
        'issues_prompt += "Return issue numbers created or reused, or none.\\n";',
        'let issues = agent(issues_prompt, #{ label: "issues", capability_mode: "all", resume_from: audit.agent_id });',
        "",
        'phase("Fix");',
        f'let fix_prompt = "Continue the same BioETL task for {prompt_id}.\\n";',
        'fix_prompt += "Fix PROVEN defects on WORK_BRANCH=" + work_branch + " (never main).\\n";',
        'fix_prompt += "Re-run focused tests. Close issues only vs origin/main or explicit PR-head acceptance.\\n";',
        'fix_prompt += "Do not raise debt budgets. Do not edit .env. ALLOW_MERGE false means do not merge.\\n";',
        'fix_prompt += "Baked defaults:\\n" + baked + "\\n";',
        'fix_prompt += "Return gate PASS|WARN|BLOCK, remaining open issues, and artifact paths.\\n";',
        "let resume_id = audit.agent_id;",
        "if issues != () && issues.success { resume_id = issues.agent_id; }",
        'let fix = agent(fix_prompt, #{ label: "fix", capability_mode: "all", resume_from: resume_id });',
        "",
        'let summary = "workflow " + "' + name + '" + " finished";',
        'if fix != () && fix.success && type_of(fix.output) == "string" { summary = fix.output; }',
        'else if issues != () && issues.success && type_of(issues.output) == "string" { summary = issues.output; }',
        'else if audit != () && audit.success && type_of(audit.output) == "string" { summary = audit.output; }',
        'let report = write_scratch_file("report.md", summary);',
        'complete(#{ path: report, prompt_id: "'
        + prompt_id
        + '", summary: summary });',
        "",
    ]
    header = (
        "// Auto-generated zero-arg wrapper for "
        + prompt_id
        + "\n// Defaults:\n"
        + "\n".join("//   " + line for line in param_lines.split("\n"))
        + "\n\n"
    )
    return header + "\n".join(lines)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for prompt_id, name, description, defaults in CARDS:
        path = OUT / f"{name}.rhai"
        baked = normalize_defaults(defaults)
        path.write_text(render(name, prompt_id, description, baked), encoding="utf-8")
        print(
            "wrote", path, "lines", len(path.read_text(encoding="utf-8").splitlines())
        )


if __name__ == "__main__":
    main()
