"""Rendering, artifact persistence, and CLI for debt-governance gates."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any


def render_markdown(payload: dict[str, object]) -> str:
    summary = payload["summary"]
    assert isinstance(summary, dict)
    gates = payload["gates"]
    assert isinstance(gates, list)
    lines = [
        "# Debt Governance Gates",
        "",
        "> Generated by `python -m scripts.engineering.qa report-debt-governance-gates`.",
        "",
        f"- gate_count: {summary['gate_count']}",
        f"- pass_count: {summary['pass_count']}",
        f"- warn_count: {summary['warn_count']}",
        f"- fail_count: {summary['fail_count']}",
        f"- release_gate_status: `{summary['release_gate_status']}`",
        "- architecture_quality_scorecard_integral_score: "
        f"`{summary['architecture_quality_scorecard_integral_score']}`",
        "- architecture_quality_scorecard_interpretation: "
        f"`{summary['architecture_quality_scorecard_interpretation']}`",
        "",
        "| gate | status | metric | current | limit | source |",
        "| --- | --- | --- | ---: | ---: | --- |",
    ]
    for gate in gates:
        assert isinstance(gate, dict)
        lines.append(
            "| `{name}` | `{status}` | `{metric}` | `{current}` | `{limit}` | `{source}` |".format(
                name=gate["name"],
                status=gate["status"],
                metric=gate["metric"],
                current=gate["current"],
                limit=gate["limit"],
                source=gate["source_artifact"],
            )
        )
    lines.append("")
    return "\n".join(lines)


def _write_artifacts(
    payload: dict[str, object],
    *,
    json_out: Path,
    md_out: Path,
    root: Path | None = None,
) -> None:
    from scripts.engineering.common.repo_paths import REPO_ROOT, resolve_output_path

    base = root if root is not None else REPO_ROOT
    json_out = resolve_output_path(json_out, root=base)
    md_out = resolve_output_path(md_out, root=base)
    json_out.parent.mkdir(parents=True, exist_ok=True)
    md_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(  # NOSONAR - path confined by resolve_output_path
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    md_out.write_text(
        render_markdown(payload), encoding="utf-8"
    )  # NOSONAR - path confined by resolve_output_path


def _artifact_staleness_errors(
    payload: dict[str, object],
    *,
    json_out: Path,
    md_out: Path,
) -> list[str]:
    """Return errors when committed debt-governance artifacts drift from payload."""
    errors: list[str] = []
    expected_json = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    expected_md = render_markdown(payload)
    if (
        not json_out.exists()
        or json_out.read_text(encoding="utf-8")  # NOSONAR - path confined
        != expected_json
    ):
        errors.append(f"Debt governance gate JSON artifact is stale: {json_out}")
    if (
        not md_out.exists()
        or md_out.read_text(encoding="utf-8")  # NOSONAR - path confined
        != expected_md
    ):
        errors.append(f"Debt governance gate Markdown artifact is stale: {md_out}")
    return errors


def _failing_gate_errors(
    summary: dict[str, object], payload: dict[str, object]
) -> list[str]:
    """Return human-readable errors for currently failing debt-governance gates."""
    fail_count = int(summary["fail_count"])
    if fail_count <= 0:
        return []
    errors: list[str] = []
    failing = summary.get("failing_gates") or []
    detail = ", ".join(str(name) for name in failing) if failing else "unknown"
    errors.append(f"Debt governance gates have {fail_count} failing gate(s): {detail}")
    gates = payload.get("gates")
    if not isinstance(gates, list):
        return errors
    for gate in gates:
        if not isinstance(gate, dict) or gate.get("status") != "fail":
            continue
        name = gate.get("name")
        current = gate.get("current")
        remediation = gate.get("remediation")
        errors.append(f"  - {name}: current={current!r}; {remediation}")
    return errors


def _check_artifacts(
    payload: dict[str, object],
    *,
    json_out: Path,
    md_out: Path,
    compare_artifacts: bool = True,
    root: Path | None = None,
) -> list[str]:
    from scripts.engineering.common.repo_paths import REPO_ROOT, resolve_output_path

    base = root if root is not None else REPO_ROOT
    json_out = resolve_output_path(json_out, root=base)
    md_out = resolve_output_path(md_out, root=base)
    errors: list[str] = []
    if compare_artifacts:
        errors.extend(
            _artifact_staleness_errors(payload, json_out=json_out, md_out=md_out)
        )
    summary = payload["summary"]
    assert isinstance(summary, dict)
    errors.extend(_failing_gate_errors(summary, payload))
    return errors


def main(argv: list[str] | None = None) -> int:
    # Lazy imports to avoid circular import when this module is loaded via
    # report_debt_governance_gates as __main__
    from scripts.engineering.qa.report_debt_governance_gates import (
        _parse_args,
        build_payload,
    )
    from memory.proof import emit_receipt_from_environment

    args = _parse_args(argv)
    repo_root = Path(args.repo_root).resolve()
    payload = build_payload(
        repo_root=repo_root,
        changed_from_ref=args.changed_from_ref,
    )
    json_out = Path(args.json_out)
    md_out = Path(args.md_out)

    if args.check:
        errors = _check_artifacts(
            payload,
            json_out=json_out,
            md_out=md_out,
            compare_artifacts=args.changed_from_ref is None,
            root=repo_root,
        )
        emit_receipt_from_environment(
            repo_root=repo_root,
            producer="debt_governance_gates",
            evidence_kind="debt",
            command="python -m scripts.engineering.qa report-debt-governance-gates",
            status="fail" if errors else "pass",
            exit_code=1 if errors else 0,
            output_path=json_out,
        )
        if errors:
            for error in errors:
                print(error, file=sys.stderr)
            return 1
        return 0

    if args.update:
        _write_artifacts(payload, json_out=json_out, md_out=md_out, root=repo_root)
        emit_receipt_from_environment(
            repo_root=repo_root,
            producer="debt_governance_gates",
            evidence_kind="debt",
            command="python -m scripts.engineering.qa report-debt-governance-gates",
            status="pass",
            exit_code=0,
            output_path=json_out,
        )
        return 0

    print(json.dumps(payload, indent=2, sort_keys=True))
    return 0
