#!/usr/bin/env python3
"""Generate/check the published reproducibility support matrix."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
DEFAULT_OUTPUT = (
    ROOT / "docs" / "02-architecture" / "policies" / "reproducibility-support-matrix.md"
)

if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

from bioetl.domain.control_plane.reproducibility_profiles import (  # noqa: E402
    published_reproducibility_family_inventory,
)


_HEADER = """# Reproducibility Support Matrix (Auto-Generated)

> Generated by `scripts/engineering/qa/generate_reproducibility_support_matrix.py`.
> Do not edit manually.
> Exact replay is supported only inside the published boundary shown here and only
> when runtime diagnostics also prove full immutable input snapshots, code/config
> provenance, dependency-lock provenance, and produced artifact trace anchors.
> Supported source families may also promote a completed live capture with
> ledger-materialized immutable snapshots into replayable parent evidence.
> Historical live runs without immutable snapshot evidence remain outside that
> stronger claim until explicit `input_snapshot_published` ledger evidence
> materializes a bounded parent snapshot envelope.
> A broader certified historical replay tranche is also supported when explicit
> certification evidence is appended into the ledger. Historical source runs
> require certified immutable source snapshot backfill; historical composite
> runs require certified source lineage before composite replay-envelope
> certification.
> Replay-supported families are also protected by a no-new-uncertifiable-runs
> evidence floor so lifecycle cleanup does not delete retained replay evidence
> before that broader historical tranche can be exercised.

"""


def _snapshot_requirement(row: dict[str, object]) -> str:
    contract = str(row["replay_family_contract"])
    if contract == "snapshot_backed_exact_replay":
        return "full_source_snapshot_envelope"
    if contract == "composite_snapshot_backed_exact_replay":
        return "full_composite_snapshot_envelope"
    return "not_exact_replay_supported"


def _lineage_closure(row: dict[str, object]) -> str:
    if bool(row["lineage_closure_supported"]):
        return "closed"
    if row["execution_context"] == "composite":
        return "lifecycle_trace_only"
    return "not_supported"


def _diagnostics_surface(row: dict[str, object]) -> str:
    diagnostics = [
        "replay_readiness_verdict",
        "replay_capability",
        "replay_occurrence_kind",
        "historical_live_run_upgrade_state",
        "exact_replay_blockers",
        "source_posture",
        "manifest_id",
        "execution_fingerprint",
        "input_snapshot_identity_fingerprint",
        "produced_artifact_trace",
    ]
    if row["execution_context"] == "composite":
        diagnostics.append("composite_dossier_projection")
    return ", ".join(f"`{item}`" for item in diagnostics)


def _post_capture_parent_state(row: dict[str, object]) -> str:
    if bool(row["post_capture_replayable_parent_supported"]):
        return "supported"
    return "not_applicable"


def _historical_upgrade_policy(row: dict[str, object]) -> str:
    return str(row["historical_live_run_upgrade_policy"])


def _broader_scope_policy(row: dict[str, object]) -> str:
    return str(row["broader_historical_exact_replay_policy"])


def _broader_scope_boundary(row: dict[str, object]) -> str:
    return str(row["broader_historical_exact_replay_boundary"] or "n/a")


def _matrix_rows() -> list[dict[str, object]]:
    return sorted(
        published_reproducibility_family_inventory(),
        key=lambda row: (
            str(row["execution_context"]),
            str(row["family"] or ""),
        ),
    )


def build_reproducibility_support_matrix_markdown() -> str:
    """Return the deterministic generated support matrix markdown."""
    lines = [_HEADER.rstrip(), ""]
    lines.extend(
        [
            "| Family | Context | Support State | Strict Exact Replay | Post-Capture Parent | Parent Boundary | Historical Upgrade Policy | Historical Upgrade Boundary | Broader Scope Policy | Broader Scope Boundary | Required Profile | Snapshot Requirement | Lineage Closure | Contract | Blocker Reason | Diagnostics |",
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for row in _matrix_rows():
        lines.append(
            "| "
            f"`{row['family']}` | "
            f"`{row['execution_context']}` | "
            f"`{row['support_state']}` | "
            f"`{str(row['strict_exact_replay_supported']).lower()}` | "
            f"`{_post_capture_parent_state(row)}` | "
            f"`{row['post_capture_replayable_parent_boundary'] or 'n/a'}` | "
            f"`{_historical_upgrade_policy(row)}` | "
            f"`{row['historical_live_run_upgrade_boundary'] or 'n/a'}` | "
            f"`{_broader_scope_policy(row)}` | "
            f"`{_broader_scope_boundary(row)}` | "
            f"`{row['default_required_persistence_profile']}` | "
            f"`{_snapshot_requirement(row)}` | "
            f"`{_lineage_closure(row)}` | "
            f"`{row['replay_family_contract']}` | "
            f"`{row['reason']}` | "
            f"{_diagnostics_surface(row)} |"
        )
    return "\n".join(lines) + "\n"


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate/check the reproducibility support matrix."
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="Fail when output drifts.")
    mode.add_argument("--update", action="store_true", help="Rewrite output.")
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT),
        help="Generated support matrix markdown path.",
    )
    return parser.parse_args()


def _resolve_output(raw_output: str) -> Path:
    output = Path(raw_output)
    if not output.is_absolute():
        output = ROOT / output
    resolved_root = ROOT.resolve()
    resolved_output = output.resolve()
    if (
        resolved_output != resolved_root
        and resolved_root not in resolved_output.parents
    ):
        raise ValueError(f"refusing to write outside repository: {resolved_output}")
    return resolved_output


def main() -> int:
    """Run the generator/checker CLI."""
    args = _parse_args()
    output = _resolve_output(args.output)
    generated = build_reproducibility_support_matrix_markdown()
    if args.update:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(generated, encoding="utf-8")
        print(f"[OK] Updated {output}")
        return 0
    if args.check:
        current = output.read_text(encoding="utf-8") if output.exists() else ""
        if current == generated:
            print(f"[OK] Reproducibility support matrix is current: {output}")
            return 0
        print(f"[FAIL] Reproducibility support matrix drift detected: {output}")
        print("Run with --update to refresh generated matrix.")
        return 1
    print(generated, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
