#!/usr/bin/env python3
"""Generate/check hotspot-family baseline artifacts for RF-06 governance."""

from __future__ import annotations

import argparse
import json
from datetime import date
from pathlib import Path

try:
    from scripts.engineering.qa.hotspot_family_metrics import (
        PROJECT_ROOT,
        SCORECARD_PATH,
        collect_hotspot_family_metrics,
        load_scorecard,
    )
except ModuleNotFoundError:  # pragma: no cover - direct script execution fallback
    try:
        # Try relative import for direct script execution
        from hotspot_family_metrics import (  # type: ignore[no-redef]
            PROJECT_ROOT,
            SCORECARD_PATH,
            collect_hotspot_family_metrics,
            load_scorecard,
        )
    except ModuleNotFoundError:
        # Try absolute import with path adjustment
        import sys
        from pathlib import Path
        sys.path.insert(0, str(Path(__file__).parent))
        from hotspot_family_metrics import (  # type: ignore[no-redef]
            PROJECT_ROOT,
            SCORECARD_PATH,
            collect_hotspot_family_metrics,
            load_scorecard,
        )

DEFAULT_JSON_OUTPUT = PROJECT_ROOT / "reports/quality/hotspot-family-baseline.json"
DEFAULT_MD_OUTPUT = PROJECT_ROOT / "reports/quality/hotspot-family-baseline.md"


def _resolve_snapshot_date(scorecard: dict[str, object]) -> str:
    report_only = scorecard.get("report_only_hotspot_families", {})
    if isinstance(report_only, dict):
        snapshot_date = report_only.get("snapshot_date")
        if isinstance(snapshot_date, str) and snapshot_date.strip():
            return snapshot_date
    return date.today().isoformat()


def _build_json_payload(
    *,
    snapshot_date: str,
    metrics: list[dict[str, object]],
) -> dict[str, object]:
    return {
        "summary": {
            "snapshot_date": snapshot_date,
            "families": len(metrics),
            "scorecard": str(SCORECARD_PATH.relative_to(PROJECT_ROOT)),
        },
        "families": metrics,
    }


def _render_markdown(
    *,
    snapshot_date: str,
    metrics: list[dict[str, object]],
) -> str:
    lines = [
        "# Hotspot Family Baseline",
        "",
        "> Generated by `python -m scripts.engineering.qa report-family-baseline`.",
        "> Use this artifact as the reviewed RF-06 family baseline for non-regression checks.",
        "",
        f"- snapshot_date: `{snapshot_date}`",
        f"- families: `{len(metrics)}`",
        "",
        "| Family | Files | Total LOC | Files >=250 LOC | Helper ratio | Duplication | Max fan-in | Max fan-in module | Budgets |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | --- | --- |",
    ]

    for family in metrics:
        budgets = family.get("bounded_growth_budgets", {})
        budget_text = (
            ", ".join(f"{key}={value}" for key, value in sorted(budgets.items()))
            if isinstance(budgets, dict) and budgets
            else "-"
        )
        duplication = family.get("duplication_clusters")
        duplication_text = str(duplication) if duplication is not None else "-"
        lines.append(
            "| "
            f"`{family['name']}` | "
            f"{family['files']} | "
            f"{family['total_loc']} | "
            f"{family['files_ge_250_loc']} | "
            f"{family['helper_function_ratio']:.3f} | "
            f"{duplication_text} | "
            f"{family['max_internal_fan_in']} | "
            f"`{family['max_internal_fan_in_module'] or '-'}` | "
            f"`{budget_text}` |"
        )

    lines.append("")
    return "\n".join(lines)


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _check_file_sync(path: Path, expected: str) -> bool:
    if not path.exists():
        print(f"[drift] missing file: {path.relative_to(PROJECT_ROOT)}")
        return False
    actual = path.read_text(encoding="utf-8")
    if actual == expected:
        return True
    print(f"[drift] mismatch: {path.relative_to(PROJECT_ROOT)}")
    return False


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate/check RF-06 hotspot-family baseline artifacts."
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        action="store_true",
        help="Fail if committed baseline artifacts differ from generated output.",
    )
    mode.add_argument(
        "--update",
        action="store_true",
        help="Write generated baseline artifacts to disk (default mode).",
    )
    parser.add_argument(
        "--json-output",
        type=Path,
        default=DEFAULT_JSON_OUTPUT,
        help="JSON output path.",
    )
    parser.add_argument(
        "--md-output",
        type=Path,
        default=DEFAULT_MD_OUTPUT,
        help="Markdown output path.",
    )
    parser.add_argument(
        "--active-only",
        action="store_true",
        help="Only include active hotspot families.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    scorecard = load_scorecard()
    snapshot_date = _resolve_snapshot_date(scorecard)
    metrics = [
        item.to_dict()
        for item in collect_hotspot_family_metrics(
            scorecard=scorecard,
            active_only=args.active_only,
        )
    ]
    json_payload = _build_json_payload(snapshot_date=snapshot_date, metrics=metrics)
    json_text = json.dumps(json_payload, ensure_ascii=False, indent=2) + "\n"
    markdown = _render_markdown(snapshot_date=snapshot_date, metrics=metrics)

    if args.check:
        json_ok = _check_file_sync(args.json_output, json_text)
        md_ok = _check_file_sync(args.md_output, markdown)
        if json_ok and md_ok:
            print("[ok] hotspot-family baseline artifacts are up to date")
            return 0
        hint = "python -m scripts.engineering.qa report-family-baseline"
        if args.active_only:
            hint += " --active-only"
        hint += " --update"
        print(f"[hint] run: {hint}")
        return 1

    _write_text(args.json_output, json_text)
    _write_text(args.md_output, markdown)
    print(
        "[updated] wrote hotspot-family baseline artifacts:\n"
        f"  - {args.json_output.relative_to(PROJECT_ROOT)}\n"
        f"  - {args.md_output.relative_to(PROJECT_ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
