"""
Common type definitions and Value Objects for the application.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum, StrEnum
from typing import Any, TypeVar

# Generic type for Pandas DataFrame
DataFrame = TypeVar("DataFrame")


@dataclass(frozen=True)
class PreflightReport:
    """Report generated by preflight checks."""

    status: str
    details: dict[str, Any]
    checked_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class IsoformNote:
    """Represents a note associated with a specific isoform."""

    isoform_id: str
    note: str


class DataLayer(StrEnum):
    """Data layer enumeration."""

    BRONZE = "bronze"
    SILVER = "silver"
    GOLD = "gold"


class ProcessingStatus(StrEnum):
    """Processing status enumeration."""

    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class ValidationLevel(Enum):
    """Validation strictness level."""

    STRICT = "strict"
    LENIENT = "lenient"
    NONE = "none"
