"""P1 #9808 — deterministic compile (DOCX гл.4.3)."""

from __future__ import annotations

import hashlib
import re

import pytest

from scripts.ai.prompts.compile import compile_one, sha8

pytestmark = pytest.mark.unit


def _body_from_rendered(rendered: str) -> str:
    lines = rendered.splitlines()
    body_start = 0
    for idx, line in enumerate(lines):
        if line.startswith("<!-- params:"):
            body_start = idx + 1
            break
    body = "\n".join(lines[body_start:]).lstrip("\n")
    if not body.endswith("\n"):
        body += "\n"
    return body


def test_compile_deterministic_same_inputs_byte_identical() -> None:
    a = compile_one("docs", "audit-readonly")
    b = compile_one("docs", "audit-readonly")
    assert a["error"] is None, a["error"]
    assert b["error"] is None, b["error"]
    assert a["rendered_text"] == b["rendered_text"]
    assert a["prompt_sha8"] == b["prompt_sha8"]


def test_compile_prompt_sha8_matches_body_hash() -> None:
    result = compile_one("docs", "audit-readonly")
    assert result["error"] is None
    rendered: str = result["rendered_text"]  # type: ignore[assignment]
    prompt_sha8: str = result["prompt_sha8"]  # type: ignore[assignment]
    body = _body_from_rendered(rendered)
    assert sha8(body.encode("utf-8")) == prompt_sha8
    assert hashlib.sha256(body.encode("utf-8")).hexdigest()[:8] == prompt_sha8


def test_different_profile_changes_sha() -> None:
    a = compile_one("docs", "audit-readonly")
    b = compile_one("docs", "full-write")
    assert a["error"] is None
    assert b["error"] is None
    assert a["prompt_sha8"] != b["prompt_sha8"]
    assert a["rendered_text"] != b["rendered_text"]


def test_provenance_header_present() -> None:
    result = compile_one("docs", "audit-readonly")
    assert result["error"] is None
    text: str = result["rendered_text"]  # type: ignore[assignment]
    assert text.startswith("<!-- GENERATED by scripts/ai/prompts/compile.py")
    prov = re.search(r"<!-- provenance:\s*(.*?)\s*-->", text, re.S)
    assert prov is not None, "provenance header missing"
    fields = dict(part.split("=", 1) for part in prov.group(1).split() if "=" in part)
    for key in ("kernel_sha8", "overlay_sha8", "prompt_sha8", "profile"):
        assert key in fields, f"provenance missing {key}"
    assert fields["profile"] == "audit-readonly"
    assert re.fullmatch(r"[a-f0-9]{8}", fields["prompt_sha8"])
    assert "<!-- params:" in text
