"""P0 Control Plane identity anchor specifications."""

from __future__ import annotations

from bioetl.interfaces.http.control_plane_identity.types import AnchorSpec

P0_ANCHOR_SPECS: tuple[AnchorSpec, ...] = (
    AnchorSpec(
        "P0",
        "run_id",
        "Run ID",
        "RunManifest.run_id; identity graph",
        "UUID v4",
        "Primary correlation anchor for manifest, ledger, logs, and traces.",
        "overview: short; details: full",
        True,
        "Run Manifest details; ledger by run_id; Loki/Tempo links",
        "FAILING",
    ),
    AnchorSpec(
        "P0",
        "manifest_id",
        "Manifest ID",
        "RunManifest.manifest_id; identity graph",
        "opaque string / UUID-like",
        "Immutable control-plane artifact anchor.",
        "overview: short; details: full",
        True,
        "Manifest JSON; run-manifest CLI show; ledger events",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "pipeline_name",
        "Pipeline",
        "RunManifest.pipeline_name",
        "snake_case",
        "Shows which pipeline was executed.",
        "full in card/table",
        False,
        "Pipeline dashboard; manifest filter",
        "FAILING",
    ),
    AnchorSpec(
        "P0",
        "provider_entity",
        "Provider / Entity",
        "RunManifest.provider + RunManifest.entity",
        "provider.entity",
        "Fixes dataset and contract scope.",
        "full in card/table",
        False,
        "Dataset lineage; contract registry entry",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "runtime_mode",
        "Runtime Mode",
        "RunManifest.run_type + runtime_config/launch_context flags",
        "run_type + flags",
        "Shows the runtime mode for the launch.",
        "overview badge; details tuple",
        False,
        "Manifest runtime_config and launch_context",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "execution_fingerprint",
        "Execution FP",
        "RunManifest.execution_fingerprint; identity graph",
        "sha256 hex / opaque fingerprint",
        "Semantic reproducibility and compatibility anchor.",
        "overview: short; details: full",
        True,
        "Identity graph; manifest diff; replay diagnostics",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "git_commit",
        "Git Commit",
        "RunManifest.code_provenance.git_commit",
        "git SHA",
        "Shows which code produced the result.",
        "overview: short; details: full",
        True,
        "Repository commit / release notes",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "pipeline_version",
        "Pipeline Version",
        "RunManifest.code_provenance.pipeline_version",
        "semver / string",
        "Pipeline/config contract version.",
        "full",
        False,
        "Pipeline spec / changelog",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "effective_config_hash",
        "Effective Config Hash",
        "RunCodeProvenance.effective_config_hash; checkpoint metadata",
        "sha256 hex",
        "Resolved config actually used by the run.",
        "overview: short; details: full",
        True,
        "Effective config artifact; config diff",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "effective_config_artifact_id",
        "Effective Config Artifact",
        "RunCodeProvenance.effective_config_artifact_id; base_summary",
        "artifact ref",
        "Direct handoff to resolved config.",
        "overview: short; details: full",
        True,
        "Resolved config artifact view",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "contract_ref",
        "Contract Ref",
        "RunCodeProvenance.contract_ref; contract registry",
        "provider.entity",
        "Gold/DQ contract scope.",
        "full",
        True,
        "Contract registry entry; Gold contract doc",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "contract_version",
        "Contract Version",
        "RunCodeProvenance.contract_version; contract registry",
        "semver",
        "Applied Gold/DQ contract version.",
        "full",
        False,
        "Contract registry / migration guide",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "contract_schema_hash",
        "Contract Schema Hash",
        "RunCodeProvenance.contract_schema_hash; registry identity.schema_hash",
        "sha256 hex",
        "Protects against schema drift.",
        "overview: short; details: full",
        True,
        "Contract artifact diff",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "input_snapshot_identity_fingerprint",
        "Input Snapshot FP",
        "RunManifest.source_refs[*].input_snapshots",
        "sha256 / opaque fingerprint",
        "Fixes the immutable input closure.",
        "overview: short; details: full",
        True,
        "Input snapshots details",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "input_snapshot_count",
        "Input Snapshots",
        "RunManifest.source_refs[*].input_snapshots",
        "integer + array",
        "Shows whether input closure was captured.",
        "count in overview; IDs in details",
        False,
        "Input snapshots table",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "replay_mode",
        "Replay / Backfill / Rebuild",
        "RunManifest.run_type + replay parentage",
        "enum / badge",
        "Shows whether the run is replay/backfill/rebuild/incremental.",
        "badge in overview",
        False,
        "Replay diagnostics",
        "INFO",
    ),
    AnchorSpec(
        "P0",
        "replay_of_run_id",
        "Parent Run ID",
        "RunManifest.replay_of_run_id; identity graph",
        "UUID",
        "Parent run for replay lineage.",
        "short when replay; full in details",
        True,
        "Parent manifest/ledger",
        "FAILING",
    ),
    AnchorSpec(
        "P0",
        "replay_of_manifest_id",
        "Parent Manifest ID",
        "RunManifest.replay_of_manifest_id; identity graph",
        "opaque id / UUID-like",
        "Parent manifest for replay lineage.",
        "short when replay; full in details",
        True,
        "Parent manifest details",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "checkpoint_anchor_status",
        "Checkpoint Anchors",
        "Checkpoint metadata compared with current runtime anchors",
        "OK / MISMATCH / MISSING / PARTIAL",
        "Shows whether persisted checkpoint anchors match current runtime anchors.",
        "status badge; pairwise table",
        False,
        "Checkpoint compatibility panel",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "composite_run_identity",
        "Composite Run Identity",
        "Composite checkpoint metadata; runtime config",
        "UUID / opaque run-scoped id",
        "Prevents resume across different composite executions.",
        "only for composite; full in details",
        True,
        "Composite checkpoint details",
        "FAILING",
    ),
    AnchorSpec(
        "P0",
        "identity_graph_complete",
        "Identity Graph",
        "identity evidence gaps",
        "boolean + gap count",
        "Single identity gap indicator.",
        "status badge plus gap count",
        False,
        "Identity gaps table",
        "DEGRADED",
    ),
)

__all__ = ["P0_ANCHOR_SPECS"]
