"""P1 Control Plane identity anchor specifications."""

from __future__ import annotations

from bioetl.interfaces.http.control_plane_identity.types import AnchorSpec

P1_ANCHOR_SPECS: tuple[AnchorSpec, ...] = (
    AnchorSpec(
        "P1",
        "resolved_config_hash",
        "Resolved Config Hash",
        "RunCodeProvenance.resolved_config_hash",
        "sha256 hex",
        "Resolved declarative config provenance.",
        "details only; compact short",
        True,
        "Manifest/config diff",
        "WARNING",
    ),
    AnchorSpec(
        "P1",
        "dq_policy_ref",
        "DQ Policy Ref",
        "RunCodeProvenance.dq_policy_ref; contract registry",
        "string ref",
        "Applied DQ policy.",
        "full in contract/DQ details",
        True,
        "DQ contract registry",
        "DEGRADED",
    ),
    AnchorSpec(
        "P1",
        "rule_bundle_version",
        "Rule Bundle",
        "RunCodeProvenance.rule_bundle_version; contract registry",
        "semver / string",
        "DQ rule bundle version.",
        "full",
        False,
        "DQ rule bundle / migration guide",
        "DEGRADED",
    ),
    AnchorSpec(
        "P1",
        "dq_contract_compatibility_hash",
        "DQ Compat Hash",
        "RunCodeProvenance.dq_contract_compatibility_hash",
        "sha256 hex",
        "Detects DQ compatibility surface drift.",
        "details only; compact short",
        True,
        "DQ contract diff",
        "WARNING",
    ),
    AnchorSpec(
        "P1",
        "source_refs",
        "Source Refs",
        "RunManifest.source_refs",
        "array provider/entity/query/input_snapshots",
        "External input lineage closure.",
        "count in summary; full nested table",
        True,
        "Source refs panel",
        "DEGRADED",
    ),
    AnchorSpec(
        "P1",
        "input_snapshot_ids",
        "Input Snapshot IDs",
        "RunManifest.source_refs[*].input_snapshots[*].snapshot_id",
        "array of opaque ids",
        "Immutable input snapshot list.",
        "details table only",
        True,
        "Input snapshot details",
        "DEGRADED",
    ),
    AnchorSpec(
        "P1",
        "input_snapshot_content_hashes",
        "Input Snapshot Hashes",
        "RunManifest.source_refs[*].input_snapshots[*].content_hash",
        "array of sha256 hex",
        "Checks input snapshot immutability.",
        "details table only",
        True,
        "Snapshot hash diff",
        "DEGRADED",
    ),
    AnchorSpec(
        "P1",
        "replay_capability",
        "Replay Capability",
        "RunManifest.replay_capability",
        "enum",
        "Shows reproducibility support.",
        "badge",
        False,
        "Replay diagnostics",
        "WARNING",
    ),
    AnchorSpec(
        "P1",
        "exact_replay_eligible",
        "Exact Replay Eligible",
        "Derived from manifest anchors",
        "boolean + blockers",
        "Quick exact replay eligibility answer.",
        "badge; blockers in details",
        False,
        "Replay blockers",
        "DEGRADED",
    ),
    AnchorSpec(
        "P1",
        "resume_contract",
        "Resume Contract",
        "runtime_config/resolved_config resume_contract",
        "object summary",
        "Checkpoint/resume semantics.",
        "details summary",
        False,
        "Checkpoint/resume details",
        "WARNING",
    ),
    AnchorSpec(
        "P1",
        "lineage_fragment_ids",
        "Lineage Fragments",
        "RunLedger.lineage_fragment_id",
        "array of ids",
        "Lineage closure emitted by run.",
        "details only",
        True,
        "Lineage panel",
        "DEGRADED",
    ),
    AnchorSpec(
        "P1",
        "artifact_refs",
        "Published Artifact Refs",
        "RunLedger artifact_published details; planned_artifacts",
        "artifact refs / paths",
        "Links identity graph to produced artifacts.",
        "details only",
        True,
        "Artifact details",
        "DEGRADED",
    ),
    AnchorSpec(
        "P1",
        "latest_event_id",
        "Ledger Watermark",
        "RunLedger latest event",
        "opaque event id",
        "Checkpoint snapshot plus ledger suffix reconstruction anchor.",
        "details only",
        True,
        "Run Ledger event table",
        "INFO",
    ),
)

__all__ = ["P1_ANCHOR_SPECS"]
