"""P2 Control Plane identity anchor specifications."""

from __future__ import annotations

from bioetl.interfaces.http.control_plane_identity.types import AnchorSpec

_DETAILS_ONLY = "details only"


P2_ANCHOR_SPECS: tuple[AnchorSpec, ...] = (
    AnchorSpec(
        "P2",
        "launch_context_hash",
        "Launch Context",
        "RunManifest.launch_context",
        "derived sha256",
        "Audit context for who/how started run.",
        "drilldown only",
        False,
        "Manifest launch_context",
        "INFO",
    ),
    AnchorSpec(
        "P2",
        "runtime_config_hash",
        "Runtime Config Hash",
        "RunManifest.runtime_config",
        "derived sha256",
        "Debug runtime flag drift.",
        "drilldown only",
        True,
        "Manifest diff",
        "INFO",
    ),
    AnchorSpec(
        "P2",
        "planned_artifacts",
        "Planned Artifacts",
        "RunManifest.planned_artifacts",
        "layer/path refs",
        "Compare planned outputs with published outputs.",
        _DETAILS_ONLY,
        True,
        "Artifact table",
        "WARNING",
    ),
    AnchorSpec(
        "P2",
        "published_artifacts",
        "Published Artifacts",
        "RunLedger artifact_published details",
        "artifact refs / paths",
        "Actual output artifacts.",
        _DETAILS_ONLY,
        True,
        "Artifact table",
        "DEGRADED",
    ),
    AnchorSpec(
        "P2",
        "component_run_ids",
        "Composite Component Runs",
        "Composite ledger event details",
        "array of UUIDs",
        "Seed/dependency/enricher run identities for composite.",
        "composite drilldown only",
        True,
        "Component manifest table",
        "DEGRADED",
    ),
    AnchorSpec(
        "P2",
        "checkpoint_file_id",
        "Checkpoint File",
        "checkpoint metadata path/id",
        "local file name / path",
        "Forensic resume storage debug.",
        "details only; never stat card",
        True,
        "Checkpoint raw view",
        "INFO",
    ),
    AnchorSpec(
        "P2",
        "lock_owner_id",
        "Lock Owner / Fencing Token",
        "runtime lock metadata",
        "opaque string",
        "Concurrency forensic anchor.",
        _DETAILS_ONLY,
        True,
        "Runtime locks panel",
        "WARNING",
    ),
    AnchorSpec(
        "P2",
        "dq_report_paths",
        "DQ Report Paths",
        "RunLedger details/runtime_config",
        "path refs",
        "Open DQ reports without metrics-label pollution.",
        _DETAILS_ONLY,
        True,
        "DQ report view",
        "INFO",
    ),
    AnchorSpec(
        "P2",
        "cross_validation_rule_ids",
        "Cross-validation Rules",
        "runtime_config/resolved_config",
        "list of string ids",
        "Composite cross-validation/nullification context.",
        _DETAILS_ONLY,
        False,
        "Cross-validation details",
        "INFO",
    ),
    AnchorSpec(
        "P2",
        "bronze_batch_ids",
        "Bronze Batch IDs",
        "source refs / ledger details",
        "UUID/list",
        "Bronze provenance for forensic replay.",
        "details only; never card",
        True,
        "Bronze lineage details",
        "INFO",
    ),
)

__all__ = ["P2_ANCHOR_SPECS"]
