"""P0/P1/P2 Control Plane identity anchor specifications."""

from __future__ import annotations

from bioetl.interfaces.http.control_plane_identity.types import AnchorSpec

TERMINAL_STATUSES = frozenset({"success", "failed", "shutdown"})
CHECKPOINT_ANCHORS = (
    "manifest_id",
    "execution_fingerprint",
    "effective_config_hash",
    "effective_config_artifact_id",
    "input_snapshot_fingerprint",
    "composite_run_identity",
)
ALLOWED_LOW_CARDINALITY_LABELS = [
    "pipeline",
    "run_type",
    "status",
    "layer",
    "event_type",
    "disposition",
    "ref_type",
    "decision_type",
    "selected_source",
]

ANCHOR_SPECS: tuple[AnchorSpec, ...] = (
    AnchorSpec(
        "P0",
        "run_id",
        "Run ID",
        "RunManifest.run_id; identity graph",
        "UUID v4",
        "Primary correlation anchor for manifest, ledger, logs, and traces.",
        "overview: short; details: full",
        True,
        "Run Manifest details; ledger by run_id; Loki/Tempo links",
        "FAILING",
    ),
    AnchorSpec(
        "P0",
        "manifest_id",
        "Manifest ID",
        "RunManifest.manifest_id; identity graph",
        "opaque string / UUID-like",
        "Immutable control-plane artifact anchor.",
        "overview: short; details: full",
        True,
        "Manifest JSON; run-manifest CLI show; ledger events",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "pipeline_name",
        "Pipeline",
        "RunManifest.pipeline_name",
        "snake_case",
        "Shows which pipeline was executed.",
        "full in card/table",
        False,
        "Pipeline dashboard; manifest filter",
        "FAILING",
    ),
    AnchorSpec(
        "P0",
        "provider_entity",
        "Provider / Entity",
        "RunManifest.provider + RunManifest.entity",
        "provider.entity",
        "Fixes dataset and contract scope.",
        "full in card/table",
        False,
        "Dataset lineage; contract registry entry",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "runtime_mode",
        "Runtime Mode",
        "RunManifest.run_type + runtime_config/launch_context flags",
        "run_type + flags",
        "Shows the runtime mode for the launch.",
        "overview badge; details tuple",
        False,
        "Manifest runtime_config and launch_context",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "execution_fingerprint",
        "Execution FP",
        "RunManifest.execution_fingerprint; identity graph",
        "sha256 hex / opaque fingerprint",
        "Semantic reproducibility and compatibility anchor.",
        "overview: short; details: full",
        True,
        "Identity graph; manifest diff; replay diagnostics",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "git_commit",
        "Git Commit",
        "RunManifest.code_provenance.git_commit",
        "git SHA",
        "Shows which code produced the result.",
        "overview: short; details: full",
        True,
        "Repository commit / release notes",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "pipeline_version",
        "Pipeline Version",
        "RunManifest.code_provenance.pipeline_version",
        "semver / string",
        "Pipeline/config contract version.",
        "full",
        False,
        "Pipeline spec / changelog",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "effective_config_hash",
        "Effective Config Hash",
        "RunCodeProvenance.effective_config_hash; checkpoint metadata",
        "sha256 hex",
        "Resolved config actually used by the run.",
        "overview: short; details: full",
        True,
        "Effective config artifact; config diff",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "effective_config_artifact_id",
        "Effective Config Artifact",
        "RunCodeProvenance.effective_config_artifact_id; base_summary",
        "artifact ref",
        "Direct handoff to resolved config.",
        "overview: short; details: full",
        True,
        "Resolved config artifact view",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "contract_ref",
        "Contract Ref",
        "RunCodeProvenance.contract_ref; contract registry",
        "provider.entity",
        "Gold/DQ contract scope.",
        "full",
        True,
        "Contract registry entry; Gold contract doc",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "contract_version",
        "Contract Version",
        "RunCodeProvenance.contract_version; contract registry",
        "semver",
        "Applied Gold/DQ contract version.",
        "full",
        False,
        "Contract registry / migration guide",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "contract_schema_hash",
        "Contract Schema Hash",
        "RunCodeProvenance.contract_schema_hash; registry identity.schema_hash",
        "sha256 hex",
        "Protects against schema drift.",
        "overview: short; details: full",
        True,
        "Contract artifact diff",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "input_snapshot_identity_fingerprint",
        "Input Snapshot FP",
        "RunManifest.source_refs[*].input_snapshots",
        "sha256 / opaque fingerprint",
        "Fixes the immutable input closure.",
        "overview: short; details: full",
        True,
        "Input snapshots details",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "input_snapshot_count",
        "Input Snapshots",
        "RunManifest.source_refs[*].input_snapshots",
        "integer + array",
        "Shows whether input closure was captured.",
        "count in overview; IDs in details",
        False,
        "Input snapshots table",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "replay_mode",
        "Replay / Backfill / Rebuild",
        "RunManifest.run_type + replay parentage",
        "enum / badge",
        "Shows whether the run is replay/backfill/rebuild/incremental.",
        "badge in overview",
        False,
        "Replay diagnostics",
        "INFO",
    ),
    AnchorSpec(
        "P0",
        "replay_of_run_id",
        "Parent Run ID",
        "RunManifest.replay_of_run_id; identity graph",
        "UUID",
        "Parent run for replay lineage.",
        "short when replay; full in details",
        True,
        "Parent manifest/ledger",
        "FAILING",
    ),
    AnchorSpec(
        "P0",
        "replay_of_manifest_id",
        "Parent Manifest ID",
        "RunManifest.replay_of_manifest_id; identity graph",
        "opaque id / UUID-like",
        "Parent manifest for replay lineage.",
        "short when replay; full in details",
        True,
        "Parent manifest details",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "checkpoint_anchor_status",
        "Checkpoint Anchors",
        "Checkpoint metadata compared with current runtime anchors",
        "OK / MISMATCH / MISSING / PARTIAL",
        "Shows whether persisted checkpoint anchors match current runtime anchors.",
        "status badge; pairwise table",
        False,
        "Checkpoint compatibility panel",
        "DEGRADED",
    ),
    AnchorSpec(
        "P0",
        "composite_run_identity",
        "Composite Run Identity",
        "Composite checkpoint metadata; runtime config",
        "UUID / opaque run-scoped id",
        "Prevents resume across different composite executions.",
        "only for composite; full in details",
        True,
        "Composite checkpoint details",
        "FAILING",
    ),
    AnchorSpec(
        "P0",
        "identity_graph_complete",
        "Identity Graph",
        "identity evidence gaps",
        "boolean + gap count",
        "Single identity gap indicator.",
        "status badge plus gap count",
        False,
        "Identity gaps table",
        "DEGRADED",
    ),
    AnchorSpec(
        "P1",
        "config_hash",
        "Source Config Hash",
        "RunCodeProvenance.config_hash",
        "sha256 hex",
        "Raw pipeline config provenance.",
        "details only; compact short",
        True,
        "Manifest/config diff",
        "WARNING",
    ),
    AnchorSpec(
        "P1",
        "dq_policy_ref",
        "DQ Policy Ref",
        "RunCodeProvenance.dq_policy_ref; contract registry",
        "string ref",
        "Applied DQ policy.",
        "full in contract/DQ details",
        True,
        "DQ contract registry",
        "DEGRADED",
    ),
    AnchorSpec(
        "P1",
        "rule_bundle_version",
        "Rule Bundle",
        "RunCodeProvenance.rule_bundle_version; contract registry",
        "semver / string",
        "DQ rule bundle version.",
        "full",
        False,
        "DQ rule bundle / migration guide",
        "DEGRADED",
    ),
    AnchorSpec(
        "P1",
        "dq_contract_compatibility_hash",
        "DQ Compat Hash",
        "RunCodeProvenance.dq_contract_compatibility_hash",
        "sha256 hex",
        "Detects DQ compatibility surface drift.",
        "details only; compact short",
        True,
        "DQ contract diff",
        "WARNING",
    ),
    AnchorSpec(
        "P1",
        "source_refs",
        "Source Refs",
        "RunManifest.source_refs",
        "array provider/entity/query/input_snapshots",
        "External input lineage closure.",
        "count in summary; full nested table",
        True,
        "Source refs panel",
        "DEGRADED",
    ),
    AnchorSpec(
        "P1",
        "input_snapshot_ids",
        "Input Snapshot IDs",
        "RunManifest.source_refs[*].input_snapshots[*].snapshot_id",
        "array of opaque ids",
        "Immutable input snapshot list.",
        "details table only",
        True,
        "Input snapshot details",
        "DEGRADED",
    ),
    AnchorSpec(
        "P1",
        "input_snapshot_content_hashes",
        "Input Snapshot Hashes",
        "RunManifest.source_refs[*].input_snapshots[*].content_hash",
        "array of sha256 hex",
        "Checks input snapshot immutability.",
        "details table only",
        True,
        "Snapshot hash diff",
        "DEGRADED",
    ),
    AnchorSpec(
        "P1",
        "replay_capability",
        "Replay Capability",
        "RunManifest.replay_capability",
        "enum",
        "Shows reproducibility support.",
        "badge",
        False,
        "Replay diagnostics",
        "WARNING",
    ),
    AnchorSpec(
        "P1",
        "exact_replay_eligible",
        "Exact Replay Eligible",
        "Derived from manifest anchors",
        "boolean + blockers",
        "Quick exact replay eligibility answer.",
        "badge; blockers in details",
        False,
        "Replay blockers",
        "DEGRADED",
    ),
    AnchorSpec(
        "P1",
        "resume_contract",
        "Resume Contract",
        "runtime_config/resolved_config resume_contract",
        "object summary",
        "Checkpoint/resume semantics.",
        "details summary",
        False,
        "Checkpoint/resume details",
        "WARNING",
    ),
    AnchorSpec(
        "P1",
        "lineage_fragment_ids",
        "Lineage Fragments",
        "RunLedger.lineage_fragment_id",
        "array of ids",
        "Lineage closure emitted by run.",
        "details only",
        True,
        "Lineage panel",
        "DEGRADED",
    ),
    AnchorSpec(
        "P1",
        "artifact_refs",
        "Published Artifact Refs",
        "RunLedger artifact_published details; planned_artifacts",
        "artifact refs / paths",
        "Links identity graph to produced artifacts.",
        "details only",
        True,
        "Artifact details",
        "DEGRADED",
    ),
    AnchorSpec(
        "P1",
        "latest_event_id",
        "Ledger Watermark",
        "RunLedger latest event",
        "opaque event id",
        "Checkpoint snapshot plus ledger suffix reconstruction anchor.",
        "details only",
        True,
        "Run Ledger event table",
        "INFO",
    ),
    AnchorSpec(
        "P2",
        "launch_context_hash",
        "Launch Context",
        "RunManifest.launch_context",
        "derived sha256",
        "Audit context for who/how started run.",
        "drilldown only",
        False,
        "Manifest launch_context",
        "INFO",
    ),
    AnchorSpec(
        "P2",
        "runtime_config_hash",
        "Runtime Config Hash",
        "RunManifest.runtime_config",
        "derived sha256",
        "Debug runtime flag drift.",
        "drilldown only",
        True,
        "Manifest diff",
        "INFO",
    ),
    AnchorSpec(
        "P2",
        "planned_artifacts",
        "Planned Artifacts",
        "RunManifest.planned_artifacts",
        "layer/path refs",
        "Compare planned outputs with published outputs.",
        "details only",
        True,
        "Artifact table",
        "WARNING",
    ),
    AnchorSpec(
        "P2",
        "published_artifacts",
        "Published Artifacts",
        "RunLedger artifact_published details",
        "artifact refs / paths",
        "Actual output artifacts.",
        "details only",
        True,
        "Artifact table",
        "DEGRADED",
    ),
    AnchorSpec(
        "P2",
        "component_run_ids",
        "Composite Component Runs",
        "Composite ledger event details",
        "array of UUIDs",
        "Seed/dependency/enricher run identities for composite.",
        "composite drilldown only",
        True,
        "Component manifest table",
        "DEGRADED",
    ),
    AnchorSpec(
        "P2",
        "checkpoint_file_id",
        "Checkpoint File",
        "checkpoint metadata path/id",
        "local file name / path",
        "Forensic resume storage debug.",
        "details only; never stat card",
        True,
        "Checkpoint raw view",
        "INFO",
    ),
    AnchorSpec(
        "P2",
        "lock_owner_id",
        "Lock Owner / Fencing Token",
        "runtime lock metadata",
        "opaque string",
        "Concurrency forensic anchor.",
        "details only",
        True,
        "Runtime locks panel",
        "WARNING",
    ),
    AnchorSpec(
        "P2",
        "dq_report_paths",
        "DQ Report Paths",
        "RunLedger details/runtime_config",
        "path refs",
        "Open DQ reports without metrics-label pollution.",
        "details only",
        True,
        "DQ report view",
        "INFO",
    ),
    AnchorSpec(
        "P2",
        "cross_validation_rule_ids",
        "Cross-validation Rules",
        "runtime_config/resolved_config",
        "list of string ids",
        "Composite cross-validation/nullification context.",
        "details only",
        False,
        "Cross-validation details",
        "INFO",
    ),
    AnchorSpec(
        "P2",
        "bronze_batch_ids",
        "Bronze Batch IDs",
        "source refs / ledger details",
        "UUID/list",
        "Bronze provenance for forensic replay.",
        "details only; never card",
        True,
        "Bronze lineage details",
        "INFO",
    ),
)

SPEC_BY_NAME = {spec.name: spec for spec in ANCHOR_SPECS}
OVERVIEW_NAMES = frozenset(
    {
        "run_id",
        "manifest_id",
        "pipeline_name",
        "provider_entity",
        "runtime_mode",
        "execution_fingerprint",
        "effective_config_hash",
        "contract_ref",
        "contract_version",
        "input_snapshot_identity_fingerprint",
        "replay_capability",
        "replay_mode",
        "checkpoint_anchor_status",
        "composite_run_identity",
        "identity_graph_complete",
    }
)
