name: Commit Lint

permissions:
  contents: read

on:
  workflow_call:
concurrency:
  group: commit-lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@f133a0d95090ef2609192b4a21f54e20af819ea9 # v6
        with:
          configFile: commitlint.config.mjs
          helpURL: https://www.conventionalcommits.org/
